### ISSUE TITLE
Results not listed (kodi 17.3, win7)

### ISSUE THREAD

**Issue by Gregsr** [elgatito/script.elementum.burst#10]
I have this message "no link found" but, in the log, there are links found. Issue is that these links are not listed.
[kodi.log](https://github.com/elgatito/script.elementum.burst/files/1615698/kodi.log)

**Comment by Nemiroff** [comment]
Low internet speed or little timeout for provider (9sec default)

**Comment by Gregsr** [comment]
It's strange because I have optical fibre.
I retested with timeout longer yesterday evening and I had same results.

**Comment by elgatito** [comment]
It does not always depend on your connection speed. 
Try setting bigger timeout.

**Comment by Gregsr** [comment]
After last updates (plugin+script), all is ok now.
Thanks
