### ISSUE TITLE
New provider

### ISSUE THREAD

**Issue by Gregsr** [elgatito/script.elementum.burst#100]
Can you add this provider please ?
https://downloadville.net/tracker/

Thanks

**Comment by chivigoku** [comment]
Hi @elgatito 

As this post is opened, I'd like to know if you can also add some Spanish web pages ;)
Here are the best. 
Hope you can help those Spanish people that want to download torrents through your addon.

https://www.elitetorrent.biz/
http://www.mejortorrent.org/

Thanks in advance for your effort !!!
Regards,
ChIvI

**Comment by elgatito** [comment]
Waiting for approval for registration....

**Comment by Gregsr** [comment]
Is it approved now?

**Comment by elgatito** [comment]
Have got no mails so far.

**Comment by elgatito** [comment]
Got no approval so far. 
You get send any account to login and test everything. Or I will just close the issue.

**Comment by Gregsr** [comment]
I realize that I can now send invitations. It is valid for 48 hours. I prefer to send it to you in private.

**Comment by elgatito** [comment]
@Gregsr you can send account information or invitation via gitter https://gitter.im/ElementumApp/Lobby

**Comment by elgatito** [comment]
Closing without getting response.
