### ISSUE TITLE
Optimize Torrent9 provider

### ISSUE THREAD

**Issue by rik91** [elgatito/script.elementum.burst#101]
Hi @elgatito,

I want to optimize the provider Torrent9 because in some case, it return no result.
The issue is that url with apostrophe (') are not correct query.

For example : 
https://www.torrent9.uno/search_torrent/l'ombre-d'emily-2018.html send by burst return 0 result 
whereas 
https://www.torrent9.uno/search_torrent/lombre-demily-2018.html return results

There is a way to configure the provider to remove specific character ?

Thanks

**Comment by elgatito** [comment]
You can enable setting in Burst to remove quote from query.

**Comment by rik91** [comment]
OK I don't seen this parameter.

It's OK for this provider, but yggtorrent requires quote to properly works on the same example...
https://www2.yggtorrent.gg/engine/search?do=search&name=lombre+demily+2018 -> 0 result
https://www2.yggtorrent.gg/engine/search?do=search&name=l'ombre+d'emily+2018 ->  1 result

There is not way to remove quote on a specific provider ??

**Comment by danny1990** [comment]
Create a file called "overrides.py" in "~/.kodi/userdata/addon_data/script.elementum.burst" and paste this
[code]
{
    "yggtorrent": {
        "parser": {
            "infohash": "",
            "name": "item('a', order=2)",
            "peers": "item(tag='td', order=9)",
            "row": "find_once('table', ('class', 'table')).find_all('tr', start=2)",
            "seeds": "item(tag='td', order=8)",
            "size": "item(tag='td', order=6)",
            "torrent": "'https://www2.yggtorrent.gg/engine/download_torrent?id=%s' % item(tag='a', attribute='target', order=3).replace('\'', '')"
        }
    }

}
[/code]

I can't verify if it works or not as i don't have an account and i'm having problems creating an account as i don't speak french. Let me know if it works for you.

**Comment by Lesproges** [comment]
> 
> 
> OK I don't seen this parameter.
> 
> It's OK for this provider, but yggtorrent requires quote to properly works on the same example...
> https://www2.yggtorrent.gg/engine/search?do=search&name=lombre+demily+2018 -> 0 result
> https://www2.yggtorrent.gg/engine/search?do=search&name=l'ombre+d'emily+2018 -> 1 result
> 
> There is no way to remove quote on a specific provider ??

For me, even with "remove quote from query" on or off : no result for me !

**Comment by antonsoroko** [comment]
this is fixed by https://github.com/elgatito/script.elementum.burst/commit/b8535d825168783c489c049ec3ac0c2f1e6c8bea

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.
