### ISSUE TITLE
New provider

### ISSUE THREAD

**Issue by zaube2** [elgatito/script.elementum.burst#114]
Can you add this provider please ? 
http://www.torrent.ai/lt/account-login.php?returnto=%2Flt%2Fmain
Thanks

**Comment by elgatito** [comment]
I have no account on that website.

**Comment by zaube2** [comment]
I can send you invitation to create an account

2019-04-17, tr, 21:00 Denis <notifications@github.com> rašė:

**Comment by elgatito** [comment]
you can send invite to denis.kuzmenok@gmail.com or just leave it here.

**Comment by elgatito** [comment]
Please, check v0.0.36.

**Comment by zaube2** [comment]
Thanks!!!

2019-04-24, tr, 20:56 Denis <notifications@github.com> rašė:
