### ISSUE TITLE
1337x.to gives irrelevant results

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/script.elementum.burst#115]
Search for the same episode works correctly on web site.
By some reason does not work properly in burst. Burst 0.0.35. In elementum i have "use original name" option enabled.

https://paste.ubuntu.com/p/ngTDTg32ft/
(2 searches, second with proxy logging enabled)

Thank you.

**Comment by antonsoroko** [comment]
![IMG_20190416_115033](https://user-images.githubusercontent.com/17964763/56199844-f4551900-603d-11e9-8d8f-edfa5cec19c6.jpg)

**Comment by elgatito** [comment]
A lot of providers have one query to search by episode number, another one for season. 
Because there are often torrents that include whole season.

**Comment by antonsoroko** [comment]
So i understand correctly that you want to sat that it actually search for s17 and not for s14e17 in this particular provider?

But sometimes it gives me only relevant results (maybe it depends on sorting by seeds, when releases with new episode have more seeds so they "suppress" old releases, not sure if it is the case)

**Comment by elgatito** [comment]
> So i understand correctly that you want to sat that it actually search for s17 and not for s14e17 in this particular provider?

Yes.
https://github.com/elgatito/script.elementum.burst/blob/v0.0.35/burst/providers/providers.json#L42

```
        "tv_keywords": "{title} s{season:2}e{episode:2}",
        "tv_keywords2": "{title} s{season:2}"
```

These queries are both sent. I will change second query for many providers. It is common to search for season, not only for episode.

**Comment by antonsoroko** [comment]
Thanks. I see.
With new tv series you usually search for one episode , with old i guess for the season pack.
But i suppose there is no way to give more priority to first or second "search string", right? (Other than edit local provider's json file, I mean)

**Comment by zynexiz** [comment]
I removed "tv_keywords2": "{title} s{season:2}" from providers.json, after that I just got the episode I was searching for :)

**Comment by antonsoroko** [comment]
@zynexiz the problem with this approach is that this file will be overwritten after burst addon update. 
But readme.md describes a better way - overrides. Have not tried it yet, though.

**Comment by zynexiz** [comment]
Yes they will, but it's quite easy to edit again. Haven't looked at overrides, just read about it. I will have a look at it.

Not sure why the "tv_keywords2": "{title} s{season:2}" is there in the first place, creating lots of irrelevant result making legit results "hidden" because of max results. Maybe better to remove it all together like I did at the source? tv_keywords2 isn't present in the other providers, just 1337x. Maybe elgatito have some insight on why this is the case? 🙂

**Comment by zynexiz** [comment]
@antonsoroko I tested the override, and it worked the same way as removing it from the providers.json. This is the code I used for 1337x provider to remove the irrelevant results. Just create the file mentioned in the description. This way it won't be overwritten in case of an update anyway :)
```
overrides = {
	 "1337x": {
		 "tv_keywords2": ""
		 }
    }
```

**Comment by elgatito** [comment]
Will be fixed in the next version.

**Comment by elgatito** [comment]
Please, check v0.0.36.

**Comment by burekas7** [comment]
I have just opened a similar issue with EZTV:
https://github.com/elgatito/script.elementum.burst/issues/117

**Comment by elgatito** [comment]
@burekas7 nothing similar, you just spam.

**Comment by antonsoroko** [comment]
Looks good for particular episode but does not show torrents for"season pack"s like https://1337x.to/sort-search/Big%20bang%20s11/size/desc/1/

Not sure if it was intended or not.

Thank you.

**Comment by elgatito** [comment]
There is no bug. 

Episode searches search for specific episode. 
Season search searches only for season packs.

```
        "season_keywords": "{title} s{season:2}",
        "season_keywords2": "",
        "tv_keywords": "{title} s{season:2}e{episode:2}",
        "tv_keywords2": "{title} {season:2}x01|S{season:2}",
        "tv_keywords_fallback": "{title} s{season}"
```

**Comment by antonsoroko** [comment]
@elgatito

Okay, could you please tell me how to search for season then? Probably i just don't know how to do it now.

Btw, Rarbg provider, for example , still offers season pack when i search for episode.

**Comment by zynexiz** [comment]
> @elgatito
> 
> Okay, could you please tell me how to search for season then? Probably i just don't know how to do it now.
> 
> Btw, Rarbg provider, for example , still offers season pack when i search for episode.

Maybe it's bit easier to use a computer for that? Think Elementum is better used for single episodes?

**Comment by elgatito** [comment]
>  how to search for season then? 

Go to list of seasons inside of Elementum. In context menu of any season choose "Select stream" - then you say burst to search for season and use "season_keywords". All other cases you use episode searches.

**Comment by antonsoroko** [comment]
Thank you! Very cool feature.

Unfortunately i still can't make 1337x provider produce reasonable results. I tried to switch sorting to size in both elementum and burst - still no packs from 1337x , only episodes. Also tried to allow torrents with 0 seed and disable all filters for search (like rip type).

(I used "select stream" if course)

https://paste.ubuntu.com/p/jWTk5Hvd7b/

**Comment by burekas7** [comment]
@elgatito 

But if there is a season torrent in the results, does it should run the relevant episode from it as usually, right?

**Comment by elgatito** [comment]
Burst is NOT removing any result, received from the website. It can remove only results without seeds or name/url/detected quality.

**Comment by antonsoroko** [comment]
What i meant is that i dont see season pack torrents like here https://1337x.to/sort-search/Big%20bang%20s11/size/desc/1/ by some reason

**Comment by elgatito** [comment]
All requests that come FROM Burst are in the log file.

**Comment by antonsoroko** [comment]
i see
```
$ grep 'Opening URL:' log.txt | wc -l
      21
$ grep 'Opening URL:' log.txt | egrep -v "[eE][0-9][0-9]"
16:48:02.440 T:18446744072612739440   DEBUG: [script.elementum.burst] Opening URL: 'https://www.1337x.to/search/the+big+bang+theory+s11/1/'
```

https://www.1337x.to/search/the+big+bang+theory+s11/1/ do default sorting by seeds and thus season pack are lost (too many sXXeXX torrents come first)

this is sad. i guess this can be avoided only by filtering "eXX" results. but not sure if you want to introduce this kind of filtering.

**Comment by elgatito** [comment]
Season queries should be sent only if episode queries are not returning any result.
Burst will never filter results, coming from the website.

**Comment by antonsoroko** [comment]
мне кажется мы друг друга не очень понимаем :-)
я использовал "select stream", видно что запрос пошел как s11, но сам 1337х дал еще и результаты с эпизодами. у них больше сидов, соотв результаты для сезона не прошли "отбор" как я вижу. я имел ввиду что избежать этого можно только если как-то получить все результаты и отсечь eXX или поменять запрос так для сезонов чтобы он сортировал по размеру - тогда паки будут в начале и попадут в бурст.
