### ISSUE TITLE
EZTV gives irrelevant results

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#117]
For example: Vikings S02E05
When running this search url (As it shown in the log) in browser I get only one correct result,
but in kodi log it shows that it returns 26 result (All of them are wrong)

`https://eztv.io/search/%27vikings%27-s02e05`

Kodi Log:
https://paste.ubuntu.com/p/nQH6NpTStp

Why is that?

Burst Elementum 0.0.36  (but it already happened before)
Elementum 0.1.29
Kodi 17.6
Windows 10, 64bit

**Comment by elgatito** [comment]
You should look in the log. You have another query to eztv: https://eztv.io:443/search/%27vikings%27-s2- 
I don't have those queries, maybe you have overrides.

**Comment by burekas7** [comment]
I haven't touch anything, I checked in the userdata folder and there is nothing with overrides.

**Comment by elgatito** [comment]
Anyway, I will remove season queries. They don't properly treat those queries.
Will be fixed in the next version.
