### ISSUE TITLE
Season Packs 

### ISSUE THREAD

**Issue by kavuraki** [elgatito/script.elementum.burst#123]
Burst doesn’t find any season packs if i go with strm file for an episode. It just finds episode torrents. Isn’t it possible to find season packages with more seeders?

If i manually search name of series s01 I can find but the thing is no season pack result if i do click a specific episode from my library. 

thanks.

**Comment by elgatito** [comment]
Some trackers has episode torrents, some have mostly season packs. 
Each tracker has own settings what to search when you need episode/movie. 
You can look at `providers.json` file or override any settings.

**Comment by kavuraki** [comment]
so what should i do? when I click from library for example:
name s01 e02
strm file

I guess it searches:
name s01 e2

but it should also search:
name s01

and should bring me the both results. 

because I know that there is a season pack on the same tracker and it has way more seeders than lonely episode torrent.

**Comment by elgatito** [comment]
> so what should i do? 

1) Use trackers that have season queries for episode searches.
2) Change queries for trackers that you like.

**Comment by kavuraki** [comment]
for example:

        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title} s{season:2}",
        "season_keywords2": "",
        "season_query": "",

It seems season_query is empty for this instance then change to what?

**Comment by elgatito** [comment]
@kavuraki `season...` are queries, used to search seasons. You need `tv_...`, they are used for episode searches.

**Comment by kavuraki** [comment]
"tv_keywords": "{title} s{season:2}e{episode:2}",
"tv_keywords2": "{title} {season:2}x01|S{season:2}",
"tv_keywords_fallback": "{title} s{season}"

I understand that from these keywords when I click a library integrated elementum strm file then 3 queries are occured:

first query with "{title} s{season:2}e{episode:2}",
second query with "{title} {season:2}x01|S{season:2}",
third query with "{title} s{season}"

for each providers I had enabled. 

Then It gathers all results and shows me.

In this respect, my problem is lack of "tv_keywords_fallback" (third query) results because I am sure that there exist season packs with plenty seeders. I want to play the episode from that pack not from lonely episode torrent.

Sorry that I may be insistent and boring...

**Comment by elgatito** [comment]
@kavuraki `tv_keywords` and `tv_keywords2` are queried always, does not matter if first one has any results or not. `tv_keywords_fallback` is run only when usual queries get no results.

**Comment by kavuraki** [comment]
I edited providers.json

this:
"tv_keywords": "{title} s{season:2}e{episode:2}",
"tv_keywords2": "{title} {season:2}x01|S{season:2}",
"tv_keywords_fallback": "{title} s{season}"

to:
"tv_keywords": "{title} s{season:2}e{episode:2}",
"tv_keywords_fallback": "{title} s{season}",
"tv_keywords2": "{title} {season:2}x01|S{season:2}"

on the sites that I enabled.

Still no season packs are found from the trackers that I know the pack exists %100
just finds the torrents related to that episode which have less sources than packs.

What would be the reason behind this?

**Comment by elgatito** [comment]
Log file can show what is searched and what query is used for search.
Changing in `providers.json` is a bad practice, this file will be overwritten by plugin update. You should use `overrides.json` for it.

**Comment by kavuraki** [comment]
resolved with changing
"tv_keywords2": "{title} s{season}" 
to
"tv_keywords2": "{title} s{season:2}"

where should I put the overrides.json exactly?

**Comment by elgatito** [comment]
http://elementum.surge.sh/burst/override/
