### ISSUE TITLE
How to add a new provider on macos?

### ISSUE THREAD

**Issue by jefersontonin** [elgatito/script.elementum.burst#124]
How can I add a new provider on macos?
My .kodi folder don't have the userdata folder inside.
I tried to create the path used with linux and don't work.
Thank you.

**Comment by elgatito** [comment]
@jefersontonin Userdata location differs on platforms: https://kodi.wiki/view/Userdata#Location_of_the_userdata_folder

**Comment by jefersontonin** [comment]
Thank you
