### ISSUE TITLE
RARBG not **always** getting results

### ISSUE THREAD

**Issue by Yutsa** [elgatito/script.elementum.burst#126]
This is really weird but sometimes provider won't get results from RARBG, but sometimes it will.

I tried 3 times for the same episode, the first two attempts failed but the third returned results.

Here's the [log](http://paste.kodi.tv/fuweliwayu)

You can see my three requests. We can see in the logs that the behaviour between the failed attempts and the one that succeeded isn't the same.

## Working request

Burst sent only two requests :
* one with `good+omens+s01e01` which returned results 
* the other with `good+omens+01x01%7CS01` which didn't return any result.

## Failing request

This time Burst sent three requests :

* one with `good+omens+s01e01` which returned results 
* another with `good+omens+01x01%7CS01` which didn't return any result.
* finally one with `good+omens+s1` which didn't return any result

We can clearly see that the api returns a 429 return code for too many requests, I don't know if there's a workaround.

**Comment by konvar** [comment]
I have to search twice the same episode/movie to get a result (from RARBG), I have not posted so far because it is not a big problem.

**Comment by elgatito** [comment]
Looks like Rarbg is responding with 429 error (too much requests). I will add a retry option for that error in the next version of Burst.

**Comment by elgatito** [comment]
Can you try with the latest version?
It problem is still there - please, send new log file.

**Comment by Kristijan1001** [comment]
> Can you try with the latest version?
> It problem is still there - please, send new log file.

@elgatito could you check this out too:

https://github.com/elgatito/script.elementum.burst/issues/132
