### ISSUE TITLE
Getting almost no results at all

### ISSUE THREAD

**Issue by drulo** [elgatito/script.elementum.burst#131]
Since last week or so, I'm not getting results for the 7 providers I have. I just get results from 1337 and a single result for 1080p and the rest is for 720p. How can I get a log from the moment i execute the search until the moment I get the results and share it here? I'm using a kodi 18.3 on a beelink mx III.

**Comment by elgatito** [comment]
http://elementum.surge.sh/contribute/log/
Provide a log file with debugging enabled.

**Comment by elgatito** [comment]
Closing without getting response.
