### ISSUE TITLE
RARBG Doesn't bring results possibly because of "Special Characters" Solution: Search by IMDB Code instead.

### ISSUE THREAD

**Issue by Kristijan1001** [elgatito/script.elementum.burst#132]
I am assuming this is a problem only with special characters, since i have only encountered this like on movies like Pokemon that contain a special charterer "é", I suggest for it an IMDB Code Search instead, since RARBG allows it . So it should fix this kind of problems.

**Comment by elgatito** [comment]
We cannot remove some chars for one provider and leave it for another one.
