### ISSUE TITLE
Nyaa: Add a new scraping template

### ISSUE THREAD

**Issue by PrevotYann** [elgatito/script.elementum.burst#133]
Hello there !
When we seek for anime through widgets, it searches the shows like this : 

_Exemple here for Fire Force latest episode atm :_ 

Fire Force S01E05

But on Nyaa there is not a single S01E05 torrents, but a bunch of "Fire Force - 05"

Would this be possible to add for this provider only maybe, a template to find : 
ShowName - _EpisodeNumber_ instead of ShowName - S_SeasonNumber_E_EpisodeNumber_

Would solve lots of issues not finding for animes with OpenMeta widget > Elementum source :)

**Comment by konvar** [comment]
For anime there is a simple solution, absolut number for each episode.

"Absolute numbering.

Anime TV shows are usually considered only one season. Trakt displays absolute numbers (in parenthesis) to help locate episodes. You’ll see this when viewing a TV show, season, episode, your calendars, and your dashboard. We get absolute numbers from TVDB so please add them there if any are missing."

**Comment by danny1990** [comment]
I don't watch anime so i don't know which shows to test it on. If you want to test it yourself then you can edit providers.json (in /kodi/addons/script.elementum.burst/providers) search for Nyaa then under parser look for

`"anime_keywords": "{title:original} {episode}",`

Just change {episode} to {episode:2} that will format the episode numbers such as 01 rather than 1.

**Comment by PrevotYann** [comment]
> I don't watch anime so i don't know which shows to test it on. If you want to test it yourself then you can edit providers.json (in /kodi/addons/script.elementum.burst/providers) search for Nyaa then look for
> 
> `"anime_keywords": "{title:original} {episode}",`
> 
> Just change {episode} to {episode:2} that will format the episode numbers such as 01 rather than 1.

Working ! Thank's dude !
