### ISSUE TITLE
Update for Providers

### ISSUE THREAD

**Issue by davidecasadei** [elgatito/script.elementum.burst#136]
Hello,
I have modified the link of this site and now the provider works.
This is theupdated json code:

Il corsaro nero

"ilcorsaronero": {
        "enabled": true,
        "predefined": false,
        "private": false,
        "name": "Il Corsaro Nero",
        "languages": "it",
        "anime_extra": "",
        "anime_keywords": "{title:it} {episode}",
        "anime_query": "",
        "base_url": "http://ilcorsaronero.unblocker.cc/argh.php?search=QUERYEXTRA",
        "color": "FF919232",
        "general_extra": "",
        "general_keywords": "{title:it}",
        "general_query": "",
        "language": "it",
        "login_failed": "",
        "login_object": "",
        "login_path": null,
        "movie_extra": "",
        "movie_extra2": "",
        "movie_keywords": "{title:it} {year}",
        "movie_keywords2": "{title:original} {year}",
        "movie_query": "",
        "parser": {
            "infohash": "item(tag='input', attribute='value')",
            "name": "item('a', order=2)",
            "peers": "item(tag='td', order=6)",
            "row": "find_all('tr', ('class', ['odd', 'odd2']))",
            "seeds": "item(tag='td', order=5)",
            "size": "item(tag='td', order=2)",
            "torrent": "'magnet:?xt=urn:btih:%s' % item(tag='input', attribute='value')"
        },
        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title:it} S{season:2}",
        "season_keywords2": "{title:original} S{season:2}",
        "season_query": "",
        "separator": "+",
        "show_query": "",
        "subpage": false,
        "tv_extra": "",
        "tv_extra2": "",
        "tv_keywords": "{title:it} s{season:2}e{episode:2}",
        "tv_keywords2": "{title:original} s{season:2}e{episode:2}",
        "tv_keywords_fallback": "{title:it} s{season}"
    }

ITorrent.ws

"itorrent" : {
        "enabled": true,
        "predefined": false,
        "private" : false,
        "name" : "iTorrent",
        "languages" : "hu",
        "anime_extra" : null,
        "anime_keywords" : null,
        "anime_query" : null,
        "base_url" : "https://itorrent.ws/torrentek/title/QUERY/",
        "color" : "FFF14E13",
        "general_extra" : "",
        "general_keywords" : "{title:original}",
        "general_query" : "",
        "language" : null,
        "login_failed" : "",
        "login_object" : "",
        "login_path" : null,
        "movie_extra" : "",
        "movie_keywords" : "{title:original} {year}",
        "movie_query" : "",
        "parser" : {
            "infohash" : "",
            "name" : "item(tag='a', order=1)",
            "row": "find_once('table', ('class', ['table', 'main-table', 'table-striped'])).find_all('tr', start=1)",
            "seeds" : "item(tag='td', order=7)",
            "peers" : "item(tag='td', order=8)",
            "size" : "item(tag='td', order=5)",
            "torrent" : "('https://itorrent.ws/%s' % item(tag='a', attribute='href', order=1))"
        },
        "season_extra" : "",
        "season_extra2" : "",
        "season_keywords" : "{title:original} s{season:2}",
        "season_keywords2" : "",
        "season_query" : "",
        "separator" : "+",
        "show_query" : "",
        "subpage" : true,
        "tv_extra" : "",
        "tv_extra2" : "",
        "tv_keywords" : "{title:original} s{season:2}e{episode:2}",
        "tv_keywords2": "{title:originak} {season:2}x01|S{season:2}",
        "tv_keywords_fallback": "{title:original} s{season}"
    }

**Comment by elgatito** [comment]
@davidecasadei is it safe to use external service?

**Comment by mackomac** [comment]
compared to original json at itorrent now get list of torrents but cant play at all..
@elgatito should check and somehow mix this updated and original codes for making work itorrent provider. Thanks ;)

**Comment by elgatito** [comment]
Ilcorsaronero and Itorrent will work with new version of Burst and Elementum 0.1.39 (and later).
