### ISSUE TITLE
Finding almost no results in some providers

### ISSUE THREAD

**Issue by Expolio** [elgatito/script.elementum.burst#137]
Hi, I have noticed that when i use quasar i found a lot more of providers than elementum burst with the same configuration ,is there anytihng i cando to use quasar burst with the elementum daemon?
PD:the providers which give more results are 1337x and magnetdl .
log: [http://paste.kodi.tv/oxemelerel](url)
thanks a lot for your work .

**Comment by elgatito** [comment]
Elementum's Burst has different search queries and many other changes. You can't use Burst from Quasar.
