### ISSUE TITLE
IPTorrents stopped working

### ISSUE THREAD

**Issue by Allebale** [elgatito/script.elementum.burst#138]
I can't get any results from IPT anymore, I've tried turning on/off all proxy settings but it wont work anymore. I got it to work on Friday with these settings, but after a day it stopped working again. https://tinyurl.com/y5nwn5a3

It also wont work with or without a VPN.

Log: https://pastebin.com/F7RMAxxv

Basically i think its a cloudflare problem since its shows the 503 error

**Comment by Allebale** [comment]
updated the log with proxy requests

**Comment by elgatito** [comment]
They have enabled cloudflare protection.

**Comment by Allebale** [comment]
Is there any way to get it to work again? Thanks for responding.

**Comment by elgatito** [comment]
@Allebale  No, existing cloudflare scraper is not able to bypass it. Same issue with Yggtorrent and few others.

**Comment by Allebale** [comment]
Alright.

**Comment by elgatito** [comment]
Will be working with new version of Burst and Elementum 0.1.39 (and later).

**Comment by Allebale** [comment]
Thank you so much!
