### ISSUE TITLE
Itorrent Decode error

### ISSUE THREAD

**Issue by mackomac** [elgatito/script.elementum.burst#139]
There is a decoding error in Itorrent(hungarian open tracker) providers.js
when i try find a movie Elementum says found nothing but in kodi log im guess Elementum burst found title but in decoding there is something wrong.
example: "NOTICE: [plugin.video.elementum] [33mWARN  linkssearch  ▶ 1                [0mResolve failed for https://itorrent.ws/torrentfiles/21418/aladdin_and_the_death_lamp_2012_custom_dvdrip_xvid_hun_sln.torrent : Decode error: Cant store a []interface{} into string"
im not a coder but maybe who expert in coding can fix this issue easy!
thanks if anyone fix it!!
![kodilog](https://user-images.githubusercontent.com/55044220/64484657-d7e89180-d215-11e9-8bdc-a886561aa1a3.JPG)

**Comment by elgatito** [comment]
Something with torrent file format. I have tried several items without no luck.

**Comment by mackomac** [comment]
in previous version i was modified providers.json as i read in post: [https://github.com/elgatito/script.elementum.burst/issues/136](url) by @davidecasadei in this case Itorrent work fine but you must disable Ecryption in elementum/torrent settings. (if Burst update itself to new version the providers.json also go back to original so we lose this mod) /as i reported its a WORKING fix (you can try) should fix in next relase of burst providers.json/ thanks
![fix](https://user-images.githubusercontent.com/55044220/65783308-d55fc480-e14f-11e9-9f02-7acf2dc4113e.JPG)

**Comment by elgatito** [comment]
@mackomac  never change `providers.json`, it is overwritten with every plugin update.
There is no encryption in Elementum. Error is caused by wrong format of torrent file, that we get from itorrent. 
In suggested fix we have to get each torrent page and get magnet from it. So we will need to make a lot of requests. But I don't see other ways now, so adding this to the next release.
