### ISSUE TITLE
elmentum 0.1.39+Burst 0.0.38

### ISSUE THREAD

**Issue by mackomac** [elgatito/script.elementum.burst#140]
in Kodi elementum+Burst updated itself from 0.1.37 to 0.1.39 and also Burst updated from version "master" to 0.0.38.
issues so far: All title and info panel only english language (in previous version was Hungarian its my language!) BUT fanart pic is hungarian /weird/...probably for this if i press any title getting no results as my providers all hungarian.

2. in previous version i was modified providers.json as i read in post: [https://github.com/elgatito/script.elementum.burst/issues/136](url) by @davidecasadei in this case Itorrent work fine but you must disable Ecryption in elementum/torrent settings. in this new version isnt matter if disable or enable encryption Itorrent dont work at all (still parsing error in .json)

**Comment by elgatito** [comment]
I have answered in another issue. Do not modify `providers.json` file. If you have any issues - provide logs/screenshots or other information to identify the problem.
