### ISSUE TITLE
Rutracker playback failed

### ISSUE THREAD

**Issue by ilanerukh** [elgatito/script.elementum.burst#141]
Hello, I'm trying to watch shows via rutracker. I can find the results in the search bar but the playback is failing. This morning the same torrent worked fine.

Here is the log file:
https://pastebin.com/HngeZsDC

**Comment by ilanerukh** [comment]
Never mind, I cleared the database and cache and now it works fine.

**Comment by elgatito** [comment]
There was a strange error with non existing torrent file path, but bad there is no full log.
Closing.
