### ISSUE TITLE
New Provider (idope replacement)

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#143]
When entering to this url:
https://idope.xyz/

There is this message:
![image](https://user-images.githubusercontent.com/13424257/66274130-fb8a1080-e883-11e9-8ef4-487222776085.png)

So there is a new provider with this url:
https://torrentz2k.xyz/

**Comment by elgatito** [comment]
Strange search there.
"Avengers" is found, but "Avengers 2018" is not.
Does not seem to be usable for searches.

**Comment by elgatito** [comment]
Will be added in the next version.

**Comment by elgatito** [comment]
Please, try v0.0.42.

**Comment by burekas7** [comment]
Works ok. Thanks.
Only one thing there is no logo for the provider in the results list.

**Comment by elgatito** [comment]
To add a logo - it has to be manually created. 
You can do that if you want.
