### ISSUE TITLE
Need to fix fallback/season search for ETTV

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#145]
Similar the issue I had with ygg (https://github.com/elgatito/script.elementum.burst/issues/142)

search url from the log, for example:
https://www.ettv.to:443/torrents-search.php?search=vikings%20s2&cat=0&incldead=0&lang=0

It searching with this format of "s2" instead of "s02"

Thanks.

**Comment by burekas7** [comment]
@elgatito 
Can you please check this request?

Thanks.

**Comment by burekas7** [comment]
Regarding ETTV and also MagnetDL

Elementum Burst 0.0.42
Elementum : 0.1.44

Kodi Log: https://paste.ubuntu.com/p/5yTmGCrWfq/
---

Why when I run this url in a browser I get results:

The fallback url: 
`ETTV search URL:  https://www.ettv.to/torrents-search.php?search=westworld%20s02&cat=0&incldead=0&lang=0`

Episode URL:
`ETTV search URL: https://www.ettv.tv/torrents-search.php?search=westworld%20s02e03&cat=0&incldead=0&lang=0`

But in the log ETTV return 0 results, why?
`ETTV returned  0 results in 20.8 seconds`

* By the way, what is this url?
`Episode URL: https://www.ettv.tv/torrents-search.php?search=QUERYEXTRA&cat=0&incldead=0&lang=0`

What is "QUERYEXTRA" and why does it search for it?


* I also see this strange fallback url:
`https://www.ettv.tv/torrents-search.php?search=westworld%2002x01%7CS02&cat=0&incldead=0&lang=0`

Which searching for:
westworld 02x01|S02

Instead of
westworld S02
Like the first one.

---

Also regarding MagnetDL:

In the log MagnetDL return 0 results, why?
`MagnetDL returned  0 results in 13.7 seconds`

The fallback url: (Has results)
`MagnetDL search URL: https://www.magnetdl.com/v/vikings-s03/`

Episode URL: (Has results)
`MagnetDL search URL: https://www.magnetdl.com/v/vikings-s03e01/`

* By the way, what is this url? 
(This url doesn't work: 404)
`MagnetDL search URL: https://www.magnetdl.com/v/vikings-03x01%7CS03/`

The same regarding the "QUERYEXTRA":
`Episode URL: https://www.magnetdl.com/FIRSTLETTER/QUERYEXTRA/`

**Comment by elgatito** [comment]
MagnetDL always returns empty page, probably because of some defense.
ETTV will be fixed in the next version.

**Comment by burekas7** [comment]
Thanks.
So for now is MagnetDL useless?
We can do something about that?

**Comment by elgatito** [comment]
> So for now is MagnetDL useless?

Probably.

> Can we do something about that?

Not from my side. I already tried to fix.

**Comment by burekas7** [comment]
But how I do get MagnetDL result when testing with the old Quasar & Quasar Burst

Kodi Log: https://paste.ubuntu.com/p/cp3XPR4T9T

![image](https://user-images.githubusercontent.com/13424257/71626985-9f235c80-2bf8-11ea-9353-06bda7e146d9.png)

**Comment by elgatito** [comment]
@burekas7 you can investigate, make appropriate changes and submit a PR. PRs are always welcome.

**Comment by burekas7** [comment]
But I don't have access to the code (it's exe file), 
and I don't know how it actually works besides the search urls from the log.

**Comment by elgatito** [comment]
Update to Burst 0.0.44. 
Magnetdl should work. They have filters on http headers.

Code of Elementum is open: https://github.com/elgatito/elementum

**Comment by burekas7** [comment]
Regarding 0.0.44

1)  ETTV:
In 0.0.43 I did get result from ETTV but they wasn't included in the results screen. (Why?)
But in 0.0.44 it back again show 0 results from ETTV.

Kodi Log (0.0.44) : https://paste.ubuntu.com/p/jGgwy2RCg9
>>>>>> ettv would send 0 torrents to Elementum <<<<<<<
Kodi Log (0.0.43): https://paste.ubuntu.com/p/h9skY9SYy2
>>>>>> ettv would send 3 torrents to Elementum <<<<<<<

2) MagnetDL:
Works ok now, Thanks.

**Comment by burekas7** [comment]
When I run for The Witcher S01E04
ETTV found results but they are not shown in the results screen
`[ettv] >>>>>> ettv would send 4 torrents to Elementum <<<<<<<`
Kodi Log: https://paste.ubuntu.com/p/fS352zCgcq

But when I run it for Westworld S02E03 the results from ETTV are shown.
[ettv] >>>>>> ettv would send 3 torrents to Elementum <<<<<<<
Kodi Log: https://paste.ubuntu.com/p/cTWmZgScJb/

What is the difference?
