### ISSUE TITLE
[Request] Add "Il Corsaro Viola"

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#146]
Hi.
Please add "Il Corsaro Viola" http://ilcorsaroviola.info/ to the Public trackers list.

Thank you!

**Comment by elgatito** [comment]
@iz8mbw It is the same as is corsaro blue , you can see in the bottom of the page. And Il corsaro blu is already in the list.

**Comment by iz8mbw** [comment]
Ok, sorry for that
