### ISSUE TITLE
TNT Village closed but replaced by corsaro.red

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#151]
Hi.
"TNT Village" has been closed but it was replaced by https://corsaro.red/

Please remove "TNT Village" and add "Corsaro.red" https://corsaro.red/

Thank you!!!

**Comment by elgatito** [comment]
WIll be added in the next version.

**Comment by iz8mbw** [comment]
Great!!

**Comment by elgatito** [comment]
Please, try v0.0.42.
