### ISSUE TITLE
Torrentz provider can't find some movies.

### ISSUE THREAD

**Issue by Dhionatha6** [elgatito/script.elementum.burst#153]
When I search for a movie in Portuguese Brazil it does not return the same number of results as when searching directly for the site, and some return 0 results and searching the site the movies are shown.
What is the problem?

**Comment by elgatito** [comment]
Please, post kodi.log, showing what you do and what it gets, if you want any help.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
@Dhionatha6 please, provide a log file.

**Comment by elgatito** [comment]
Closing without getting response.
