### ISSUE TITLE
Не работает поиск на определенных торрент трекерах

### ISSUE THREAD

**Issue by Agdiru** [elgatito/script.elementum.burst#155]
При поиске на данных торрент трекерах Megapeer, Kinozal, Nnmclub
Не находит раздачи, лог прикрепляю
[spmc.log](https://github.com/elgatito/script.elementum.burst/files/3897253/spmc.log)

**Comment by elgatito** [comment]
Megapeer, Nnmclub работают нормально. У вас возможно блокируются трекеры.
Кинозал будет отключен, там ограничение на скичивание торрентов.
