### ISSUE TITLE
Limetorrents doesn't work

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#156]
Hi.
Limetorrents in Elementum does not work. 
Hope in a new version that solve this issue. 
Thank you.

**Comment by elgatito** [comment]
@iz8mbw CloudFlare has updated the defense, so you will need new version of Elementum (0.1.44 and so on) and new version of Burst. Should be in a few days.

**Comment by iz8mbw** [comment]
Hi Danis. Thank you, I hope this will also solve problems with Limetorrents.

**Comment by elgatito** [comment]
Should work fine now with the latest version of Elementum and Burst.

**Comment by iz8mbw** [comment]
Just testing. No results from Limetorrents and for "Il Corsaro Nero" search is Ok but cannot put in play (search gives results but Elementum is still in "Resolving magnet link")....

**Comment by elgatito** [comment]
@iz8mbw Log is required.

**Comment by elgatito** [comment]
I have tried both Limetorrents and Il Corsaro Nero - both torrents started fine, magnets were resolved.
Make sure you enabled DHT in Elementum to resolve magnets.

**Comment by iz8mbw** [comment]
I'll test it better later or tomorrow and provide log in case of problems. Thank you Denis for your work, and I hope you will have time to improve Elementum also to be supported for Kodi 19 (newest python).

**Comment by iz8mbw** [comment]
Hi Danis, here https://pastebin.com/sEtxs9Ly the Kodi log.
What I have done:

1. Started Kodi
2. Search with Elementum for "independence day ita"

What happens:

1. LimeTorrents returned 0 results

what I did:

1. I selected a results from "Il Corsaro Nero"

What happens:

1. Elementum always waiting for "Resolving magnet link" and did not open the Torrent.


About LimeTorrents
As you can see in the log (line 836 and line 901), LimeTorrents returned 0 results I think because LimeTorrents need "-" instead of "%20" as space character in the URL and it does not like the last "/0" in the URL.
In fact, I go on "https://www.limetorrents.info/search/all/independence%20day%20ita/seeds/1/0" LimeTorrents redirect me on the HomePage, instead if I go on "https://www.limetorrents.info/search/all/independence-day-ita/seeds/1/" I can see results.

About "Il Corsaro Nero" I see various "Resolve failed" and "Cannot write TLS response header".

Thank you!

**Comment by iz8mbw** [comment]
Hi Danis, this my PR works for me for Limetorrents https://github.com/elgatito/script.elementum.burst/pull/160

**Comment by elgatito** [comment]
> Elementum always waiting for "Resolving magnet link" and did not open the Torrent.

Elementum cannot resolve magnet link, so it cannot start download.

**Comment by iz8mbw** [comment]
Have a solution for that?

**Comment by elgatito** [comment]
@iz8mbw There is no solution. You should check your network or use torrents with trackers, not magnets.

**Comment by iz8mbw** [comment]
How can I set to use trackers and not magnets for "Il Corsaro Nero"? (since I have problem only with "Il Corsaro Nero")

**Comment by elgatito** [comment]
> How can I set to use trackers and not magnets for "Il Corsaro Nero"? (since I have problem only with "Il Corsaro Nero")

Each provider usually has only one option, magnet or torrent files. We prefer magnets as they are independent.
