### ISSUE TITLE
Provider "TorLock" is not working... just changing the domain fixed the problem

### ISSUE THREAD

**Issue by zequi** [elgatito/script.elementum.burst#158]
Hi Friends!
The provider TORLOCK is not working, the download of the .torrent doesn't work.
It appears that just slightly  changing the DOMAIN you can fix the problem.

Now the domain is _www.torlock2.com_
I have tried to change to _www.torlock.com_ and it worked.

Perhaps It can be related with the CLOUDFARE issue that you commented.
;)

**Comment by elgatito** [comment]
@zequi for me both domain work the same, the problem with torlock is that mostly where are "0" seeds for each torrent, so they are filtered from results and you get "no torrents".

**Comment by elgatito** [comment]
Closing as Torlock is returning fine with the latest versions.

**Comment by zequi** [comment]
Yep! With the latest version from yesterday, now it works :)
Anyway, as you said, this provider gives "no torrents".

Any help you need, just ask for it (testing, whatever,...)
