### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by sapiora** [elgatito/script.elementum.burst#162]
On Sony XE9005 with Kodi 18.5 and version of Elementum 0.1.44 and Elementum Burst 0.0.42 when I choose a movie or TV show and when it starts playing the video plays for about 5-10 seconds and then black screen appears and I can not do anything but to close Kodi using the TV button on my TV remote control and then Force Close it from the application menu.

**Comment by elgatito** [comment]
@sapiora your problem is not connected to Burst, nor Elementum. 
Maybe you run out of memory.
If you think it is caused by Elementum - then stop using it, for sure.

**Comment by sapiora** [comment]
Sir,
the issue started after the last update. I love Elementum and am grateful for your efforts and spending your time for people like me. I do not want to stop using your product.

**Comment by sapiora** [comment]
Well Sir,
you were right. I had moved the Kodi on a flash drive (16GB) that was formatted to expand the TV's memory. Now I transferred it back to the TV's memory and everything is working correct. Thank you for your help! I apologize for reporting the issue.

However your sentence, and I quote: "If you think it is caused by Elementum - then stop using it, for sure.", was not polite and I do not know why. If I offended you somehow, please forgive me. I understand that many people are bugging you with a lot of useless reports (like mine).

I wish you happy meeting the New Year and once again Thank you for what you do!
