### ISSUE TITLE
[Request] Add "SkyTorrents"

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#163]
Hi.
Please add "SkyTorrents" https://www.skytorrents.lol/ to the Public trackers list.

Thank you!

**Comment by elgatito** [comment]
Would be re-added in the next version.

**Comment by iz8mbw** [comment]
Thanks and HNY!

**Comment by elgatito** [comment]
Is available in v0.0.43.

**Comment by iz8mbw** [comment]
added in v0.0.43.
