### ISSUE TITLE
Problem with PirateBay

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#170]
Probably the url is changed or something.
Stop getting results from him, and it delays the search progress.

Thanks

Elementum Burst 0.0.46

Kodi Debug Log:
https://paste.ubuntu.com/p/Zr933MTRcM

**Comment by burekas7** [comment]
Can you update the url to this one?
https://thepiratebay1.com

Thanks.

**Comment by elgatito** [comment]
WIll be fixed in the next version.
