### ISSUE TITLE
Add provider: idope is back to work

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#175]
Hi,

If it can be done, please add back **idope** to the providers.
url: https://idope.se

Thanks.

@elgatito

**Comment by elgatito** [comment]
@burekas7 looks fine, returning it.

**Comment by burekas7** [comment]
@elgatito 

Hi,
Do you know why idope get into timeout?
In this log I put it on 60 sec but even with 90 sec it get timeout.
The url is responding.

Kodi debug log:
https://paste.ubuntu.com/p/VQ2WfJzNt3

Thanks.

**Comment by burekas7** [comment]
The searching and getting results from it is ok now.
But there is a problem to download/play the file from it.

Kodi Debug Log:
https://paste.ubuntu.com/p/cMm6xFfsY7

What is the reason?

**Comment by elgatito** [comment]
@burekas7 No problems at all with it. You have timeouts resolving magnets.

**Comment by burekas7** [comment]
@elgatito 

This is the first thing I checked before posting here.
I set it on 40 seconds! resolving timeout, and still it was the same.

But I will try it again with a different item and check it.
