### ISSUE TITLE
Only x264 or H264 results

### ISSUE THREAD

**Issue by john3voltas** [elgatito/script.elementum.burst#177]
I'm currently using a Raspberry Pi3B+.
It doens't have h265/x265 hardware decoding capabilities.
Is there a way that I can filter the results for only h264/x264 torrents?
Thanks

**Comment by axelsimon** [comment]
Yes, you can put keywords to be excluded in the settings.

**Comment by john3voltas** [comment]
Thanks to @axelsimon I found a way to workaround my issue.
Solved.
