### ISSUE TITLE
[Request] Kickass Update

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#179]
Hi,

The current Kickass url is no longer working (https://katcr.co/)

There are two new options:
https://katcr.to/
https://kickasstorrents.to/

Also the search url patter is different:
The old:
https://katcr.co/katsearch/page/1/westworld%20s02e03
The new:
https://katcr.to/usearch/westworld%20S02E03/

Thanks.

**Comment by shmizan** [comment]
you can set provider aliases in settings, that's how I got "the pirate bay" to work again..

**Comment by burekas7** [comment]
@shmizan 
Thanks, I know it.
But not everyone knows how to do it or this option is exist at all. So I open this issue to fix it for everyone.
Some maybe doesn't the provider they I preffer to use is stop working.

And by the way, regarding to this issue with Kickass, the search pattern was changed also.
So for this case, changing of the provider aliases is not the only fix that should be done here.

p.s.
The PirateBay was fixed in the last updated according to my issue that I've opened (So you can cancel the change you did, if it's still there)

**Comment by burekas7** [comment]
Update:
It seems that this url: https://katcr.co/ back to work, 
but it's different from this one: https://katcr.to/

So I don't know who is the real Kickass provider, I think the ".to"  is the correct one.

**Comment by elgatito** [comment]
@burekas7 I have fixed getting torrent link for Kickass, should be much more results from it.

**Comment by burekas7** [comment]
@elgatito 
Hi,
There is Timeout error again with Kickass.

Kodi Log: https://paste.ubuntu.com/p/D4pD9hYgCt

**Comment by burekas7** [comment]
@elgatito 
Hi,
Can you update the Kickass info according to first comment.
The current info is not working.

Thanks.

Log: https://paste.ubuntu.com/p/gkXJdHrbp4
Burst 0.0.49
