### ISSUE TITLE
Only getting 4k remux on RARBG

### ISSUE THREAD

**Issue by override187** [elgatito/script.elementum.burst#18]
Hi, I always getting only remuxes for 4k from RARBG while there are x265 4k rips with more seeders and smaller size. I setup Elementum to sort torrents by resolution, choose 4k in burst, and use only RARBG provider in burst but results are same, always getting    only big remuxes.

**Comment by elgatito** [comment]
Please, provide kodi.log 
http://kodi.wiki/view/Log_file/Easy

**Comment by override187** [comment]
https://paste.ubuntu.com/26501044/

**Comment by override187** [comment]
Sorry, here is full log

https://paste.ubuntu.com/26519575/

**Comment by elgatito** [comment]
I have tested the same movie with rarbg, and get 2 movies, both around 75 GB. Both are 4K.
There was a bug in elementum which could say 1080p in the results list (instead of a real 4K), but results are what we get from rarbg.
You can search in the log messages `Resolution not allowed`, and you can see what is the torrent's name. 

You feel we are filtering more than needed?

**Comment by override187** [comment]
I looked at the log already, and this 2 4k torrents are only one 4k that we get from RARBG, while on the website there is around 10 4k torrents available for that movie. So is it maybe a problem in rarbgs API or burst doing something wrong when filtering 4k because we got bunch 1080p torrents but only 2 4k.

**Comment by elgatito** [comment]
There are really only 2 items returned from their api.
Can you share the link to website results that you refer to?

**Comment by override187** [comment]
https://rarbgmirror.org/torrents.php?search=Blade+runner&category%5B%5D=50&category%5B%5D=51&category%5B%5D=52&category%5B%5D=46

**Comment by elgatito** [comment]
Ha. By default they search for movies only in certain category, I have added all the categories explicitly, and now getting this for "4K resolution only".

How do you like:
![image](https://user-images.githubusercontent.com/1247242/35851720-84e93a54-0b31-11e8-868f-41964ee22ea1.png)

**Comment by elgatito** [comment]
It will be included in the next version.

**Comment by override187** [comment]
Wow, that was fast, thank you.

**Comment by elgatito** [comment]
Have you tested the latest version? Issue is fixed?

**Comment by hoshsadiq** [comment]
I will say I get many more results for rarbg

**Comment by override187** [comment]
Yes, issue is fixed.
