### ISSUE TITLE
how to add imdb id or tvdb id to the provider request?

### ISSUE THREAD

**Issue by shmizan** [elgatito/script.elementum.burst#180]
@elgatito I am trying to build a provider that accepts tvdb id as a search param.
is there a way to add it to the search URL, like {title}?

**Comment by elgatito** [comment]
@shmizan you can see what is sent to search plugins from Elementum. Don't think there are any IDs.

**Comment by shmizan** [comment]
yes I found it now.
in the payload that is sent when using run_provider(provider, payload, method) which is found in burst.py, I see the IDs:
'tvdb_id', 'imdb_id', among other information.
now I just need to add to provider.py:
```
if 'tvdbid' in keyword:
                text = text.replace('{%s}' % keyword, str(self.info["tvdb_id"]))
```
and then I can reference {tvdbid} in my provider.

thanks again for this amazing software @elgatito !! 💯

**Comment by elgatito** [comment]
@shmizan I have added `tmdb_id` and `show_tmdb_id` to the search payload in Elementum 0.1.51.

**Comment by shmizan** [comment]
@elgatito thank you very much!

**Comment by movianlost** [comment]
@shmizan Did you manage to reference {tmdb_id} in your provider? what code lines did you change?
