### ISSUE TITLE
Ygg - Missing results

### ISSUE THREAD

**Issue by POMPOM24** [elgatito/script.elementum.burst#181]
Hello no result with yggtorent have you an idea to resolve this problem thank you

**Comment by chicungunya** [comment]
> Hello no result with yggtorent have you an idea to resolve this problem thank you

Hi @POMPOM24 ,
I think it's because YGG use Cloudflare and it's not possible to by pass it, am I right @elgatito ?
There is no more support for elementum and burst so I think we need to forget Ygg unfortunately...

**Comment by chicungunya** [comment]
@elgatito maybe a solution ? https://github.com/KyranRana/cloudflare-bypass

**Comment by elgatito** [comment]
It's a php project. Not usable.

**Comment by HtheChemist** [comment]
This is in Python: https://github.com/venomous/cloudscraper

Seems pretty straigtforward to implement. I will try to do some test when I have a moment.
