### ISSUE TITLE
Cloudflare bypass ?

### ISSUE THREAD

**Issue by chicungunya** [elgatito/script.elementum.burst#182]
Hello,

I know there is no more support but maybe someone can help.
This is my log : http://paste.ubuntu.com/p/NggG5CsYYk/

YGG and IPTorrents doesn't work anymore and I think it's because of Cloudflare. I know there is a by pass with Proxy but maybe it's a new system of by pass using by IPTorrents and YGG?

Thanks a lot

**Comment by elgatito** [comment]
Duplicate of #181 

Cloudflare has changed it's protection.
