### ISSUE TITLE
iptorrents not working

### ISSUE THREAD

**Issue by albrhe** [elgatito/script.elementum.burst#183]
Private provider: iptorrents not working
No results appear in the search

**Comment by madnesofjuice** [comment]
I have the same problem

**Comment by elgatito** [comment]
@albrhe @madnesofjuice it's protected by CloudFlare. See other issue in Burst.

**Comment by rafae667** [comment]
Still no way to make iptorrents work?

**Comment by elgatito** [comment]
Closing, as this one is related to Cloudflare protection.
