### ISSUE TITLE
Could not solve the CloudFlare challenge

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#185]
Hi,

What is the meaning of this protection?
How can I know which provider raises thie error?
And how does it affect the search process? Does it mean that I don't get any result from this provider?

Kodi Log: https://paste.ubuntu.com/p/D2WhBsysWb

Thanks.

Elementum 0.1.51
Burst 0.0.48

**Comment by elgatito** [comment]
Cloudflare is used to protect websites from accessing by non-humans, like Burst.

They change logic from time to time to avoid robots passing them.

Elementum is using http://github.com/ElementumOrg/cfbypass to solve cloudflare defense, which does not work with latest logic, of course.

> How can I know which provider raises thie error?

Watch in the log.

> And how does it affect the search process? 

You cannot access the website.

> Does it mean that I don't get any result from this provider?

Yes.

**Comment by burekas7** [comment]
I understand that it relates to: https://itorrents.org:443/
But I didn't find which is the provider relating to this url.

All the others has their own search urls and they are working.
