### ISSUE TITLE
Torrentleech not working

### ISSUE THREAD

**Issue by Jezze83** [elgatito/script.elementum.burst#186]
Url https://classic.torrentleech.org/torrents/browse/index/ not working so thats why it wont give any result or its very slow. Can someone fix torrentleech?

**Comment by elgatito** [comment]
@Jezze83 You should read existing issues before creating a new one.
CloudFlare protection is not letting Burst.

**Comment by Jezze83** [comment]
Torrentleech not using cloudflare

**Comment by Jezze83** [comment]
Now it works with my raspberry but no computer 🤔

**Comment by elgatito** [comment]
> Torrentleech not using cloudflare

@Jezze83 If you don't see it - it does not mean it is not used.

https://classic.torrentleech.org/

```
Response headers:
cache-control: no-store, no-cache, must-revalidate
cf-cache-status: DYNAMIC
cf-ray: 58c05c6f980d2b6e-AMS
cf-request-id: 026c1819bb00002b6e7f368200000001

```

**Comment by Jezze83** [comment]
How its possible then that works my raspberry but not with pc?

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.

This issue is related to Cloudflare protection, there is a separate issue for that.
