### ISSUE TITLE
UnicodeError breaking certain search results

### ISSUE THREAD

**Issue by danryu** [elgatito/script.elementum.burst#187]
Try searching for "THX 1138" (I have almost all English-language trackers enabled, about 20) and you will likely get an error like this:

> ERROR: [script.elementum.burst] UnicodeEncodeError: 'ascii' codec can't encode characters in position 114-115: ordinal not in range(128)

Not sure why ascii is being used anywhere, but probably some international (ie non-ascii) characters are breaking the search.

Attaching a Kodi crashlog covering the search and the above error.

I haven't spent much time looking at code yet. I can probably make a fix for this but if you want to point me in the right direction to start with it will save some time.

[kodi_elementum_burst_crash.txt](https://github.com/elgatito/script.elementum.burst/files/4602952/kodi_elementum_burst_crash.txt)

**Comment by elgatito** [comment]
@danryu should be fixed in 0.0.49.
