### ISSUE TITLE
Stuck on "Resolving magnet link"

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#188]
When trying to play a torrent from idope it stuck on the "Resolving magnet link" notification message.

EDIT:
Probably the problem is some specific torrents and not a problem with the provider.
It's also happened with a torrent from Magnetdl

Kodi debug log:
(In the log it was tested with a torrent from idope)
https://paste.ubuntu.com/p/mYHMwK5XXZ

Kodi 17.6
Elementum 0.1.51
Burst 0.0.48
Window 10

**Comment by elgatito** [comment]
@burekas7 magnet is resolved by DHT and if nobody can show information - you cannot start downloading.

**Comment by burekas7** [comment]
So this is a problem that relates to a specific torrent and not relates to the provider?

**Comment by elgatito** [comment]
@burekas7 if provider gives non-real magnet hash - it will never resolve. There are different possible issues.

**Comment by burekas7** [comment]
Understood.
So you can add a timeout for this? (or there is already timeout for this?)
Because the notification of "Resolving magnet link" is stuck and stay like this forever until I go back and exit, then return back to the addon so the addon crashes itself somehow and it releases.

**Comment by brentonv** [comment]
#171

**Comment by brentonv** [comment]
Yes it would be great if this issue could be resolved. Thank you

**Comment by elgatito** [comment]
Resolve timeout in Elementum might be more usable.

**Comment by elgatito** [comment]
Resolve timeout is added to the latest Elementum.

**Comment by brentonv** [comment]
@elgatito thanks very much
