### ISSUE TITLE
Is there a way to improve torrent search?

### ISSUE THREAD

**Issue by peter099** [elgatito/script.elementum.burst#190]
Is there a way to improve torrent search, maybe by manually editing script files? I am mostly interested improving the search for piratebay because most of the tv shows and movies are there, but i get results from piratebay less of the 50% of the time. For example, for the first season of 'law and order svu' elementum burst doesn't find any results on piratebay, and if i look in the log this is the search url which is implemented:
 `https://thepiratebay1.com:443/search/law%20order%20special%20victims%20unit%20s01/0/99/200`, and the search string 'law order special victims unit s01' do not find any results. But if i go to piratebay website and search for `law order svu s01` it finds results. 
So, is there a way to make elementum burst to implement this search `'law order svu s01'` instead of `'law order special victims unit s01'`?

**Comment by consal** [comment]
I'm wondering about the same - is it possible to define a search with first n words from title. Did you find a solution?

**Comment by zalexzperez** [comment]
I'm interested in this as well.

There should be an automatic search override when you can't find the proper torrent and let the user use a custom search phrase. And/Or let them add the torrent link in case they found it.-

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.

If you install `context.elementum` addon, it now supports using custom query for searching in burst, and Burst will use it, without any modifications.
