### ISSUE TITLE
RARBG and YTS always timeout

### ISSUE THREAD

**Issue by logon84** [elgatito/script.elementum.burst#192]
Hi. I'm using elementum burst on my android tv but when searching for torrents with Elementum, RARBG and YTS both always reach timeout. The strange thing is that, with Quasar, both providers work nicely, and I get search results from them. I suspect this is not a common issue for the rest of the people, because I haven't been able to find similar issues on inet, but anyway, I share my log here if it helps. Thank you

https://gist.github.com/logon84/984295f09e97d261a3749e3ef722d2be

**Comment by logon84** [comment]
Ok, I found the problem. I had to disable 'replace quotes' setting in elementum burst in order to receive search results from RARBG and YTS. Idk why line 415 in filtering.py (text = text.replace(u"'", '')) is causing both providers to fail if the serting is active. Thank you anyway

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.
