### ISSUE TITLE
[Request] Compatible with Kodi 19 Matrix / Python 3

### ISSUE THREAD

**Issue by Lontron** [elgatito/script.elementum.burst#197]
Стабильная версия Kodi 19 Matrix скоро выйдет, должно быть обновление для elementum burst, спасибо.
Для совместимости с Kodi 19.

**Comment by 1F33LR41N** [comment]
Development stopped, so i think brust will not work with Kodi 19, at least to the moment when any other developer fork this project and make his own version of the plugin.
In this case i think it would not be soon.

**Comment by Lontron** [comment]
> Development stopped, so i think brust will not work with Kodi 19, at least to the moment when any other developer fork this project and make his own version of the plugin.
> In this case i think it would not be soon.

Обновления все еще идут, и если мы поддержим разработчика пожертвованиями, elementum burst будет совместим с kodi 19, elementum совместим с Kodi 19.

**Comment by elgatito** [comment]
@Lontron Проблема не в самом дополнении, а в зависимостях, которые оно использует. Зависимости нужно править для работы на Python2/Python3. А я не являюсь Python разработчиком + у меня сейчас на это нету времени.
Если кто-то сделает толково - я включу изменения и выпущу новую версию.

**Comment by Lontron** [comment]
@Limeone Можете ли вы сделать elementum Burst совместимым с Kodi 19? Спасибо за любые ответы.

**Comment by Limeone** [comment]
@Lontron Автор скрипта прекратил его поддержку. я не знаю что это за скрипт, не пользуюсь им и не вижу причин участвовать в его поддержке

**Comment by Lontron** [comment]
@lopezvg I know you made elementum compatible with kodi 19, would you do that for elementum burst as well?  Thank you.

**Comment by Lontron** [comment]
@ghost

**Comment by Lontron** [comment]
@Limeone Обновления для исправлений все еще идут, он просто попросил помощи и обновить аддон до python 3 и продолжит его дальше.

**Comment by elgatito** [comment]
@Lontron Я не говорил что буду продолжать развитие этого дополнения. Я только выпущу исправления, если кто-то толково это сделает.
Дополнение должно работать и с Python2 и с Python3, а не только с последним.

**Comment by Lontron** [comment]
@elgatito Исправлений ошибок не будет?  Например если провайдер не работает

**Comment by Lontron** [comment]
@steeve Hi, we need help here, this addon must be compatible with python 2/3 for Kodi. It must be compatible with both sides of the python. Thanks.

**Comment by Nemiroff** [comment]
> @ghost @vlmaksime @tdw1980 @I-Cat @Nemiroff
> @blackcofee

https://github.com/Nemiroff/script.elementum.burst/tree/matrix

**Comment by Lontron** [comment]
@Nemiroff Спасибо.
@elgatito Я вижу это только для python 3, но я думаю вы можете комбинировать его с python 2.

**Comment by tahirjalilov** [comment]
Какой смысл делать совместимость с python 2, если его развитие прекращено?

**Comment by 1F33LR41N** [comment]
> Какой смысл делать совместимость с python 2, если его развитие прекращено?

Для поддержки в старых версиях Kodi.
Думаю, всегда найдутся люди, которые будут использовать устаревшие версии. Как по мне, самый верный вариант - что бы кто-нибудь, чьи знания python этого позволяют, забрал разработку плагина под свое крыло, возможно под другим названием, и желательно вместе с elementum.
Старые версии (нынешние) будут работать на старых версиях Kodi, а новые на свежих версиях Kodi. Тогда и путаницы не будет, и проекты обретут новый дом.

**Comment by Lontron** [comment]
@i96751414 would you do that for elementum burst as compatible with Kodi 19 Matrix/Python 3 well? Thank you.

**Comment by elgatito** [comment]
Burst updated with PR from @vlmaksime.
Many thanks to @vlmaksime .

**Comment by FKOV** [comment]
Thanks @vlmaksime but one question (sorry if it's stupid question but as far as I noticed @vlmaksime made burst compatible with python 3 , but since I am a new user here will the burst auto uptade when I uptade to kodi 19 or I need to download it from a github repository through my broswer ? And if the second one where can I find it 

--I totally forgot @elgatito thank you for the creation of the best kodi addon ever made , keep up the good work

**Comment by elgatito** [comment]
@FKOV latest Burst version run same way on Kodi19 and earlier Kodi versions.

**Comment by FKOV** [comment]
@elgatito thanks for the clarification,  have a nice day and keep up the good work, you can close the issue now
