### ISSUE TITLE
Fixing TPB thepiratebay provider scraper API

### ISSUE THREAD

**Issue by dairefagan** [elgatito/script.elementum.burst#198]
As TPB now requires JavaScript I have been attempting to change it to using the apibay visisble in this side-by-side comparison: [this side-by-side comparison](https://editor.mergely.com/yhmS0ypk/). For the api-torrent line, as the api only gives an ID which much be put into a URL from the main site to load the main page of each torrent, rather than the URL itself, I have also tried both of the following:

```
"torrent": "'https://thepiratebay.org/description.php?id=s%' & id"
"torrent": "'https://thepiratebay.org/description.php?id=' + {id}"
"torrent": "'https://thepiratebay.org/description.php?id=' + {id}"
```
But the logs throws errors, visible [here](https://paste.kodi.tv/ahowewitez.kodi), the last of which is:

KeyError: u"'https://thepiratebay.org/description.php?id=' + id"

Someone far more familiar with python than I has explained this is because line [469/470 of burst.py](https://github.com/elgatito/script.elementum.burst/blob/master/burst/burst.py#L=461) read:

```
if 'download_path' in definition:
    torrent = definition['base_url'] + definition['download_path'] + torrent
```
but that even when that is changed there would be a problem with lines 589/592, as they look like the format is api + html parser?

Is it possible to scrape from the apibay(or TPB another way) using the current code of Elementum, and if so please tell me how exactly I should edit the scraper. If not, could you please tell me the changes to the code that will allow this to work.

If it will work, will I then be able to select the row and tag for the magnet link using the standard non-api "row" and "torrent" lines as normal?

**Comment by georgew21** [comment]
any progress for this?

**Comment by elgatito** [comment]
@georgew21 what progress you expect?

**Comment by georgew21** [comment]
if he achieved to find the way to solve the problem.  i attach the url of an other addon (for stremio) that scaps the piratebay awesome, if it could help to take some ideas to solve the above problems.

https://github.com/TheBeastLT/torrentio-scraper/tree/master/scraper/scrapers/thepiratebay

p.s. unfrotunately, i don't know programming

**Comment by elgatito** [comment]
Existing piratebay providers works fine, why you need API implementation?

**Comment by counttiefre** [comment]
PirateBay never shows up in results for me (used to work with a mirror in domain alias, but can’t get any to work now).

**Comment by elgatito** [comment]
@counttiefre tpb works fine for me. Send your log file and remove alias for tpb.

**Comment by counttiefre** [comment]
@elgatito Now it’s working for me again, thanks, sorry.
