### ISSUE TITLE
[Request] Updating for these providers: Kickass, ThePirateBay

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#201]
Hi,

Please update these providers: Kickass, ThePirateBay

---

**For Kickass:**
Current url: https://katcr.co  (Not working)
Current search url pattern: .../katsearch/page/1/<title>

New url: https://katcr.to       (Working)
New search url pattern: .../usearch/<title>/

---

**For ThePirateBay**
Current url: https://thepiratebay1.com  (Not working)
New url: https://thepiratebay10.org/        (Working)
* Search url pattern remain the same here.

---

Current Burst version: 0.0.49

Thanks.

**Comment by burekas7** [comment]
Hi @elgatito ,
Just as a reminder.

I know this is not your main thing, but it has been a long time since Burst received an update.
Can you check this and implement this request?

Thanks.

**Comment by elgatito** [comment]
@burekas7 i have updated TPB and Kickass, but kickass now requires login to download torrent file. 
So it probably need to be private with login/password.

**Comment by burekas7** [comment]
@elgatito 
Thanks, I will test it :)

Regarding Kickass, I aware to this requirement of registration only by now, and to be honest nothing there seems to be safe so I prefer not to try that. If there will be any change in the future I will update.
* BTW, there are another mirrors that asks for pressing on a lot of links in order to get the file but they also looks as a scam or something like that.
