### ISSUE TITLE
How to tell if a provider is timing out?

### ISSUE THREAD

**Issue by john3voltas** [elgatito/script.elementum.burst#203]
Hi there,

I've got provider 1337 enabled but for some reason it's been a while that I don't get any results from it.
Is there an easy way to tell if a provider is timing out?
I am assuming it is timing out because their website is up, I can manually copy paste their magnets into elementum and they work, and no one here has been mentioned that it is not working for them... So I am guessing it's not broken and that it is a matter of timing out.
I'll try to raise the timeout and see if that helps but it would be cool if there was an easy way to detect when a provider is either broken or simply timing out.
I'll provide more feedback later today or tomorrow.
Thanks in advance.

Cheers

**Comment by john3voltas** [comment]
Okay, I've just tried on a different computer and 1337x is working fine.
So, either I have a bad setting in elementum/burst or else my Pi is not fast enough and is timing out.
So, my question still stands: how can I tell if a given tracker is timing out?

**Comment by john3voltas** [comment]
Hi.
Here's a kodi log from the Pi.
http://ix.io/2B53
Apparently from the log file, the provider is working but I don't see any torrent findings from this provider when Elementum runs a search on all providers for a given tv show episode.
All I get are RARBG and EZTV torrents when I search for the tv show 'impulse' without the quotes.
Why wouldn't it show me results for 1337x when it found torrents on that provider??

On the other end, on the PC (x86) I get 1337x torrent findings although the provider only finds a 480p result when in fact there are other torrents available for that episode of that show on that provider. The only catch is that Elementum seems to be looking for the s02e01 string when there are torrents called s02.complete...
Any way to work around that?
Thanks in advance.

Cheers

**Comment by antonsoroko** [comment]
@john3voltas 
is this still and issue?

for a while all popular providers has fallback search queries - e.g. search for s02 if s02e01 is not found.
example:
https://github.com/elgatito/script.elementum.burst/blob/be5bb3dd094c46c96b725ab387b98b06badaa67f/burst/providers/providers.json#L92-L96

**Comment by john3voltas** [comment]
Hi @antonsoroko .
Sorry for taking so long to answer. Been away from github for a while.
No, this is not an issue at the present moment. I think either thr provider is now faster, burst received an update that fixed it, or there was some issue with LibreELEC back in May.
Closing it.
