### ISSUE TITLE
[Support] How do I use the "domain alias" option under each provider?

### ISSUE THREAD

**Issue by pitsi** [elgatito/script.elementum.burst#204]
A friend of mine does not get any results from a well known public tracker, and at the same time I do, so I assume it is not an api issue or a burst one.  However, he can access the tracker's page via a web browser and do any search there as usual.

Then I thought of the "domain alias" option under burst's setting (public trackers > name of the provider > enable > domain alias (optional). Can I enter the url of a mirror in there and let burst use that mirror? And if so, how shall I set it? E.g. is `example.com` enough, or do I have to set the full url like `https://www.example.com/` ?

Thank you in advance.

**Comment by elgatito** [comment]
@pitsi example.com is enough. I don't remember if "https://" is taken in mind there. You can try it.

**Comment by pitsi** [comment]
Well, I tried 2 mirrors of that page, both with and without the https part, on my setup and I got no results. I can't mention them here, I know :(

**Comment by antonsoroko** [comment]
https://github.com/elgatito/script.elementum.burst/commit/59ae400a6e42486a2a4c869d6c734a87404cd382#diff-f6abd4c3e77d4532c7ed82ea2d2258510150e4e7e8d0ba994cf26ee066c32d46R57

so if it does not have any scheme - then it will be `http://` by default. so basically you can put name without scheme, but better to specify it, i think.

**Comment by naveen1hot** [comment]
No need for http!!
Just put without http like 
1337x.to
It's working for me

**Comment by pitsi** [comment]
Can you please try an 1337x mirror there and not the original page?

**Comment by elgatito** [comment]
Closing as this is not an issue.

**Comment by pitsi** [comment]
Now that the issue was closed and came up on my notifications... 2.5+ years later, I gave it a try.
All it needs to work is the domain be valid, regardless of http/http or anything else. 
E.g. assuming that `github.com` is the domain in question, it will work with all those 3
```
github.com
http://github.com
https://github.com
```
but not with something irrelevant, like `github.gr`.
