### ISSUE TITLE
[Request] Обновление кода для Kodi 19

### ISSUE THREAD

**Issue by Lontron** [elgatito/script.elementum.burst#207]
https://forum.kodi.tv/showthread.php?tid=344263&pid=2975581#pid2975581
01 September 2020 - xbmc.translatePath() was moved to the xbmcvfs module (xbmcvfs.translatePath()) 

Log: http://paste.kodi.tv/nirovomenu `2020-11-12 13:08:34.183 T:9824  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.`

**Comment by Lontron** [comment]
@vlmaksime надо сделать тоже самое здесь, если возможно, спасибо.

**Comment by vlmaksime** [comment]
Уже сделано в #210

**Comment by elgatito** [comment]
@vlmaksime Спасибо, добавил.
