### ISSUE TITLE
[Request] Add ExtraTorrent website

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#209]
Hi.
Please if possible add "ExtraTorrent" https://extratorrents.it/home

Thank you.

**Comment by burekas7** [comment]
+1

**Comment by elgatito** [comment]
@iz8mbw sort by seeders count does not work there, it will give you a lot of wrong results.

**Comment by iz8mbw** [comment]
Ok, so ignore this my request.
Thanks!

**Comment by elgatito** [comment]
@burekas7 https://ext.torrentbay.to/search/?q=Vikings+S03E01&__cf_chl_jschl_tk__=b7d7acee4bac775cf89e3596fa8cfb057e7fa206-1612383906-0-AdAWXE-vJk0uy8stUOY5CwDY2HRnakHm0SGRkGEyCRTU8eD6eqoSMenfAfQuJ14dHqlANazwhDEKUUyKWYYDFdvdgtWCVllnBy4kh5ecTg_XoThraxEfAQxCVy6fbaMBKvVb4BkInIjwq6D-Gw-48zhyhBaDaYuAz3KkSB9bzR5B_mG8q4-HFrj6XTbqNXJtjbzAk32DSV7a649mvOyBH39tu1CLPDvETxbcO7Q2V3ZZ4oFlsRXGwjMrHPDHAciv7f2GC6DYjJIgC186K9Lkw0jR4KLrhjI1ytGwId9VBSoycXE04MXvVHOU9BiIOLKHGXg9lYHc_xT28pYkhCmGDhJ6D2espfUvyyirfWGJQIVKUFbRdyPvGcdAslniUybMkA - behind cloudflare.
