### ISSUE TITLE
Additional sites to remove

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/script.elementum.burst#21]
elitetorrent > http://www.eliteros.com
extratorrent > https://www.extratorrents-cc.com

t411 > https://yggtorrent.info

Just raising for tracking purposes

edit: in fact, should get rid of t411.
edit 2: all of them need to be removed.

**Comment by Gregsr** [comment]
yggtorrent.info is a fake
True site is yggtorrent.com

**Comment by hoshsadiq** [comment]
Hmm, I got it from here: https://www.torrent411.li/
But I don't know. I think yggtorrent.com already exists on the list.

**Comment by Gregsr** [comment]
Be careful because torrent411.li is a fake too.

YGG admins communicate with Twitter 
Take a look at YggTorrent (@yggtorrent_com): https://twitter.com/yggtorrent_com?s=09

**Comment by hoshsadiq** [comment]
Sure! Well in that case I think we can actually get rid of t411 because there's no other site besides that.

**Comment by elgatito** [comment]
So what is the final here? 

Which changes do we need? 
I have tried few trackers from Public section but they seemed all offline. 

All of the remaining hosts are alive?

I'd also make a remark, which language are each of them, so it's clear what to enable for people.

**Comment by hoshsadiq** [comment]
It seems we need to get rid of all three of them:
https://torrents.me/site/t411/
https://torrents.me/site/extratorrent/
https://torrents.me/site/elitetorrent/

**Comment by hoshsadiq** [comment]
By the way, I stumbled upon https://github.com/Jackett/Jackett while investigating these sites. They seem to have an up to date list of torrent sites. It might be worth looking into using Jackett as an alternative to burst (or maybe wrap around it or something)

**Comment by elgatito** [comment]
> By the way, I stumbled upon https://github.com/Jackett/Jackett while investigating these sites. They seem to have an up to date list of torrent sites. It might be worth looking into using Jackett as an alternative to burst (or maybe wrap around it or something)

It's a standalone application with a lot of requirements, and I doubt it will work fine on libreelec or other specific OS. Easier to write a proxy addon which receives request from elementum, pass it to jackett and return back to elementum. It's up to someone who wants to do that.

**Comment by elgatito** [comment]
@Gregsr you want to add something, which trackers are dead - from the current list?

**Comment by Gregsr** [comment]
Nextorrent and T411 are dead

Last adress for Cpasbien : https://www.cpabien.bz/

Thanks

**Comment by elgatito** [comment]
I have checked all public providers in Burst (the ones I can really test).
Removed few ones (some are not active, some are fraud). Fixed queries for few of them. And changed default providers.

**Comment by elgatito** [comment]
It will come in the next release, but I have uploaded to github so you can make some changes.

**Comment by hoshsadiq** [comment]
Awesome.

> It's a standalone application with a lot of requirements, and I doubt it will work fine on libreelec or other specific OS. Easier to write a proxy addon which receives request from elementum, pass it to jackett and return back to elementum. It's up to someone who wants to do that.

True. Honestly I was thinking maybe host it myself as an API (similar to alluc.ee) and _maybe_ port it to Go as a challenge (I'm not a huge .net fan). And after that potentially have a separate provider that would wrap around that.

**Comment by elgatito** [comment]
Are we fine with the latest version? Should we close this?

**Comment by hoshsadiq** [comment]
Yes, we can close this I think.
