### ISSUE TITLE
TorrentGalaxy has no icon

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/script.elementum.burst#221]
Hey,
The new provider "TorrentGalaxy" is awesome but has no icon on results page.
it tried adding an icon myself but that doesn't seem to work.
can this please be fixed?

Thanks :)

**Comment by elgatito** [comment]
@ShlomiD83 to make that you need to find proper logo, resize it to correct aspects. 
There are many providers without images, because it takes time.

**Comment by ShlomiD83** [comment]
![torrentgalaxy](https://user-images.githubusercontent.com/17053215/101990106-73846f80-3cad-11eb-8703-0cc4c555f762.png)
how about this one?

**Comment by burekas7** [comment]
What should be the correct size?
![tgxlogo](https://user-images.githubusercontent.com/13424257/102026900-5d5bd980-3da9-11eb-9b44-223e37e6c9ed.png)

**Comment by elgatito** [comment]
@burekas7 Yes, that is much better. 

Preffered image is a png, with transparent background.

It would be great if someone could try to prepare icons for active providers. 
There are log of them without logos.

**Comment by ShlomiD83** [comment]
> What should be the correct size?
> 
> ![tgxlogo](https://user-images.githubusercontent.com/13424257/102026900-5d5bd980-3da9-11eb-9b44-223e37e6c9ed.png)

256*256 pixels I think.

**Comment by ShlomiD83** [comment]
> What should be the correct size?
> 
> ![tgxlogo](https://user-images.githubusercontent.com/13424257/102026900-5d5bd980-3da9-11eb-9b44-223e37e6c9ed.png)

I believe it should be 256*256 pixels.

**Comment by elgatito** [comment]
@ShlomiD83 I don't recall now, they are still resized. But probably shoud be resized to 256x256 aspect.
You can try to place icon in the icons folder, and it will show up after Kodi restart.

**Comment by ShlomiD83** [comment]
> @ShlomiD83 I don't recall now, they are still resized. But probably shoud be resized to 256x256 aspect.
> You can try to place icon in the icons folder, and it will show up after Kodi restart.

I did just that, but don't remember if I restarted Kodi..
I'll try that when I'll get home from work.

**Comment by burekas7** [comment]
> @burekas7 Yes, that is much better.
> 
> Preffered image is a png, with transparent background.
> 
> It would be great if someone could try to prepare icons for active providers.
> There are log of them without logos.

Do you have any list of "active" providers that doesn't have a logo?
Because I don't use everyone there. 
From 10-13 providers that I checked during the time there are logos.

**Comment by elgatito** [comment]
@burekas7 @ShlomiD83 It is easy to see.

- Look in `providers.json`: https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json 
- If `"enabled": true` - then if should have an icon.
- Icon is named as `provider` + `.png`. Icons placed here: https://github.com/elgatito/script.elementum.burst/tree/master/burst/providers/icons

Example:
```
"0day": {
        ......
        "enabled": true,
        .....
    },
```

Icon name should be `0day.png`.

**Comment by burekas7** [comment]
@elgatito 

Ok, those are the active providers ("enabled": true) that don't have logos:
bitnova
filetracker
ilcorsaroblu
ilcorsarored
iptorrents
itorrent
mvgroup
nitro
skytorrents
**torrenthalaxy**
torrentz2k
worldwidetorrents

I will search their logos and open a new issue when I have them.

* Be aware that you have typo issue with Torrent Galaxy, you type it "torrent**h**alaxy" instead of "torrent**g**alaxy"

**Comment by burekas7** [comment]
By the way, I check the list above, these providers urls doesn't work:
ilcorsarored
worldwidetorrents

So you can remove them or set them as "enable: false".

**Comment by elgatito** [comment]
@burekas7 
> You type it "torrenthalaxy" instead of "torrentgalaxy"

Good catch, it will be changed.

**Comment by elgatito** [comment]
@burekas7 
>>>
 By the way, I check the list above, these providers urls doesn't work:
ilcorsarored
worldwidetorrents

So you can remove them or set them as "enable: false".

Yes, the proper way is to make `enable:false`, then regenerate Kodi settings to remove them from settings.

**Comment by elgatito** [comment]
I thought there are much more missed icons for providers.

**Comment by elgatito** [comment]
@ShlomiD83 Should be fine with 0.0.53.

**Comment by burekas7** [comment]
@elgatito 
I see when the logo is not set as 256x256 it distort the logo.
So I probably will fix them inside 256x256 box and reupload it.

**Comment by burekas7** [comment]
@ShlomiD83 
You can use this updated logo file:
![torrentgalaxy](https://user-images.githubusercontent.com/13424257/102230173-36aab980-3ef5-11eb-80c9-a8ce5f0dc9d3.png)

**Comment by ShlomiD83** [comment]
> @ShlomiD83
> You can use this updated logo file:
> ![torrentgalaxy](https://user-images.githubusercontent.com/13424257/102230173-36aab980-3ef5-11eb-80c9-a8ce5f0dc9d3.png)

thanks, I'll try it.

**Comment by burekas7** [comment]
@elgatito 
I updated the logos after you release 0.0.53 to be 256x256.
You can find the updated zip file here:
https://github.com/elgatito/script.elementum.burst/issues/222#issuecomment-745366622

**Comment by elgatito** [comment]
@burekas7 @ShlomiD83 Icons got updates with 0.0.54. Thanks to @burekas7 .

**Comment by ShlomiD83** [comment]
Thanks to both of you.
one last request..can you add TorrentGalaxy's colors to it's name?
like this: "name": "[COLOR teal]Torrent[/COLOR][COLOR yellow]Galaxy[/COLOR]"
I've added it manually in providers.json file but it gets overwritten after every update.
thank you.

**Comment by elgatito** [comment]
@burekas7 @ShlomiD83 @iz8mbw  Would be great, if someone could browse different providers and try to pick colors for them.

**Comment by iz8mbw** [comment]
Yes, tested and works!

**Comment by ShlomiD83** [comment]
> @burekas7 @ShlomiD83 @iz8mbw Would be great, if someone could browse different providers and try to pick colors for them.

I've submitted a pull request changing TorrentGalaxy's color.
