### ISSUE TITLE
[Request] Add missing providers logos

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#222]
According to version version 0.0.52 and this issue:
https://github.com/elgatito/script.elementum.burst/issues/221

These are the providers that doesn't have a logo:
Some of them are logos that I edited by myself.
One of them doesn't have a logo at all.
Two of them doesn't work.
torrentgalaxy (remember to fix the typo "torrenthalaxy"" in "providers.json".

bitnova - V
filetracker - V
ilcorsaroblu - V
ilcorsarored - Site is not working
iptorrents - V
itorrent - Doesn't have a logo
mvgroup - V
nitro - V
skytorrents - V
torrentgalaxy - V
torrentz2k - V
worldwidetorrents - Site is not working

zip file with the missing logos:
https://f2h.io/oxykx9o35517

**Comment by elgatito** [comment]
@burekas7 updated icons with 0.0.53. Thanks

**Comment by burekas7** [comment]
@elgatito 
I fixed the icon dimensions to 256x256 because the logos are distorted in the results window.

This is the new zip file for them:
https://f2h.io/03kjik80jm7p

But I don't think you have to make a new release for now,
It will be updated in the next release.
