### ISSUE TITLE
[Bug] Wrong episode results from TorrentGalaxy

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#224]
When I looking for a example: Fargo S04E02
I do get results of Fargo S04 but of different episodes numbers 
(In this case even the specific episode is not there, even when I scrolled down)

Kodi debug log:
Part1: https://paste.ubuntu.com/p/fyHvXGS5NW
Part2: https://paste.ubuntu.com/p/Bj8FxSGxGr

Image:
* In the image you see GalaxyTorrents results, but I'm also using addtional providers.
![image](https://user-images.githubusercontent.com/13424257/102422920-79ad7f80-4010-11eb-8015-1ae6dfa88ba1.png)

Elementum Burst 0.0.53
Elementum 0.1.64
Kodi 17.6

**Comment by iz8mbw** [comment]
@burekas7 I'm using the latest version and I don't have this issue:
![image](https://user-images.githubusercontent.com/3474082/103455732-b3100b80-4cef-11eb-8591-fd77db61cc38.png)

I think you can close this issue.

**Comment by burekas7** [comment]
@iz8mbw 

1. Don't sugggest to close an issue before the author has confirmed or denis decided so.
If you don't have the bug this is not saying that there isn't a problem.
We probably have a different enviroments or settings or something else..
2. I'm also using the latest version 0.0.53, so there is something that need to be check, especially that there is a differece between us, and because it still happens to me with Fargo regarding GalaxyTorrents.

**Comment by iz8mbw** [comment]
I only suggested to close the issue if you currently do not have more that issue.

**Comment by iz8mbw** [comment]
Anyway try to apply this fix to your provider.json file https://github.com/elgatito/script.elementum.burst/pull/235/commits/4958f0672135710935da6589b3135de41e36d1fc

**Comment by burekas7** [comment]
> Anyway try to apply this fix to your provider.json file [4958f06](https://github.com/elgatito/script.elementum.burst/commit/4958f0672135710935da6589b3135de41e36d1fc)

Thanks,
I will check the fix soon.

**Comment by burekas7** [comment]
@iz8mbw 

By the way if you are using Galaxy Torrents, you can update the logo from here, so it will look like I have:
https://github.com/elgatito/script.elementum.burst/issues/222

**Comment by burekas7** [comment]
> Anyway try to apply this fix to your provider.json file [4958f06](https://github.com/elgatito/script.elementum.burst/commit/4958f0672135710935da6589b3135de41e36d1fc)

Still the same with this fix, I'm getting result of all the other episodes in the season except the episode number I'm looking for.

**Comment by elgatito** [comment]
@burekas7 Please, try 0.0.54. I have moved season queries to fallback ones, so they fire only if exact episode is not found.

**Comment by burekas7** [comment]
@elgatito 

Hi,
With 0.0.55 I don't see any result from GalaxyTorrents in the results window.
But in the log there are results from it:
"[torrentgalaxy] >>       TorrentGalaxy returned  7 results in 29.9 seconds"

Kodi Log: https://paste.ubuntu.com/p/89nRrTsky4

**Comment by ShlomiD83** [comment]
> @elgatito
> 
> Hi,
> With 0.0.55 I don't see any result from GalaxyTorrents in the results window.
> But in the log there are results from it:
> "[torrentgalaxy] >> TorrentGalaxy returned 7 results in 29.9 seconds"
> 
> Kodi Log: https://paste.ubuntu.com/p/89nRrTsky4

that's very weird, TorrentGalaxy always returned results (the correct ones).
maybe you have filters? what's your Kodi language? maybe that has something to do with it.

**Comment by burekas7** [comment]
I have the same filters for years and I don't have this problem with any of the other providers.
The only option I can think of is that there is a same torrent from another provider so Burst prefer it instead the TorrentGalaxy one.

I will try to set it as a single provider and test it.
But maybe @elgatito  has some insights regarding the current situation in the log I provided.

**Comment by ShlomiD83** [comment]
> @burekas7
> 
> > The only option I can think of is that there is a same torrent from another provider so Burst prefer it instead the TorrentGalaxy one.
> 
> When torrent with same hash found on multiple providers, it is shown as combined. It is never just skipped.

It doesn't show as combined for a long time.
It shows as it came from one of the providers, i remember Quasar had a combined icon.
Maybe you can fix it a bring back the combined icon?

**Comment by burekas7** [comment]
@elgatito , so can you figure out from the log what could be the reason I don't see any TorrentGalaxy result in the results window?
(It happens since version 0.054/0.055)

@ShlomiD83 , yes, there was a kind of cloud icon.

**Comment by ShlomiD83** [comment]
> @elgatito , so can you figure out from the log what could be the reason I don't see any TorrentGalaxy result in the results window?
> (It happens since version 0.054/0.055)
> 
> @ShlomiD83 , yes, there was a kind of cloud icon.

Exactly, the cloud icon.
Bring it back :)

**Comment by elgatito** [comment]
@ShlomiD83 
> Exactly, the cloud icon.

It works as expected, I always see the cloud icon.
Torrents are combined if they have same hash code, not the same name or something else.

**Comment by ShlomiD83** [comment]
> @ShlomiD83
> 
> > Exactly, the cloud icon.
> 
> It works as expected, I always see the cloud icon.
> Torrents are combined if they have same hash code, not the same name or something else.

Haven't seen the cloud icon for ages.

**Comment by elgatito** [comment]
> Haven't seen the cloud icon for ages.

Private trackers always use unique torrents.

**Comment by ShlomiD83** [comment]
> > Haven't seen the cloud icon for ages.
> 
> Private trackers always use unique torrents.

I'm not using private trackers.
1337x, rarbg, torrentgalaxy, rutor & magnetdl.

**Comment by burekas7** [comment]
@elgatito 

I found something intresting:
I set for example 13 providers (As in the log above), in this case GalaxyTorrents isn't shown up.
But when I'm removing some of them, the results from GalaxyTorrents begins to show up.
There is no meaning which of them I remove.
There is something unstable with the results.

I guess it's something with the filters, or combination of some providers together, I still don't know why or what.

**Comment by ShlomiD83** [comment]
> @elgatito
> 
> I found something intresting:
> I set for example 13 providers (As in the log above), in this case GalaxyTorrents isn't shown up.
> But when I'm removing some of them, the results from GalaxyTorrents begins to show up.
> There is no meaning which of them I remove. And I can't point on one providers that makes a conflict or something.
> 
> Sometimes I removed provider X the results from GalaxyTorrents do show up,
> Add provider X back, results from GalaxyTorrents don't show up.
> Remove provider X again, you expect that results from GalaxyTorrents will show up but they don't.
> There is something unstable with the results.
> 
> I guess it's something with the filters, or combination/conflict of some providers together, I still don't know why or what.
> 
> * By the way, it happens also with Kickass sometimes, or Zooqle.

How many enabled providers do you use?

**Comment by burekas7** [comment]
@ShlomiD83 
It doesn't matter.
Even when I tried with 4-6 providers the resultד still were not constant.
And as I describe, assuming with 6 providers I saw results from TorrentGalaxy, when I add another one (no matter which) suddenly I didn't see any result from it, so I removed the 7th provider and back to 6, and TorrentGalaxy isn't there.

**Comment by ShlomiD83** [comment]
sounds like it sees torrents with identical hashes but you have no indication.
it shows results as if it came from only 1 provider and not multi (the cloud icon),

**Comment by elgatito** [comment]
@burekas7 Check with 0.0.56. I have added more information to log files, so that you can see why items are filtered from results, returned to Elementum.

Most likely they don't have seeds.

**Comment by burekas7** [comment]
@elgatito 

Kodi debug log with Burst 0.0.56:
https://paste.ubuntu.com/p/bj9xf2n8zk

In their site there are seeds so take a look, thanks.

![image](https://user-images.githubusercontent.com/13424257/104820522-da152400-583d-11eb-842a-2cf10d9fcdda.png)

**Comment by elgatito** [comment]
```
20:52:59.432 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 2220, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 63, 'name': u'Fargo.S04E04.The.Pretend.War.1080p.AMZN.WEBRip.DDP5.1.x264-TOMMY[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:5fff7410dc4dfa7dde2775388c315f59bdedd6f1&dn=Fargo.S04E04.The.Pretend.War.1080p.AMZN.WEBRip.DDP5.1.x264-TOMMY[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 184, 'sort_resolution': 4, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'3.71 GB'}
20:52:59.432 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 1881, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 43, 'name': u'Fargo.S04E04.The.Pretend.War.720p.HDTV.x264-CRiMSON[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:dde2f007af99ae0d46ebd3b1955c144c47629772&dn=Fargo.S04E04.The.Pretend.War.720p.HDTV.x264-CRiMSON[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 208, 'sort_resolution': 3, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'1.57 GB'}
20:52:59.433 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 360, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 3, 'name': u'Fargo.S04E04.1080p.WEB.H264-CAKES[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:0c80ce44e9e3ab44e925e7a6390fd2dca21d26c5&dn=Fargo.S04E04.1080p.WEB.H264-CAKES[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 29, 'sort_resolution': 4, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'1.30 GB'}
20:52:59.434 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 351, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 4, 'name': u'Fargo.S04E04.720p.HDTV.x265-MiNX[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:4e2bc09d2468ad107a3d89ef07ec9af45a783e14&dn=Fargo.S04E04.720p.HDTV.x265-MiNX[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 38, 'sort_resolution': 3, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'196.76 MB'}
20:52:59.435 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 99, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 5, 'name': u'Fargo.S04E04.The.Pretend.War.REPACK.720p.AMZN.WEBRip.DDP5.1.x264-TOMMY[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:7e0b64b326a0be15f004287ffb77ccc16c0caeb0&dn=Fargo.S04E04.The.Pretend.War.REPACK.720p.AMZN.WEBRip.DDP5.1.x264-TOMMY[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 10, 'sort_resolution': 3, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'1.33 GB'}
20:52:59.435 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 99, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 2, 'name': u'Fargo.S04E04.720p.WEB.H264-CAKES[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:8b0ed6282c9c229bc5394b160f8a52e32bddcf9e&dn=Fargo.S04E04.720p.WEB.H264-CAKES[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 10, 'sort_resolution': 3, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'560.57 MB'}
20:52:59.436 T:28792   DEBUG: [script.elementum.burst] [TorrentGalaxy] Skipping due to repeating hash: {'info_hash': u'', 'sort_balance': 45, 'icon': u'C:\\Users\\aUser\\AppData\\Roaming\\Kodi\\addons\\script.elementum.burst\\burst\\providers\\icons\\torrentgalaxy.png', 'peers': 0, 'name': u'Fargo.S04E04.720p.WEBRip.x264-BAE[TGx]', 'language': None, 'uri': u'magnet:?xt=urn:btih:d5a09abef9484321048f222488317a290a888835&dn=Fargo.S04E04.720p.WEBRip.x264-BAE[TGx]&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce', 'seeds': 4, 'sort_resolution': 3, 'provider': u'[COLOR FFFFFFFF]TorrentGalaxy[/COLOR]', 'size': u'932.77 MB'}
```

They were skipped because other trackers had same torrent.
That logic of removing duplicates was long ago. That is odd, since Elementum is grouping them by torrent infohash.
I will change that, probably.

**Comment by burekas7** [comment]
@elgatito 

So it back to what @ShlomiD83 has mentioned regarding the same torrent indication, right?
The 'cloud' icon that we talked about?

**Comment by elgatito** [comment]
@burekas7 Try Burst 0.0.57. I have changed logic to remove duplicates only from the same provider.

**Comment by ShlomiD83** [comment]
> @burekas7 Try Burst 0.0.57. I have changed logic to remove duplicates only from the same provider.

now i see the cloud icon again, cool..

**Comment by burekas7** [comment]
> @burekas7 Try Burst 0.0.57. I have changed logic to remove duplicates only from the same provider.

Wow, what a beautiful view!!! :)
Finally it's working.
Thanks a lot.
@elgatito 

By the way, when starting playback from one of those 'clouds' options.
Which provider is it taking from? or all of them point to the same torrent so it doesn't matter actually?

![image](https://user-images.githubusercontent.com/13424257/104843135-b4d1f580-58d1-11eb-8fb6-243372d147f9.png)

**Comment by elgatito** [comment]
@burekas7 if it is a torrent file - it has all trackers collected. If magnet - it is the same for everyone.

**Comment by burekas7** [comment]
Thanks.
Closing this issue and also some additional with a similar issue.

**Comment by burekas7** [comment]
> @burekas7 if it is a torrent file - it has all trackers collected. If magnet - it is the same for everyone.

Just to verify, the seeds/peers amount in the results windoen will be the sum of all trackers if it is a torrent file?
And if it is a magnet they all show the same amount?

**Comment by burekas7** [comment]
> @burekas7 if it is a torrent file - it has all trackers collected. If magnet - it is the same for everyone.

@elgatito 
Just to make it clear, the seeds/peers amount in the results window will be actually the sum of all trackers if it is a torrent file?
And if it is a magnet they all show the same amount?

**Comment by elgatito** [comment]
@burekas7 no, only the highest number. Because they usually have same peers/seeds.
Does not matter magnet or torrent. Trackers are collected into one entry for both magnet/torrent.
