### ISSUE TITLE
YourBittorrent does not work

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#226]
Hi @elgatito Denis,
can you give a look at YourBittorrent provider?
It seems HTML has changed and no results are found.
I think also a `"subpage"` is needed.
Thanks!

**Comment by iz8mbw** [comment]
ping @elgatito

**Comment by elgatito** [comment]
@iz8mbw 
https://yourbittorrent.com/?q=avengers-endgame-2019&page=2
They don't give seeders, so these rows would be skipped anyway.
