### ISSUE TITLE
[request] add more search queries+ [bug] piratebay provider json

### ISSUE THREAD

**Issue by georgew21** [elgatito/script.elementum.burst#227]
Hello, congrats to developper for the awesome work.

firstly, it's seems to me that this line:   "movie_query": "200", on providers.json for piratebay is bug, as i have results from this site only if i leave this blank.

i am wondering if is possible to have the ability to make for tv shows a third search except for already 2 +1 if fallback.

as some tv shows' torrents have for name "name show season 1", or "name show s01", it could be useufull to have the option to search simutalneusly with "name show s0xe0x" and "name show s01" and "name show season x".

if it's easy to implent, i would thankfull to tell me someone what to add to code..

thanks a lot!

**Comment by georgew21** [comment]
i look more carefully and i understood how in reality the site accepts | as or

**Comment by elgatito** [comment]
0.0.54 supports up to 4 keywords for general searches and fallback searches.
Example:
```
        "tv_keywords": "{title:original} s{season:2}e{episode:2}",
        "tv_keywords_fallback": "\"{title:original} {season}\"",
        "tv_keywords_fallback2": "{title:original} \"Сезон {season}\""
```
