### ISSUE TITLE
[bug] "elementum download" from context menu searches only with the first keywords

### ISSUE THREAD

**Issue by georgew21** [elgatito/script.elementum.burst#228]
Hello, I see that when select elementum download option the results are different and less in comparison with elementum play option.

looking to debug, i see that elementum download option searches doesn't make search with keywords2. 

i don't know if this is problem of elementum or elementum burst.

hope for a fix.

**Comment by elgatito** [comment]
@georgew21 when you use context menu to search for item, Elementum is not able to get all the information, only the title, that is visible to you. So search is doing a specific request.

**Comment by georgew21** [comment]
look i see that it knows season and episode of shown. 

 my example is a tv show and i see that it searches for tv_keywords1. to be specific: searches with the query name show s01e01.

now, i have ovverride the tv_keywords2 for my seleted trackers  to search in tv_keywords2 with queries "name_show season 1 complete".

but although for elementum play it searches both tv_keywords (1+2), elementum download, although knows the season and episode, searches only for keywords 1 and omits to search with tv_keywords2.

**Comment by elgatito** [comment]
@georgew21 I can not help you here. 
There are 3 types of seach, movie/tv/global. 
Queries are sent to Burst, Burst use them for searching.
You can find all the information in your Kodi log files.

**Comment by georgew21** [comment]
in any case, the problem is indepently from my overriden code for some trackers. 

with default code, "elementum download" always searches only with keywords1 and don't make a search with keyword2 as the "elementum play" does. and i clarify that it knows the keywords2, because in tv shows keywords1 and keyword 2 are the same, but writting in different order.  

 this point i have sign as bug.

**Comment by elgatito** [comment]
@georgew21 

> You can find all the information in your Kodi log files.

**Comment by georgew21** [comment]
@elgatito firstly, thanks you to be so kind and patient replying me.

well, you are right, that with context menu elementum searches have less info and doesn't uses all the ways as does when we select play.

the problem is the following: in android is more efficient to use memory instead for files and as result the only way to download is using context menu because we don't have the dialog to ask us for download when we stop playing. but with context menu the results aren't as good as when using the standard play action. 

so, it could be possible "elementum context actions" when these are used from inside the elementum video addon, get all the info of the file to have the same search results as when we select play?

if it isn't possible, could we have an option on settings to ask us always for download the file in path for downloads when we cancel the prebuffering, even if we have choose memory as method?

i find that download option is usefull for torrents will few seeders.

i hope to be clear and thank for your interest to reply me.

**Comment by elgatito** [comment]
> the problem is the following: in android is more efficient to use memory instead for files and as result the only way to download is using context menu because we don't have the dialog to ask us for download when we stop playing. but with context menu the results aren't as good as when using the standard play action.

I don't understand this. You can select to use files or memory storage in your addon settings.

> so, it could be possible "elementum context actions" when these are used from inside the elementum video addon, get all the info of the file to have the same search results as when we select play?

Context addon does this, what it can.

> if it isn't possible, could we have an option on settings to ask us always for download the file in path for downloads when we cancel the prebuffering, even if we have choose memory as method?

I will not do this, it makes no sense for me. Source is open, so you can do any changes on your own.

**Comment by georgew21** [comment]
I tried to explain the point but I respect that it isn't so big to spend all time talking about this.

 when i want to download to disk an title (because of few seeders) i will change temporarily the settings to files instead memory.

so I respect your reply and I close this issue.

**Comment by georgew21** [comment]
Thanks you @elgatito  that you improved search function on burst.

But now, I see that burst searches only with tv_keywords2, while in previous versions it made searches with tv_keywords and tv_keywords2 and gathering all the results from the 2 searches.

These are the keywords that I have set in providers.json file for piratebay: 

"tv_keywords": "{title:en} s{season:2}e{episode:2}|S{season:2}",
"tv_keywords2": "{title:en} season {season:1}",
"tv_keywords_fallback": "{title:en} s1|s01"

And this is the log for the searches in which you can see that it makes searches using only tv_keyword2 and not using also the  tv_keywords as before.

https://pastebin.com/dCSL6fnM

How can I set to makes searches as before with both tv_keywords and tv_keywords2 simultaneously?

**Comment by elgatito** [comment]
You must set log level to Debug in Burst, before making log.

**Comment by georgew21** [comment]
I commented to wrong thread for my latest post with kodi log 

sorry,  I will delete this comment and I send the proper log with the problem to the correct issue.
