### ISSUE TITLE
Adding skytorrents.in

### ISSUE THREAD

**Issue by syneox** [elgatito/script.elementum.burst#24]
I don't know if it is possible but it would be so nice to add https://www.skytorrents.in as a search provider, in my opinion it is the best and largest torrent site available at the moment.

**Comment by nickshe89** [comment]
+1 i hope so

**Comment by syneox** [comment]
Works beautifully, thank you so much!

There's is only this for now https://www.skytorrents.in/images/sky_mini.jpg maybe you can use it, I see they also have favicon, maybe it is also useful:
https://www.skytorrents.in/favicon.ico

**Comment by syneox** [comment]
Here's [something](http://tinypic.com/r/vffcsw/9) for a moment, nothing special but I hope it will look better than empty space as it is now.

**Comment by syneox** [comment]
and slightly different [version](http://tinypic.com/r/33cr7g8/9), maybe a bit better

**Comment by syneox** [comment]
[RIP](https://torrentfreak.com/skytorrents-dumps-massive-torrent-database-and-shuts-down180221/) Skytorrents :(

If anything new comes up with their data base I'll post info, such unfortunate timing, it was really great site.
