### ISSUE TITLE
Adding a custom provider

### ISSUE THREAD

**Issue by coticj** [elgatito/script.elementum.burst#25]
Hi, I'm trying to add a custom provider, by specifying it in a json file here ~/.kodi/userdata/addon_data/script.elementum.burst/providers/nice_provider.json

But it is not detected when I go in Burst settings. Is there a special way of getting it working?

**Comment by elgatito** [comment]
Kodi does not allow dynamic settings for addon. So there are only predefined providers mentioned.
If you add custom provider via json file - it is enabled by default, so you should look into your kodi.log for more information whether it's loaded or not.

**Comment by jurecotic** [comment]
Aha, how about setting the username and password? Should I just hardcode them in my json file?

**Comment by elgatito** [comment]
@jurecotic , looks like burst is not using json-provided username/password fields. So you have to hardcode it, or I can add functionality to use json-provided in the next version.

**Comment by jurecotic** [comment]
Aha ok, thanks. I will try it out later in the afternoon and see if it works. Thanks.

**Comment by coticj** [comment]
I keep seeing the following error in the logs:

`23:33:01.084 T:3524260768   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.partis'.
23:33:01.084 T:3524260768   ERROR: Previous line repeats 1 times.
23:33:01.084 T:3524260768   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.partis-mc'.
23:33:01.087 T:3505894304   ERROR: Previous line repeats 1 times.`

I'm not getting any results from the provider I added, so I'm not sure now if there is some general issue or my parser is wrong?

**Comment by elgatito** [comment]
You should enable debug log in Kodi and then look over it. Selected part is not helping.

**Comment by Nemiroff** [comment]
script.magnetic.{provider-name} executed if set private=true, but username and password empty in settings file. So if you need add private provider, need change providers.json and settings.xml. But after update plugin from repo, your changes override

**Comment by MrDini123** [comment]
A dynamic settings.xml generator function would be a hard thing to implement from the Burst side?

**Comment by paskal** [comment]
I have error log entries about pre-build provider:
```[osmc@osmc-Hamilton ~]$ fgrep script.magnetic .kodi -ris
.kodi/temp/kodi.old.log:21:27:15.688 T:1404039936   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.tfile'.
.kodi/temp/kodi.old.log:21:27:15.689 T:1404039936   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.tfile-mc'.
```
I don't know if that's a problem at all. Also:
```21:31:43.674 T:1387262720  NOTICE: [script.elementum.burst] CloudHole key: {"key":"***"}
21:31:49.417 T:1387262720   ERROR: [script.elementum.burst] CloudHole error: IndexError('list index out of range',)
```

**Comment by elgatito** [comment]
> A dynamic settings.xml generator function would be a hard thing to implement from the Burst side?

It does not make sense. Kodi will rewrite it on each plugin upgrade and managing all those changes is a hell.
