### ISSUE TITLE
nCore provider update

### ISSUE THREAD

**Issue by daermond** [elgatito/script.elementum.burst#250]
nCore Private tracker web URL has been changed recently. New URL for the site is https://ncore.pro
Could you please update the provider for nCore with the new URL? Replace the https://ncore.cc with https://ncore.pro in the provider definitions. Site structure has not been changed just the access URL. I have tested with Domain Alias the provider and works fine with the https://ncore.pro value.

Thanks!

**Comment by elgatito** [comment]
Will be fixed in the next version.
