### ISSUE TITLE
Rarbg returns no results

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/script.elementum.burst#251]
Hi,
RARBG returns no results for movies & tv shows.
It doesn't seem related to the cloudflare issue.
please advise.

https://controlc.com/f4eab06f

**Comment by ShlomiD83** [comment]
I saw that another project fixed this issue, maybe you can check it out?

https://github.com/a4k-openproject/a4kScrapers/commit/14e9bff70d1ee1ec87bf0b51f2ddf8dc9adedbbf

**Comment by ShlomiD83** [comment]
@elgatito any help? Rarbg is the best provider :\

**Comment by burekas7** [comment]
@elgatito 

There is also the same problem with "idope".
Is it cloudflare issue or not?

Tested on: Moana 2016
https://idope.se/torrent-list/moana%202016/?&c=1

log: https://paste.ubuntu.com/p/3Ymd6qRHsF

**Comment by elgatito** [comment]
@ShlomiD83 From browser it shows fine, and headers say they are behind CloudFlare. I have no ideas with rarbg.

**Comment by elgatito** [comment]
@burekas7 https://idope.se:443/torrent-list/moana%202016/?&c=1 - that is behind cloudflare.

**Comment by ShlomiD83** [comment]
So nothing can be done? It worked until a few days ago. Something changed on the API side?

**Comment by ShlomiD83** [comment]
Rarbg always had issues with too many requests. On the first search usually it didn't return results, but on the second try and so on it worked fine.

**Comment by elgatito** [comment]
@ShlomiD83 I tried different things, I always get same error.

**Comment by ShlomiD83** [comment]
That sucks, Rarbg is the best provider.

**Comment by ShlomiD83** [comment]
Addons that use scrapers to get results from real debrid servers, torrents from torrentapi for example seem to work fine. Maybe they found a way to go around cloudflare?

**Comment by Condemned94** [comment]
The provider for Magnetic works on Rarbg. Maybe it's worth checking out what he's doing?

**Comment by ShlomiD83** [comment]
> The provider for Magnetic works on Rarbg. Maybe it's worth checking out what he's doing?

Magnetic is still working? Where can I find the installation?

**Comment by elgatito** [comment]
Any development help is welcome. 
I have no time for this.

**Comment by ShlomiD83** [comment]
@elgatito maybe you increase the time between requests sent to rarbg? I remember that in Magnetic @mancuniancol adjusted it for results to work.

**Comment by 123Freddys** [comment]
> 
> 
> > The provider for Magnetic works on Rarbg. Maybe it's worth checking out what he's doing?
> 
> Magnetic is still working? Where can I find the installation?

I think I installed it a long time ago through SuperRepo but I found [this](https://drive.google.com/open?id=19DZ2n6em8UT-5OKfDljbMlR-MRDT1Rb3) if you wanna check out whats happening behind the scenes

**Comment by ShlomiD83** [comment]
> > > The provider for Magnetic works on Rarbg. Maybe it's worth checking out what he's doing?
> > 
> > 
> > Magnetic is still working? Where can I find the installation?
> 
> I think I installed it a long time ago through SuperRepo but I found [this](https://drive.google.com/open?id=19DZ2n6em8UT-5OKfDljbMlR-MRDT1Rb3) if you wanna check out whats happening behind the scenes

I found the old zip files on my pc, installed it and RARBG is actually working.
too bad @elgatito doesn't have time to look at the code and maybe fixing our problem.

**Comment by 123Freddys** [comment]
I've just been sending the magnet link through the web UI. I know it ain't the same thing but it kinda works

**Comment by peterfrank81** [comment]
The Magnetic add-on really works well with RARBG as an Elementum provider.
In addition to being easy to set up and fast in the process, it is for the moment the best way to get around the "problem" of RARBG.
For those who have never used Magnetic, just download and use the zip file (provided above by friend @123Freddys, to whom I am grateful) for the normal installation of a local file, then just install the RARBG MC's Magnetic Parser and Elementum's Magnetic Provider from Magnetic repository (under Program add-ons).
From then on Elementum will also use the Magnetic provider, in addition to Burst, to find what you are looking for.
Have fun...

**Comment by ShlomiD83** [comment]
> The Magnetic add-on really works well with RARBG as an Elementum provider.
> In addition to being easy to set up and fast in the process, it is for the moment the best way to get around the "problem" of RARBG.
> For those who have never used Magnetic, just download and use the zip file (provided above by friend @123Freddys, to whom I am grateful) for the normal installation of a local file, then just install the RARBG MC's Magnetic Parser and Elementum's Magnetic Provider from Magnetic repository (under Program add-ons).
> From then on Elementum will also use the Magnetic provider, in addition to Burst, to find what you are looking for.
> Have fun...

that's actually working great.
I always thought that burst & magnetic can't work together.
cool!

**Comment by elgatito** [comment]
@ShlomiD83 

> @elgatito maybe you increase the time between requests sent to rarbg? I remember that in Magnetic @mancuniancol adjusted it for results to work.

Burst is getting 429 error on the very first request to rarbg and even with 10 seconds before retrying - same error with retry.

**Comment by antonsoroko** [comment]
@elgatito 
is not this 429 error from torrentapi.org but not from rargb itself? and look like even docs on torrentapi.org does not work for me.
(i am also having this issue with rarbg)

**Comment by elgatito** [comment]
@antonsoroko when you say rarbg, it's always torrentapi.org. Yes, 429 going from it. From browser it works fine.

**Comment by 123Freddys** [comment]
I've been looking at the logs and it says those 429 errors that elgatito has already talked about. It also says "failed to get token" or something like that, whatever that may be. I've also been comparing the providers code with the one from magnetic and it isn't that different I guess. Sheesh, I wish I could help but my understanding of any of this is really small.

**Comment by dlxmax** [comment]
**Thank you @elgatito for all your years of hard work on this.**
I hope somebody figures out the problem. Elementum with Rarbg is my expat couch-based TV provider.

BTW, I followed @peterfrank81's directions for setting up Magnetic, but I'm getting an error and I don't know why: https://pastebin.com/4G8uFPjv

**Comment by ShlomiD83** [comment]
TorrentGalaxy is also not working anymore, the site added a captcha.

**Comment by counttiefre** [comment]
Cool, thanks. Does Magnetic work with other providers?

The (free signup) private tracker for documentaries MVGroup.org doesn’t return any results either (never has, for me). Any idea if this can fix that?

And thank you elgatito for still checking out these threads and commenting, that’s really awesome, life would be so much worse without Elementum, haha.

**Comment by Dim0N22** [comment]
@elgatito I believe I've found and fixed the issue. Please take a look at #257.

I think we can safely remove referer for all requests.

**Comment by ShlomiD83** [comment]
> @elgatito I believe I've found and fixed the issue. Please take a look at #257.
> 
> I think we can safely remove referer for all requests.

Confirmed Working!
great job @Dim0N22

**Comment by ShlomiD83** [comment]
> @elgatito I believe I've found and fixed the issue. Please take a look at #257.
> 
> I think we can safely remove referer for all requests.

confirmed working!
thanks! @Dim0N22

**Comment by dlxmax** [comment]
Thanks @Dim0N22!
Confirmed fix on the new Kodi v19--glad to see Elementum is working fine there too, @elgatito.

Android path for the lazy: \internal\Android\data\org.xbmc.kodi\files\.kodi\addons\script.elementum.burst\burst\client.py
(delete line 269 and you're done)

**Comment by elgatito** [comment]
Should be working with 0.0.62.
Thanks to @Dim0N22
