### ISSUE TITLE
When searching other shows appear

### ISSUE THREAD

**Issue by tw11st** [elgatito/script.elementum.burst#253]
Hi.

When I **search** for a **specific Tv-Show**, then select episode it searches but then appears **other Shows randomly**.

And when I search for Anime in **nyaa** provider **it also happens.**

Can someone help me please?

Thanks in advance!

**Comment by elgatito** [comment]
@tw11st you need to post your log.

**Comment by tw11st** [comment]
@elgatito https://pastebin.pl/view/0f45a19c

**Comment by elgatito** [comment]
Nyaa returns a lot of crap for this query: https://nyaa.si/?f=0&c=1_0&q=dr.+stone+01x01%7CS01&s=seeders&o=desc
I'm not sure what is a better query for Nyaa. Maybe someone will help with it.

**Comment by tw11st** [comment]
@elgatito Can you please, look at this loh and tell me if aything is fixable.

Tried to find a episode of the series "You" and other ones appeared.

https://pastebin.pl/view/231017d4

**Comment by tw11st** [comment]
https://paste.kodi.tv/nejivatihi

**Comment by elgatito** [comment]
@tw11st you have made syntax errors in overrides file.

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.
