### ISSUE TITLE
[Request] Add Torrent TM & BT4G providers

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/script.elementum.burst#254]
Hi, is it possible to add https://torrent.tm/ & https://bt4g.org/ to Burst?

**Comment by ShlomiD83** [comment]
@elgatito can this be even done? i tried adding them myself with no success.

**Comment by elgatito** [comment]
@ShlomiD83 Both behind Cloudflare defence.

**Comment by ShlomiD83** [comment]
@elgatito thanks anyway.
