### ISSUE TITLE
Search works only into 2/3 providers since version 0.0.58

### ISSUE THREAD

**Issue by iz8mbw** [elgatito/script.elementum.burst#255]
Hi Denis @elgatito 
starting from Burst version 0.0.58 the search is made only into 2/3 providers also if I have more then 2 enabled...
It seems to search only on 1337x and on Zoogle (that seems why 1337x is the first one and Zoogle is the last one).

Here the Kodi log of the same search criteria:
search with version 0.0.57 (search working on multiple providers): https://paste.ee/p/O0qGd
search with version 0.0.60 (search NOT working on multiple providers): https://paste.ee/p/rk9gW

Thanks!

**Comment by elgatito** [comment]
@iz8mbw change logging level to DEBUG in Burst settings and make new logs.

**Comment by iz8mbw** [comment]
Hi @elgatito 
here the new logs with Debug:

search with version 0.0.57 (search working on multiple providers): https://paste.ee/p/AUTAJ
search with version 0.0.60 (search NOT working on multiple providers): https://paste.ee/p/ZlUjq


Thanks.

**Comment by elgatito** [comment]
@iz8mbw It is not with Debug. It the same log level. 
In Burst addon setting there is a setting for log level inside this specific addon.

**Comment by iz8mbw** [comment]
@elgatito this is what I did.
This is the setting I enabled:
![image](https://user-images.githubusercontent.com/3474082/108377840-b6f6df00-7204-11eb-9e25-a8986f6d2870.png)

**Comment by elgatito** [comment]
@iz8mbw That is not the required setting. You need the one that is selecting log level. And enable debug logging in Kodi, if not yet enabled.

**Comment by iz8mbw** [comment]
so you mean Kodi Debug level, not Burst Debug level. Ture?

**Comment by elgatito** [comment]
@iz8mbw Sorry, Burst does not have log level setting. That is managed by Elementum setting of Log level. 
It should help to get full log.

**Comment by iz8mbw** [comment]
Check that if now are OK.
[LOG.zip](https://github.com/elgatito/script.elementum.burst/files/6004074/LOG.zip)

**Comment by iz8mbw** [comment]
ping

**Comment by elgatito** [comment]
@iz8mbw No, it's the same. You can enable debug logging everywhere, maybe something is cutting log for you.
Enable debugging in Kodi.
Enable DEBUG level in Elementum addon settings.
Disable proxy internal proxy debugging in Elementum settings.
Disable parser logging in Burst settings.

**Comment by iz8mbw** [comment]
@elgatito hope now it's OK, see attached file.
[last.zip](https://github.com/elgatito/script.elementum.burst/files/6004841/last.zip)

Denis may be this details can help you: with version of Burst from 0.0.58 to more recent (the versions with issues), graphically I don't see that Burst will go to search into all enabled provider.. In fact the search is very very fast because, in my opinion, Burst will NOT really use all enabled providers (so don't access on them website).

**Comment by ShlomiD83** [comment]
> @elgatito hope now it's OK, see attached file.
> [last.zip](https://github.com/elgatito/script.elementum.burst/files/6004841/last.zip)
> 
> Denis may be this details can help you: with version of Burst from 0.0.58 to more recent (the versions with issues), graphically I don't see that Burst will go to search into all enabled provider.. In fact the search is very very fast because, in my opinion, Burst will NOT really use all enabled providers (so don't access on them website).

How do you use jacket? I've installed it but don't have an API.

**Comment by iz8mbw** [comment]
Jackett is not working well with Elementum.
So ignore it, it was a test

**Comment by elgatito** [comment]
@iz8mbw Yes, now log is complete.
When the issue started for you?

**Comment by iz8mbw** [comment]
@elgatito starting from version 0.0.58.
So the problem is with 0.0.58, 0.0.59 and 0.0.60.
0.0.57 was OK.

**Comment by iz8mbw** [comment]
Tested both on Android TV and Windows, same behavior (same issue)

**Comment by elgatito** [comment]
@iz8mbw Please, try v0.0.61

**Comment by iz8mbw** [comment]
@elgatito thanks Danis, 0.0.61 works again!
Many thanks for your support. 
Going to close this issue.
