### ISSUE TITLE
Интересный баг с буквой "й"

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/script.elementum.burst#259]
случайно заметил что буква й стала й (в зависимости от того в чём смотреть может выглядеть одинаково, но это разные символы)

в коди 18 с python3
```
2021-03-12 19:02:27.426 T:560802 WARNING <general>: [script.elementum.burst] [rutor] Using translated 'ru' title 'крайний космос'
2021-03-12 19:02:27.426 T:560802   DEBUG <general>: [script.elementum.burst] [rutor] Translated titles from Elementum: {'ar': 'الفضاء النهائي', 'bg': 'последен космос', 'br': 'final space', 'cn': '太空终界', 'da': 'final space', 'de': 'final space', 'dk': 'final space', 'en': 'final space', 'es': 'final space', 'he': 'חלל אינסופי', 'hu': 'az űr vége', 'il': 'חלל אינסופי', 'ko': '파이널 스페이스', 'kr': '파이널 스페이스', 'mx': 'final space', 'original': 'final space', 'pt': 'final space', 'ru': 'крайний космос', 'sa': 'الفضاء النهائي', 'source': 'Final Space', 'tr': 'son uzay', 'tw': '太空終界', 'ua': 'останній рубіж', 'uk': 'останній рубіж', 'zh': '太空終界'}
```
если сравнить эти 2 символа на https://www.branah.com/unicode-converter например
обычная
![image](https://user-images.githubusercontent.com/17964763/110967658-b23acc00-8367-11eb-897e-5ac8acd71e1e.png)
"необычная"
![image](https://user-images.githubusercontent.com/17964763/110967628-a949fa80-8367-11eb-802b-785af0a4207b.png)

похоже что [`remove_accents`](https://github.com/elgatito/script.elementum.burst/blob/e43cd1732aae42d8df29f115dea7af271d199663/burst/filtering.py#L422) как-то стал ломать строку (от Elementum приходит обычная й, если смотреть лог).

в 17м с python2
```
18:42:12.531 T:18446744072605407600  NOTICE: [script.elementum.burst] [rutor] Using translated 'ru' title u'\u043a\u0440\u0430\u0439\u043d\u0438\u0439 \u043a\u043e\u0441\u043c\u043e\u0441'
18:42:12.533 T:18446744072605407600   DEBUG: [script.elementum.burst] [rutor] Translated titles from Elementum: {u'en': u'final space', u'zh': u'\u592a\u7a7a\u7d42\u754c', u'cn': u'\u592a\u7a7a\u7ec8\u754c', u'ar': u'\u0627\u0644\u0641\u0636\u0627\u0621 \u0627\u0644\u0646\u0647\u0627\u0626\u064a', u'il': u'\u05d7\u05dc\u05dc \u05d0\u05d9\u05e0\u05e1\u05d5\u05e4\u05d9', u'es': u'final space', u'ru': u'\u043a\u0440\u0430\u0439\u043d\u0438\u0439 \u043a\u043e\u0441\u043c\u043e\u0441', u'pt': u'final space', u'tw': u'\u592a\u7a7a\u7d42\u754c', u'tr': u'son uzay', u'source': u'Final Space', u'bg': u'\u043f\u043e\u0441\u043b\u0435\u0434\u0435\u043d \u043a\u043e\u0441\u043c\u043e\u0441', u'dk': u'final space', u'de': u'final space', u'hu': u'az \u0171r v\xe9ge', u'br': u'final space', u'da': u'final space', u'he': u'\u05d7\u05dc\u05dc \u05d0\u05d9\u05e0\u05e1\u05d5\u05e4\u05d9', u'ko': u'\ud30c\uc774\ub110 \uc2a4\ud398\uc774\uc2a4', u'original': u'final space', u'kr': u'\ud30c\uc774\ub110 \uc2a4\ud398\uc774\uc2a4', u'uk': u'\u043e\u0441\u0442\u0430\u043d\u043d\u0456\u0439 \u0440\u0443\u0431\u0456\u0436', u'sa': u'\u0627\u0644\u0641\u0636\u0627\u0621 \u0627\u0644\u0646\u0647\u0627\u0626\u064a', u'ua': u'\u043e\u0441\u0442\u0430\u043d\u043d\u0456\u0439 \u0440\u0443\u0431\u0456\u0436', u'mx': u'final space'}
```
где `\u0439` это обычное `й`

пример полного лога https://paste.kodi.tv/qatupozixa.kodi

**Comment by elgatito** [comment]
Testing with merged changes. This item; https://www.themoviedb.org/movie/446893-trolls-world-tour
Rutor + RUtracker.

```
2021-03-20 15:14:17.841 T:30832   DEBUG <general>: [script.elementum.burst] [rutor] Before keywords - Query: '{title:ru} {year}' - Extra: ''
2021-03-20 15:14:17.842 T:30832 WARNING <general>: [script.elementum.burst] [rutor] Using translated 'ru' title '.'
```

As you can see, all non-latin characters removed from query.

**Comment by elgatito** [comment]
You can place `continue` at `providers.py` to avoid making requests but see what is a query in each case.

```
        query = filtering.process_keywords(provider, query)
        extra = filtering.process_keywords(provider, extra)

        continue
```

**Comment by antonsoroko** [comment]
получается это проблема существовала и раньше для py2 (но была не видна на новом изменении для py3).
проверил на kodi 17.

**Comment by elgatito** [comment]
@antonsoroko то что я запостил, это Коди 19.

**Comment by elgatito** [comment]
На Коди 18 (Coreelec) то же самое с этим фильмом.

**Comment by antonsoroko** [comment]
я про то, что этот баг просто скрылся после неправильной миграции той строки кода на python 3. но поломалось удаление "Диакритический знаков".

можно например удалять все спец символы тут
https://github.com/elgatito/script.elementum.burst/blob/0707138a54e96bdc559a68ea5d0639a8322e047b/burst/provider.py#L108
что может быть полезно для сайтов которые не понимают их, как например rutor не понимает `'` (надо искать без `'`), но не знаю как поведут себя другие сайты.

или временно удалять их тут https://github.com/elgatito/script.elementum.burst/blob/master/burst/normalize.py#L59
чисто для проверки что без них строка стала пустая.

**Comment by elgatito** [comment]
@antonsoroko Вроде получше с #262. Вот еще на этом можно проверять: https://www.themoviedb.org/tv/60572-pok-mon/titles , там символ часто не даёт нормально искать.

**Comment by antonsoroko** [comment]
@elgatito 

вообще я для интереса поигрался и для русского/белорусского/украинского NFKD форма выдаёт
![image](https://user-images.githubusercontent.com/17964763/111880498-0a537d00-89bd-11eb-8da1-0b534c87313d.png)

и по идее можно было бы использовать `.encode('cp1251', 'ignore').decode('cp1251', 'ignore')` чтобы получить из "двойных" `йёїў` `иеіу`

но вроде как и рутор и рутрекер нормально понимают наши "Диакритические знаки", так что можно забить.

но если глянуть на 
https://ru.wikipedia.org/wiki/Кириллица
и
https://ru.wikipedia.org/wiki/Алфавиты_на_основе_кириллицы

то не угадаешь надо ли им конвертировать буквы или нет. (хотя cp1251 работает для них вроде как)
