### ISSUE TITLE
[Feature Request] Provide Burst support for Quasar

### ISSUE THREAD

**Issue by santiagoroza** [elgatito/script.elementum.burst#26]
I tried installing Elementum Burst alongside Quasar (in both Linux and Android) but it didn't pick it up as a provider. Would it be possible to make Elementum Burst compatible with Quasar (as a Quasar Burst replacement)?

**Comment by elgatito** [comment]
Quasar has a check, that providers should be named as *script.quasar.*. If you want - you can fork and make your own plugin and it will be visible to Quasar.
