### ISSUE TITLE
New Provider Request: Filebase

### ISSUE THREAD

**Issue by Krolik1988** [elgatito/script.elementum.burst#270]
Hello, I would like to ask someone to try add provider [Filebase](http://www.filebase.ws/torrents/). It's RU Free. 
Kind regards,

**Comment by antonsoroko** [comment]
you can try to create it by yourself by using some existing tracker that works similar (in terms of search) as example.

e.g. https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json#L138

**Comment by Krolik1988** [comment]
> you can try to create it by yourself by using some existing tracker that works similar (in terms of search) as example.
> 
> e.g.
> 
> https://github.com/elgatito/script.elementum.burst/blob/a13443eb8233859cfeb44c0ac7c34b1ac9dcc2d3/burst/providers/providers.json#L138

Привет Антон, дело в том что я использую Kodi на андройд боксе и у меня не будет возможности проверить всё ли верно.

**Comment by antonsoroko** [comment]
у меня тоже андроид тв бокс, когда надо проверить прямо на нём - я использую X-plore File Manager -  у него есть wifi проводник, можно заменять/редактировать файлы.
хотя, конечно проще временно на комп поставить коди и елементум.

в любом случае, я просто к тому, что активных участников в сообществе очень мало, соотв маловероятно, что кто-то сделает это. поэтому и предложил попробовать самому.

**Comment by Krolik1988** [comment]
Вопшем у меня тут фиаско.

**Comment by antonsoroko** [comment]
набросок кода есть?
и ошибки может из лога (надо включить в коди полный лог, тогда будет видно всё что делает burst. перед этим отключить все провайдеры, кроме тестируемого).

**Comment by Krolik1988** [comment]
Пока так:

`"Filebase": {
        "anime_extra": "",
        "anime_keywords": "{title} {episode}",
        "anime_query": "EXTRA",
        "base_url": "http://www.filebase.ws/torrents/search/?search=EXTRA&c=0&t=liveonly",
        "color": "FFF14E13",
        "general_extra": "EXTRA",
        "general_keywords": "{title}",
        "general_query": "EXTRA",
        "language": "ru",
        "languages": "ru, en",
        "movie_extra": "",
        "movie_keywords": "{title} {year}",
        "movie_query": "EXTRA",
        "name": "Filebase",
        "enabled": true,
        "predefined": true,
        "private": false,
        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title} Season {season:2}",
        "season_keywords2": "{title} Season{season}",
        "season_query": "EXTRA",
        "separator": "+",
        "show_query": "EXTRA",
        "subpage": true,
        "tv_extra": "EXTRA",
        "tv_extra2": "EXTRA",
        "tv_keywords": "{title} s{season:2}e{episode:2}",
        "tv_keywords2": "",
        "tv_keywords3": "",
        "tv_keywords_fallback": "",
        "tv_keywords_fallback2": ""
    }`

Логов нет.

**Comment by antonsoroko** [comment]
вроде вышло, у меня работает. тестируйте, если норм, то попрошу замержить PR на его добавление.

в `.kodi/addons/script.elementum.burst/burst/providers/providers.json` добавить:
```
    },
    "filebase": {
        "anime_keywords": "{title:en:ru}",
        "anime_keywords_fallback": "{title:original}",
        "anime_query": "&c=anime",
        "base_url": "http://www.filebase.ws/torrents/search/?search=QUERY&t=liveonly&s=seedD",
        "color": "FFF14E13",
        "general_keywords": "{title}",
        "general_query": "&c=0",
        "language": "ru",
        "languages": "ru",
        "login_failed": "Имя пользователя введено неверно",
        "login_object": "{'uid': USERNAME, 'pwd': PASSWORD}",
        "login_path": "/login.php",
        "movie_keywords": "{title:en:ru} {year}",
        "movie_keywords_fallback": "{title:original} {year}",
        "movie_query": "&c=0",
        "name": "Filebase",
        "parser": {
            "infohash": "",
            "name": "item(tag='a', order=2)",
            "peers": "item(tag='td', order=8)",
            "row": "find_once('table', ('id', 'torrents_list'), order=1).find_all('tr', start=2)",
            "seeds": "item(tag='td', order=7)",
            "size": "item(tag='td', order=5)",
            "torrent": "'http://www.filebase.ws/download.php?id=%s' % item(tag='a', attribute='href', order=2, divider=('/', 3))"
        },
        "enabled": true,
        "predefined": false,
        "private": true,
        "subpage": false,
        "separator": "+",
        "root_url": "http://www.filebase.ws",
        "season_query": "&c=EXTRA",
        "season_keywords": "{title:en:ru} {season} сезон",
        "season_extra": "serials",
        "season_keywords_fallback": "{title:en:ru} {season} сезон",
        "season_extra_fallback": "cartoons",
        "show_query": "&c=EXTRA",
        "tv_keywords": "{title:en:ru} {season} сезон {episode} сери",
        "tv_extra": "serials",
        "tv_keywords2": "{title:en:ru} {season} сезон {episode} сери",
        "tv_extra2": "cartoons",
        "tv_keywords_fallback": "{title:en:ru} {season} сезон",
        "tv_extra_fallback": "serials",
        "tv_keywords_fallback2": "{title:en:ru} {season} сезон",
        "tv_extra_fallback2": "cartoons"
    }
 ```
в `.kodi/addons/script.elementum.burst/resources/settings.xml`

```
    <setting label="[B]Filebase[/B]   [COLOR gray][$ADDON[script.elementum.burst 32114]][/COLOR]" id="use_filebase" type="bool" default="false" />
      <setting id="filebase_username" label="32015" type="text" default="" subsetting="true" visible="eq(-1,true)" />
      <setting id="filebase_password" label="32016" type="text" default="" option="hidden" subsetting="true" visible="eq(-2,true)" />
      <setting id="filebase_alias" label="32077" type="text" default="" subsetting="true" visible="eq(-3,true)" />
      <setting id="filebase_contains" type="enum" label="32080" subsetting="true" lvalues="32081|32082|32083" visible="eq(-4,true)" />
```
после
```
  <category label="32130">
    <!-- Providers-Private-1-Begin -->
```

для понимания:
в burst сначала ищутся одновременно все `_keywords/2/3/4/5` ,а потом если ничего не найдено - `tv_keywords_fallback/2/3/4/5` по одному за раз, пока не будет результата (т.е. 1й fallback дал результат, остальные не будут использоваться уже).


соотв:
1) для аниме ищем по названию, так как я не заметил какого-то нормального формата имен у раздач. ру/анг одновременно, если не найдено - оригинальное название.
2) для фильмов ищем по названию и году. ру/анг одновременно, если не найдено - оригинальное название.
3) для сезонов ищем сначала в сериалах, если не найдено - то в мультфильмах (для мультсериалов). чтобы не нагружать зря трекер.
4) для серий ищем конкретную серию в сериалах и мультфильмах одновременно (`сери` специально, так как там окончания по разному пишут, а дублировать под каждое не охота). если не найдено - то ищем сезон, сначала в сериалах, потом в мультфильмах.

на этом трекере похоже единого стандарта для сериалов нет, так как поиск который я написал может выдавать не 100% результатов.

если хотите, посмотрите примеры как я делал для torrentby/rutor (правда rutor поддерживает логические выражения, без них все варианты не влезли бы даже) и сделайте похоже для сериалов с учетом специфики именования на трекере. потом напишите мне и я добавлю новые варианты для поиска.

**Comment by Krolik1988** [comment]
Привет, большое спасибо. Но по большому счёту трекер 

private = false.  Тут не обязателен логин пароль. 

Завтра проверю.

**Comment by antonsoroko** [comment]
ок, сделал его публичным.

**Comment by Krolik1988** [comment]
Привет ещё раз. Нет, у меня не завелось. Ты пробовал искать что-то после изминений на приватный? Ведь пологаю и в seteings.XML что-то до поменять нужно.

**Comment by antonsoroko** [comment]
>изменения тогда можно копировать напрямую из PR.

**Comment by Krolik1988** [comment]
Не очень тебя понимаю.

**Comment by antonsoroko** [comment]
я имею ввиду из PR который я привязал выше - https://github.com/elgatito/script.elementum.burst/pull/278/files

но вообще и со старым кодом настроек работать будет. просто проигнорирует логин и пароль если их ввести.

не забудьте про запятую, иначе json не прочитается
```
}, <----
    "filebase": {
```

**Comment by antonsoroko** [comment]
есть вариант проще - скачать https://raw.githubusercontent.com/antonsoroko/script.elementum.burst/add-filebase/burst/providers/providers.json и https://raw.githubusercontent.com/antonsoroko/script.elementum.burst/add-filebase/resources/settings.xml и заменить ими файлы дополения

**Comment by Krolik1988** [comment]
Фиаско. Может где-то что-то поколечил до этого. Попробую всё переустановить и отпишусь.

**Comment by Krolik1988** [comment]
И опять нет. Ищу слова "Spider"/"Человек" - не находит. Установил коди на другую систему с 0. Оставил включённым только этого провайдера. Другие провайдеры ищут. Мистика, ведь если у тебя работает, то и уменя должно работать.

**Comment by antonsoroko** [comment]
ищешь как? я через тракт проверял. на фильмах, сезонах и сериях.
сейчас вот еще на просто глобальном поиске проверил
tenet - ок
довод - ок

логи нужны - http://elementum.surge.sh/contribute/log/


burst у меня 0.0.65
elementum 0.1.76
kodi 19

**Comment by Krolik1988** [comment]
Запускаю коди, захожу в елементум, поиск. 

Сейчас не "у руля". 

Если не ошибаюсь то тоже, качал последнее что было.

**Comment by antonsoroko** [comment]
может или не в том месте заменены файлы или может нет доступа к трекеру с устройства (блокировки там и прочее).

без лога ничего дельного сказать не могу.

**Comment by Krolik1988** [comment]
Это врятле. На торрент заходит, файлы качает. Так же ищет на других торрентах. Завтра попробую глянуть.

**Comment by Krolik1988** [comment]
Привет, тысяча извенений. Видать что-то перенастраивали в настройках сети и действительно он не давал качать торенты. Под ВПН всё окей. Большое спасибо. Можно заливать. Хорошего тебе дня.

**Comment by antonsoroko** [comment]
отлично.

повторюсь что
```
на этом трекере похоже единого стандарта для сериалов нет, так что поиск который я написал может выдавать не 100% результатов.

для вещей аля "Название (1-4 серии из 4)" я не писал запросы.

если хотите, посмотрите примеры как я делал для torrentby/rutor (правда rutor поддерживает логические выражения, без них все варианты не влезли бы даже) и сделайте похоже для сериалов с учетом специфики именования раздач на этом трекере. протестируйте их и потом напишите мне и я добавлю новые варианты для поиска.
```

если решите добавить новые запросы, то тогда уже сразу как PR можно будет оформлять, так как надеюсь текущий PR замержим скоро.
