### ISSUE TITLE
Неправильный поиск в burst

### ISSUE THREAD

**Issue by spawnlmg** [elgatito/script.elementum.burst#28]
Значит в самом элементуме настройки стоят такие
Сортировка по разрешениям
Приоритет разрешений 1080/720/480
В burst включаем 2160p и 1080p
првайлер RUTOR
и ищем например "Чудо-женщина"
В результатах видим 4К -2шт, 1080 - 6шт
теперь добавляем еще в настройках burst разрешение 720p
и опять ищем
реультат 4К - 1шт, 1080 - 3шт, 720 - 21шт
почему так?
По правильному должно вывести все теже 4К -2шт, 1080 - 6шт и добавить еще 17шт из 720, т.к. в настройках burst ограничение выставлено на максимум 25результатов! Как мне это видится весь процесс поиска в данный момент, burst вытягивает при поиске все, что найдено по поисковому запросу, а потом по фильтрам просто берет первые 25шт, никак не сортируя первоначально по значимости видео! Это не правильно, т.к. во втором поиске отбросило 4к-1шт и 1080-3шт, среди которых могут быть нужные раздачи! И такая неправильная сортировка во всех провайдерах.

[kodi_720.zip](https://github.com/elgatito/script.elementum.burst/files/1747964/kodi_720.zip)
[kodi.zip](https://github.com/elgatito/script.elementum.burst/files/1747965/kodi.zip)

И есть проблема именно в провайдере RUTOR, посмотри в логе который без 720, находит всего 6шт 1080, хотя на сайте их 9шт.
И это видно в логе, что почему-то их откинуло, хотя 1080 в названии присутствует
DEBUG: [script.elementum.burst] [rutor] чудо женщина wonder woman 2017 bdremux 1080р от exkinoray 3d video лицензия *** Resolution not allowed
DEBUG: [script.elementum.burst] [rutor]     чудо женщина wonder woman 2017 bdremux 1080р от exkinoray лицензия *** Resolution not allowed
DEBUG: [script.elementum.burst] [rutor]       чудо женщина wonder woman 2017 bdrip 1080р от exkinoray лицензия *** Resolution not allowed

**Comment by spawnlmg** [comment]
1. Значит с ошибкой разобрались, в имени 1080p буква "p" написана в русской раскладке!
2. На счет сортировки, burst отдает полученные и отфильтрованные результаты отсортированные по кол-ву раздающих, а нужно чтобы был и вариант по разрешению. Настройки сортировки выставленные в самом элементуме никак не влияют на сортировку в burst. Нужно сделать в burst настройки сортировки.
3. И почему-то те раздачи которые с русской "p" burst определяет ни как 1080, а как 720 и 480
скрин ниже
![burst](https://user-images.githubusercontent.com/23347625/36554366-c5880292-1807-11e8-882c-71dd629edc46.jpg)

**Comment by elgatito** [comment]
Определение для сортировки в списке результатов делает сам elementum. Burst определяет только для фильтрации определение. И там и там будет поддерживаться русская "р" в названии в следующих версиях.

**Comment by elgatito** [comment]
Closing the issue. 
Changes in Burst applied, for matching Cyrillic "p". Changes in Elementum applied and will be available in 0.0.52.
