### ISSUE TITLE
Updates failing in Kodi 19 due to Indigo dependency

### ISSUE THREAD

**Issue by Djtrip83** [elgatito/script.elementum.burst#280]
I am on Kodi 19 and I cannot update  simply because of the Indigo dependency not being compatible with Kodi 19. This affects any update where the add-on has such dependency. Can we please remove the dependency so the add-on and any future fork can be updated?

[Similar ticket here](https://github.com/tvaddonsco/plugin.program.indigo/issues/20)

**Comment by elgatito** [comment]
@Djtrip83 Burst does not depend on any external dependency, except Elementum. 

```
    <requires>
        <import addon="xbmc.addon" version="16.0.0" />
        <import addon="plugin.video.elementum" optional="true"/>
        <import addon="script.module.kodi-six" />
        <import addon="script.module.future" version="0.16.0.4"/>
    </requires>
```
