### ISSUE TITLE
There are many results missing from the torrent listings. (rus)

### ISSUE THREAD

**Issue by slavatyn** [elgatito/script.elementum.burst#289]
I took as an example anime, seven deadly sins, rutracker. 
Comparing with the nova plugin (there are all those results that are not in burste and vice versa), maybe I understood what was the reason. 
Burst searches for results with the postscript "season 1", and in my example there are much more results with the postscript "TV-1" or in Russian "ТВ-1," is it possible combine the search between "season 1" and "tv-1"
Or the problem is something else?

**Comment by slavatyn** [comment]
Вкратце о проблеме - в моём примере почти во всех раздачах вместо "Сезон 3" пишется "ТВ-3"
Супер! То что надо, немного поэкспериментировал и есть 2 вопроса.

1. "anime_keywords_fallback" < burst начинает использовать это в случае если  "anime_keywords" варианты не найдены?
А есть команда которая позволила выдать сразу 2 или более вариантов например


 "anime_keywords": "\"{title:en:ru}\" \"Сезон {season}\"", 
и
 "anime_keywords": "\"{title:en:ru}\" \"ТВ- {season}\"", 
и
 "anime_keywords": "\"{title:en:ru}\" \"TV- {season}\"", 


2. Можно ли сделать условие если  {season}=1 вместо "ТВ- {season}" пробей "ТВ"
потому что если это 1 сезон то пишется просто ТВ без цифры

**Comment by antonsoroko** [comment]
1. `anime_keywords` может быть до 5 штук, `anime_keywords2` и так далее (в файле есть примеры). они будут одновременно. но это увеличит нагрузку на сайт трекера (плохо для их сервера. хотя вряд ли сильно увеличит) и время поиска (плохо для пользователя). короче можно, просто осторожно.
2. нет. но это можно в `_fallback` добавить - если не нашло "ТВ-1", то только тогда пробуй еще "ТВ". ("только тогда" - чтобы не было левых результатов, так как "ТВ" выцепит все раздачи данного сериала с "ТВ" в названии, аля для "ТВ-2" будет показан ещё "ТВ-3" и "ТВ-4".)

просто на заметку: некоторые трекеры, как rutor, поддерживают логические выражения аля https://github.com/elgatito/script.elementum.burst/blob/224729a3f85a964aeabfed54c3e330f583f784bc/burst/providers/providers.json#L1651
тогда можно больше магии запихать в один запрос.

**Comment by slavatyn** [comment]
С rutracker не получается добить 1 сезон(
"anime_keywords2": "\"{title:en:ru}\" \"TV-{season}\"",
С этим условием 2 и далее сезоны начали находиться почти все раздачи, супер!)
Но 1 сезон( 
Он вбивает в поиск - Семь смертных грехов TV 1
https://rutracker.nl/forum/tracker.php?nm=%D1%81%D0%B5%D0%BC%D1%8C%20%D1%81%D0%BC%D0%B5%D1%80%D1%82%D0%BD%D1%8B%D1%85%20%D0%B3%D1%80%D0%B5%D1%85%D0%BE%D0%B2%20TV%201

1.Есть раздача, она попадает в список-Семь смертных грехов (ТВ-4) / Nanatsu no Taizai: Fundo no Shinpan [TV] [1-19 из 24]
Часто бывает что в раздачах пишут с 1 серии по... и такая раздача попадает в список следовательно fallback не сработает(


2. Все раздачи где просто написано ТВ он не видит например-Семь смертных грехов / Nanatsu no Taizai (Окамура Тэнсай) [TV] [24 из 24] [Без хардсаба] [RUS(ext), JAP+Sub] [2014, приключения, фэнтези, BDRip] [1080p]

3. 

Что касается 2 и далее сезонов стало лучше, но 1 сезон таким способом по-прежнему не достать(
Ранее пользовался nova там было не важно какой сезон выбираешь он всё равно давал почти все раздачи, приходилось выбирать но 1 сезон не пропадал, но кстати там не было результатов с "Сезон", поэтому начал вопрос поднимать
Может есть какие-то идеи, возможности?( 

"если всё получится - сделайте пожалуйста PR с изменениями или хотя бы сюда скиньте. думаю людям будет полезно."
Да, сделаю обязательно! Хочу rutracker финально закончить и по аналогии сделать в остальных русских трекерах где это актуально

**Comment by antonsoroko** [comment]
как по мне - это плохой дизайн названий раздач на трекере. он не чёткий и соотв не дружелюбный к компьютерам.

тут или выкидывать `-{season}` из запросов и тогда будет отдавать всё или жить без первого сезона для таких вот раздач.

кстати, есть ещё "Вспомогательные элементы поиска" у рутрекера http://rutracker.wiki/Как_пользоваться_поиском#.D0.92.D1.81.D0.BF.D0.BE.D0.BC.D0.BE.D0.B3.D0.B0.D1.82.D0.B5.D0.BB.D1.8C.D0.BD.D1.8B.D0.B5_.D1.8D.D0.BB.D0.B5.D0.BC.D0.B5.D0.BD.D1.82.D1.8B_.D0.BF.D0.BE.D0.B8.D1.81.D0.BA.D0.B0

но в данном случае они вроде не помогут. но знать их полезно.


может @elgatito что сможет подсказать.

**Comment by elgatito** [comment]
Если сайт криво ищет или не имеет возможности делать строгий поиск, и названия не стандартизированы, то это всё заканчивается компромиссами.

**Comment by slavatyn** [comment]
serialz.tv - похоже закрылся

В nnmclub и rustorka ищет в том числе 1 сезон, проблема только у rutracker
Только в этих 3ёх вместо сезон используется TV

Добавил
"nnmclub"
"anime_keywords3": "{title:ru:en} \"TV-{season}\"",
"rustorka"
"anime_keywords2": "{title:ru:en} \"TV-{season}\"",
"rutracker"
"anime_keywords2": "\"{title:en:ru}\" \"TV-{season}\"",

Пока не могу разобраться с PR(


[providers (добавленно поиск аниме по ТВ).zip](https://github.com/elgatito/script.elementum.burst/files/6555830/providers.zip)

**Comment by antonsoroko** [comment]
@slavatyn 

>Пока не могу разобраться с PR(

открываете
https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json
и жмете кнопочку редактирования (иконка карандаш) - всё остальное github сделает сам.
откроется редактор, там делаете изменения и в самом низу форма создания PR. перед отправкой PR - можно сделать предпросмотр изменения.
ну и вместо табуляций - пробелы.

это уже последняя версия или ещё что-то будете пробовать менять?

**Comment by slavatyn** [comment]
Красота! Спасибо за помощь!

"это уже последняя версия или ещё что-то будете пробовать менять?"
Что касается аниме думаю да(Совсем недавно пользоваться стал, мало что успел опробовать, супер вещь, спасибо!), проверил все русские торренты, больше изменений не нужно.
Единственное что, возможно нужно было удалить в этих 3ёх "anime_keywords": "\"{title:en:ru}\" \"Сезон {season}\"", я понадеялся что это не добавляет сильной нагрузки и в крайне редких случаях может пригодиться.

**Comment by antonsoroko** [comment]
:+1: 

для rutracker можно  по идее добавить

`"anime_keywords_fallback3": "{title:ru:en} TV",`

но не уверен, что до него дойдёт очередь (учитывая ваш пример выше). но может для редкого аниме какого и дойдёт.
правда оно может перекрыться `"anime_keywords_fallback2": "\"{title:en:ru:original} {season}\"",`
короче я не знаток аниме раздач на rutracker, поэтому сложно судить.

**Comment by antonsoroko** [comment]
@slavatyn будете ещё что-то добавлять? если нет, то закройте тикет пожалуйста.
