### ISSUE TITLE
Unable to get proper results

### ISSUE THREAD

**Issue by naveen1hot** [elgatito/script.elementum.burst#305]
Hi folks and @elgatito 
PFA and I'm not getting proper results while compare to the website.
I have increased number of results to 25 in burst. Still problem not solved.
Pls help
![Screenshot_20210901-124926](https://user-images.githubusercontent.com/67212860/131634819-c642aa19-f5e4-4746-88b4-7b5873cf1222.jpg)

![Screenshot_20210901-124500__01](https://user-images.githubusercontent.com/67212860/131635362-053f433a-8990-44a4-a658-d8aac0153e23.jpg)

Thanks in advance

**Comment by antonsoroko** [comment]
https://elementumorg.github.io/contribute/log/

**Comment by naveen1hot** [comment]
Even rarbg also having same issue.

**Comment by naveen1hot** [comment]
hi anton thanks for the reply. i resolve the issue. by adding keywords.
  "movie_keywords": "{title} x265 {year}",

Request to add in advanced section search with keyword instead of filter.

**Comment by antonsoroko** [comment]
>Request to add in advanced section search with keyword instead of filter.

please paraphrase.

**Comment by elgatito** [comment]
Not much information here.Closing.
