### ISSUE TITLE
Can't seem to change providers.json.

### ISSUE THREAD

**Issue by rockofclay** [elgatito/script.elementum.burst#307]
I have been trying to add a provider to "%AppData%\Kodi\addons\script.elementum.burst\burst\providers\providers.json", but it seems the settings are not reflected in the Elementum Burst configuration page. Even only modifying an existing one shows no update to the name of the provider.

Am I missing something simple?

**Comment by rockofclay** [comment]
Never mind! I found that settings.xml doesn't get generated when adding providers, so it doesn't update the configuration page. Provider gets added though.

**Comment by antonsoroko** [comment]
in case if you will want to share your provider by creating a PR, here is the script that generates settings:
https://github.com/elgatito/script.elementum.burst/blob/master/scripts/generate_settings.py
