### ISSUE TITLE
how to add new provider using android 11 with not root

### ISSUE THREAD

**Issue by leandrocaldas** [elgatito/script.elementum.burst#308]
I created a new server and this json file is perfeccting working on other android device, but now I bought a new tv box with android 11, in this version we haven't permission to access android/data/ folders, I know one way using some file managers apks to see this files but I can't because need a native file manager to provider this permission. My sugestion is one way to upload this file using burst addoon direct. Or if someone knows another option to privide this let me know please, unfortunatly this box isn't avalible to root yet, I m using a A95x F4 with android 11.

**Comment by elgatito** [comment]
With version 0.0.77 there is now a new setting in Burst settings where you can point to a folder where you have `overrides.json` files saved, so it can be an sdcard.
