### ISSUE TITLE
[Request] GloTorrents/RARBG/Kickass providers updates

### ISSUE THREAD

**Issue by burekas7** [elgatito/script.elementum.burst#309]
Hi,

The current GloTorrents url is no longer working (https://www.gtdb.to)

There is a new option instead:
http://glodls.to

It seems that the search pattern remain the same, so only url changing is required.

Thanks.

**Comment by antonsoroko** [comment]
@burekas7 
Hi. You can create PR (change request) easily by yourself, just click edit on this file - https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json
and do the change.

(Although I can't say when it will be merged by author. But "action" has more chances than "ask".)

**Comment by burekas7** [comment]
@antonsoroko 
@elgatito 

That's right.
So I open three PRs regarding these providers:
* GloTorrents: https://github.com/elgatito/script.elementum.burst/pull/310
* RARBG: https://github.com/elgatito/script.elementum.burst/pull/311
* Kickass: https://github.com/elgatito/script.elementum.burst/pull/312

Thanks.

**Comment by elgatito** [comment]
I have merged PRs, so closing this one.
