### ISSUE TITLE
Burst fails to find 2160p (4k) torrents, although the provides do have them 

### ISSUE THREAD

**Issue by pitsi** [elgatito/script.elementum.burst#316]
## Preface
The following is a request of a friend who uses firestick 4k. I have neither the bandwidth nor the hardware to play 4k video. 
Also, the issue report follows elementum's guide of issue reporting.

## Expected Behavior
Burst should find 4k torrents that have 2160p in their name.

## Current Behavior
Burst simply ignores 2160p torrents, probably because "4k" is not part of their name. The same may apply for 2k too. However, it does return results for 1080p and lower resolutions with no problem.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Make sure you have 4k resolution enabled in burst's settings (settings for elementum burst provider > resolutions > 4k > ticked)
2. Make sure you have enabled a tracker that has 4k content for movies and/or series. I don't know if I can mention one, but the one whose api listens to torrentapi.org does have such movies and series.
3. Search or find a movie that is available in 2160p/4k through trakt lists, eg the latest spiderman movie under trakt > trending.
4. Notice that there is no results for 2160p/4k, although there are results for lower resolutions.
5. Open a web browser, visit the forementioned tracker, search for the movie again and notice that 2160p/4k torrents do exist in the results.

## Context
I want burst to provide 2160p/4k content for elementum :)
Or at least see if anyone else faces the same issue.

## Your Environment
* Version used: Burst 0.0.71 and elementum 0.1.86
* Environment name and version: Kodi 18.9 (libreelec) and 19.4 
* Operating System and version: Libreelec 9.2.6 x64 (for kodi 18.9), debian testing/unstable x64 and fireos 7 on the firestick (for kodi 19.4). 
* Link to Kodi debug log: No log. Screenshot (with the search results) only upon request.

**Comment by antonsoroko** [comment]
this is weird. probably some issue with trackers/torrent files, rather than with burst.
i do have 4k results.

also you can see burst support 4k filtering (actually it supports it from the beginning  - 5 years ago):
https://github.com/elgatito/script.elementum.burst/blob/10ea0b5168eefff71243cfbb79426cf02e1afd21/burst/filtering.py#L87

check names of "your" torrents against these patterns. maybe "your" torrents use some non-standard naming convention.

**Comment by pitsi** [comment]
What do you mean by "names of your torrents"? When I search for a movie, the only thing that is search is probably the name, e.g. "spiderman no way home", which should return results that contain 720p, 1080p, and 2160p in their names. Why would I add the resolution as a search parameter? 
This limits, if not breaks, the results. I just searched for "spider-man: no way home 2160p" (notice the dash and the dots before "no") and it got 0 results for matching movies.

**Comment by pitsi** [comment]
I agree with the first part. However, the torrent name from that specific provider clearly states the resolution, at least for movies.

For the second part, I am now waiting for my friend to check the forementioned setting in his firestick 4k and reply. I had mine set to 20gb, which is fair considering I rarely go for 1080p, because as I said I do not have the bandwidth to download such data volumes in reasonable time.
