### ISSUE TITLE
rarbg returns results only when searching for show

### ISSUE THREAD

**Issue by georgew21** [elgatito/script.elementum.burst#318]
Hello, for some reason when burst searches for movies with rarbg , it doesn't take result (although checking search url with browser it returns results)

Currently, burst get results only when searching for tv show.

Any idea about this weird problem?

**Comment by antonsoroko** [comment]
rarbg has rate limit so you can hit it if you do searches without delay  , especially if you use shared IP address like VPN.

also check elementum's logs to see if there are any error - it might help you to find issue. you can find log location and how to enable debug level here http://elementum.surge.sh/contribute/log/

also you can increase level of logging in burst as well, so you will also see result of searches (answer of rarbg server) in log.

**Comment by elgatito** [comment]
Closing as Rarbg is closed.
