### ISSUE TITLE
Проблема с rutracker

### ISSUE THREAD

**Issue by Insomniac412** [elgatito/script.elementum.burst#319]
При поиске пишет: "rutracker работает медленно" . Что это может быть, подскажите пожалуйста, настроек не менял, раньше все работало, другие провайдеры, в том числе заблокированные, работают. На компьютере в rutracker заходит под этим же логином и пассом

**Comment by Virusmater** [comment]
почему-то в плагине используется домен .nl:
https://github.com/elgatito/script.elementum.burst/blob/f66d4dd1cd4da968f8e2233e0189b6920be9bacf/burst/providers/providers.json#L1722
и данное зеркало не работает больше

**Comment by Virusmater** [comment]
Пропиши правильный домен и все будет работать:
![image](https://user-images.githubusercontent.com/99446/179324516-0a7ee99c-9b68-4b49-8ca7-f7c3c64f9d91.png)

**Comment by antonsoroko** [comment]
В их Вики это зеркало ещё значится, но у меня тоже не открылось.
https://rutracker.wiki/%D0%A7%D1%82%D0%BE_%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C,_%D0%B5%D1%81%D0%BB%D0%B8_%D0%B2%D0%B0%D0%BC_%D0%B7%D0%B0%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF_%D0%BD%D0%B0_rutracker.org#.D0.97.D0.B5.D1.80.D0.BA.D0.B0.D0.BB.D0.B0_rutracker.org

**Comment by elgatito** [comment]
Closing as rutracker is working in latest version.
