### ISSUE TITLE
Help with Nyaa

### ISSUE THREAD

**Issue by Bostox** [elgatito/script.elementum.burst#320]
Can Someone help me with nyaa search it gives lots of unwanted results when looking for anime

**Comment by antonsoroko** [comment]
Hi. You can try to fix it by yourself (I would not expect that someone else will do this).

See https://github.com/elgatito/script.elementum.burst#adding--editing-providers
and then you need to make search better here - https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json#L1509-L1514

If you will be able to figure out correct queries - then you can make a Pull Request here.

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.
