### ISSUE TITLE
Issues with providers Torrent9.cm and Cpasbien.si

### ISSUE THREAD

**Issue by Micmike74** [elgatito/script.elementum.burst#325]
Hello, I can't get Torrent9 and Cpasbien to work. Yggtorrent, 1337x, rarbg, yts and others are working perfectly fine though...
I have added the new up-to-date URL addresses of these two websites, namely Torrent9.cm and Cpasbien.si, to the "Domain alias" field.

Could you tell me if I did the right thing and if these sites are working on your end? Anyway, a big thank you for all the work already done and updated on Burst!

Thank you and have a good day !

**Comment by Micmike74** [comment]
Hello! I would be very grateful if someone could tell me if Torrent9 and Cpasbien providers are working on their side? These two  are the last ones offering French content. 

Thank you very much! Have a good day !

**Comment by antonsoroko** [comment]
@Micmike74 see my PR. you can make those changes locally for now.

torrent9 works now (they changed query format).
cpasbien (they also changed queries format) will work if they return magnet link to pages (looks like they had it before, like torrent9 still has). you can contact them.

**Comment by Micmike74** [comment]
Hello Anton, and thank you very much the time to help me. I modified the providers.json file (via Notepad) as indicated in your PR, unfortunately still nothing, I still don't have any result in the torrent list for Torrent9. :'s 
Is it normal that it works on your side and not on mine?

**Comment by antonsoroko** [comment]
@Micmike74 hi.
1. if you can open torrent9 web site from the same device via browser (or at least from same network, like from your PC) - then it should work. If you can not open - try to use VPN.
2. I used "search" in elementum's main menu - it worked for single word "murina" (i just took first word i saw on the web site).
3. but now i tried to use "search" in "movies" menu, and i see that if title has spaces (like new avatar) then it does not work, since they also changed separator (from `-` to `%20`), i updated my PR, see https://github.com/elgatito/script.elementum.burst/pull/326/commits , works for me at least.

**Comment by Micmike74** [comment]
Hi! Thank you very much for your quick response. I haven't tested the new separators for torrent9 yet (very busy week). I'll check it out this weekend and get back to you! Thanks and have a great day!

**Comment by Micmike74** [comment]
Hello! That's it Torrent9 works! Many thanks to you Anton! I had trouble making the edits on the Json. Kodi didn't want to incorporate the changes or the files didn't play... But I succeeded by starting from your file and recreating a Zip and then redoing a clean installation. Indeed, just the update didn't work.
Anyway now it works for Torrent9 so thank you! Wishing you a pleasant day!

**Comment by antonsoroko** [comment]
@Micmike74 Nice. about cpasbien:

>cpasbien (they also changed queries format) will work if they return magnet link to pages (looks like they had it before, like torrent9 still has). 

if you want it to work too - you can try to contact them and ask to add "magnet" links to pages.
