### ISSUE TITLE
bitsearch.to provider

### ISSUE THREAD

**Issue by ibrahim8383** [elgatito/script.elementum.burst#329]
please add this site https://bitsearch.to/

**Comment by antonsoroko** [comment]
@ibrahim8383 hi. you can try to add it by yourself by following guide here https://github.com/elgatito/script.elementum.burst/blob/master/README.md#adding--editing-providers
and by reading examples here https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json
and then you can send a PR via github UI.
this probably would be the fastest way to get it done :-)

**Comment by ibrahim8383** [comment]
@antonsoroko here is the provider i add but i get no links were found from elementum what is wrong?

{
    "bitsearch": {
        "anime_extra": "",
        "anime_keywords": "{title} {episode}",
        "anime_query": "EXTRA",
        "base_url": "https://bitsearch.to/search?q=QUERY",
        "color": "FFF14E13",
        "general_extra": "",
        "general_keywords": "{title}",
        "general_query": "EXTRA",
        "language": null,
        "login_failed": "",
        "login_object": "",
        "login_path": null,
        "movie_extra": "",
        "movie_keywords": "{title} {year}",
        "movie_query": "EXTRA",
        "name": "bitsearch",
        "parser": {
            "infohash": "",
            "name": "item('a', order=2)",
            "peers": "item(tag='td', order=3)",
            "row": "find_once(tag='body').find_all('tr')",
            "seeds": "item(tag='td', order=2)",
            "size": "item(tag='td', order=5)",
            "torrent": "item(tag='a', attribute='href', order=2)"
        },
        "private": false,
        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title} Season {season:2}",
        "season_keywords2": "{title} Season{season}",
        "season_query": "EXTRA",
        "separator": "+",
        "show_query": "",
        "subpage": true,
        "tv_extra": "",
        "tv_extra2": "",
        "tv_keywords": "{title} s{season:2}e{episode:2}",
        "tv_keywords2": "",
        "tv_keywords3": "",
        "tv_keywords_fallback": "",
        "tv_keywords_fallback2": ""
    }
}

**Comment by antonsoroko** [comment]
@ibrahim8383 
1. enable debug logging in elementum to see what it sends to burst (how query/URL looks like in the end) - see guide here http://elementum.surge.sh/contribute/log/
2. also enable debug logging in burst settings to see how burst parses HTML pages based on your parsing rules. see https://github.com/elgatito/script.elementum.burst/blob/e70aa218be55241462e8574c43e0f40740e1f764/resources/language/messages.pot#L163
3. you need to write correct `"parser": {` rules to get "row" (each line with torrents), "name", torrent file link and etc. as i can see they do not use tables (`tr`/`td` html tags) but uses a lot of `div` tags, so i guess your code is a copy-paste from other provider. I am not a HTML expert, but i can suggest you to use "dev panel" in browser, then highlight target item and then use "copy"->"copy as selector" to see "path" to item. then convert this path to internal "selection" language. there is not much documentation about this language, i found only https://quasar-burst.readthedocs.io/en/latest/adding_providers.html#parser and comments in code, like https://github.com/elgatito/script.elementum.burst/blob/master/burst/parser/ehp.py#L108
I guess you need to look at different examples (parsing of `div` based pages), like https://github.com/elgatito/script.elementum.burst/blob/e70aa218be55241462e8574c43e0f40740e1f764/burst/providers/providers.json#L2426-L2432

**Comment by naveen1hot** [comment]
@ibrahim8383 any success on this??
I also tried for this. But not working..

**Comment by antonsoroko** [comment]
@ibrahim8383 @naveen1hot
I had to be quite creative with parsing, but I was able to make it work. You can try to make changes locally and test how it works for you (so you can provide some feedback earlier) or wait for new release of burst.

**Comment by naveen1hot** [comment]
Kudos!!!! Great thanks for your response and help @antonsoroko...

**Comment by naveen1hot** [comment]
Hello @antonsoroko i am getting the results but failed at resolving links(not playing). sorry to trouble you. just i want to share the status of your commit. thanks..

**Comment by antonsoroko** [comment]
@naveen1hot strange, it works for me.

1. I would need a full log file with debug enabled in elementum and kodi from yuo.
See http://elementum.surge.sh/contribute/log/ for a guide.

2. On a side note, for torrent files bitsearch uses `iTorrents.org is a free service for caching torrent files online.` and as I can see that sometimes it give us timeout when we try to download torrent file, so you need to try again.
Does this issue happen all the time for you? If only sometimes - this is not a burst issue.

**Comment by elgatito** [comment]
@antonsoroko Itorrents.org is behind Cloudflare defence, so it can work in one case, and not the other.

**Comment by antonsoroko** [comment]
I just tried to use magnets instead of files, but it does not work for me, never resolve. So I guess we will stick with files and users have click twice if needed.

**Comment by naveen1hot** [comment]
Thanks @antonsoroko.. seems bitsearch no longer need for now. As we have torrentz..
