### ISSUE TITLE
Problem with choosing a stream for a season

### ISSUE THREAD

**Issue by Victor053** [elgatito/script.elementum.burst#330]
I realized that when I choose a stream for the season elementum burst searches (show title)+ season. When searching like that there are no links found on my provider I need it to search for example the last of us s01 not the last of us season 1

**Comment by froggz19** [comment]
I have a weird issue. It only gets/sets the username and passkey only on first attempt. For the next attempts it says "Reusing previous login" but 'username' and 'password' are empty and of course no results are returned.

**Comment by Victor053** [comment]
> @Victor053 you need to edit configuration of your provider, like this
> 
> https://github.com/elgatito/script.elementum.burst/blob/e70aa218be55241462e8574c43e0f40740e1f764/burst/providers/providers.json#L2069-L2071
> 
> 
> 
> where `season_keywords/2/3/4` will be used for search in parallel (thus only very common keywords should be used, to avoid useless load) and if nothing found - then `season_keywords_fallback/2/3/4` will be used, one by one, until first success (so you can put here some rare cases).
> 
> 
> 
> Then you can make a PR for your provided here in github.
I looked at the providers file and I use file list and according to what it says there results for seasons should be popping up but they don't

**Comment by Victor053** [comment]
> @Victor053 you need to edit configuration of your provider, like this
> 
> https://github.com/elgatito/script.elementum.burst/blob/e70aa218be55241462e8574c43e0f40740e1f764/burst/providers/providers.json#L2069-L2071
> 
> 
> 
> where `season_keywords/2/3/4` will be used for search in parallel (thus only very common keywords should be used, to avoid useless load) and if nothing found - then `season_keywords_fallback/2/3/4` will be used, one by one, until first success (so you can put here some rare cases).
> 
> 
> 
> Then you can make a PR for your provided here in github.

I took a look at the providers.json and my provider should use season_keywords2 to find the season but instead it uses season_keywords and I think that's why it can't find anything

**Comment by Victor053** [comment]
> @Victor053 you need to edit configuration of your provider, like this
> 
> https://github.com/elgatito/script.elementum.burst/blob/e70aa218be55241462e8574c43e0f40740e1f764/burst/providers/providers.json#L2069-L2071
> 
> 
> 
> where `season_keywords/2/3/4` will be used for search in parallel (thus only very common keywords should be used, to avoid useless load) and if nothing found - then `season_keywords_fallback/2/3/4` will be used, one by one, until first success (so you can put here some rare cases).
> 
> 
> 
> Then you can make a PR for your provided here in github.

Never mind I edited the provider and fixed it you said I can do a PR. How can I do that?

**Comment by antonsoroko** [comment]
@Victor053 the easiest way is to open https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json and click "edit" (pencil icon), then make your changes, then click "commit changes" and then github UI will guide you through the process. 

alternatively, search for "github how to create pull request" in any search engine.

**Comment by antonsoroko** [comment]
while making changes remember my notes about how `season_keywords/2/3/4` and `season_keywords_fallback/2/3/4` are used. most likely you need to add or edit "search expressions", but not delete.

**Comment by elgatito** [comment]
Closing this issue. I think it was answered by @antonsoroko .
