### ISSUE TITLE
itorrent.ws search problem

### ISSUE THREAD

**Issue by Beladeep** [elgatito/script.elementum.burst#332]
Dear developer

Thank you very much for your wonderful work.
Unfortunately, when using the itorrent provider, I do not get any search results.
Could you please check what the problem might be?

The search works from a browser:
https://itorrent.ws/

Thx

**Comment by antonsoroko** [comment]
@Beladeep #337 should fix this. at least it worked for me during tests.

**Comment by Beladeep** [comment]
Dear Antonsoroko
Thank you very much for the quick fix. It works perfectly.
♥

**Comment by tibikepc** [comment]
> Dear Antonsoroko Thank you very much for the quick fix. It works perfectly. ♥

Szia,nekem nem tölt be semmit az itorrent.ws-röl, mi lehet a gond ?

**Comment by Beladeep** [comment]
> > Dear Antonsoroko Thank you very much for the quick fix. It works perfectly. ♥
> 
> Szia,nekem nem tölt be semmit az itorrent.ws-röl, mi lehet a gond ?

Szia
Az itorrent kereső működik, most próbáltam az előbb.
Telepítsd fel ezt:
[script.elementum.burst-0.0.74.zip](https://github.com/elgatito/script.elementum.burst/files/12011423/script.elementum.burst-0.0.74.zip)

**Comment by tibikepc** [comment]
Oké,így már nekem is működik,köszönöm a segítséget.

**Comment by antonsoroko** [comment]
@Beladeep @tibikepc now you can update to official version [0.0.75](https://github.com/elgatito/script.elementum.burst/releases/tag/v0.0.75) from the repo.

**Comment by Beladeep** [comment]
> @Beladeep @tibikepc now you can update to official version [0.0.75](https://github.com/elgatito/script.elementum.burst/releases/tag/v0.0.75) from the repo.

Dear @antonsoroko 
Here is the official Itorrent logo:
![ITorrent](https://github.com/elgatito/script.elementum.burst/assets/132296655/ee55bf5f-7d0d-41aa-af63-f217c0b36fc5)

Please add this to the next update.
Thx

**Comment by antonsoroko** [comment]
@Beladeep done. btw, in future you can do it by yourself, here in github web ui:
fork repo (in top panel)
navigate to "burst/providers/icons/" directory in your fork
click upload file
file name must be the same as torrent tracker name in `burst/providers/providers.json` file
choose to create a new branch instead of master branch
then create a PR (but not to your fork, to this original repo).
