### ISSUE TITLE
[Update] limetorrents.info changed to https://www.limetorrents.lol

### ISSUE THREAD

**Issue by SubEdict** [elgatito/script.elementum.burst#340]
New https://www.limetorrents.lol works great.

**Comment by antonsoroko** [comment]
@SubEdict hi. for simple fix like this you can make change (a PR) right here in GitHub web ui:
Just open
https://github.com/elgatito/script.elementum.burst/blob/5132cdf7f8cad1ff65ac94a5101f26941e6c1717/burst/providers/providers.json#L1194
Click edit, make the change, create PR.

**Comment by SubEdict** [comment]
> Click edit, make the change, create PR.

Didn't know I can. First time... Did I do it right?

**Comment by antonsoroko** [comment]
@SubEdict yes. just change "Update providers.json" to something meaningful, like "Update limetorrents URL".

**Comment by SubEdict** [comment]
Great, you learn something new every day, even while watching TV. 🤣 

Saw you also already worked on Torlock fix, Thanks

**Comment by SubEdict** [comment]
v0.0.76: All good!
Thanks, @antonsoroko
