### ISSUE TITLE
Providers with problematic search query that doesn't fetch results

### ISSUE THREAD

**Issue by SubEdict** [elgatito/script.elementum.burst#341]
These providers work fine on their site (browser) but returned 0 results in Burst more than a year+ now:

https://www.torrentfunk.com
https://idope.se
https://torlock.com #237 **Current default: https://torlock2.com is worse, look like the site been block sometimes (Malware?).

All other main provider works great, so this is mostly FYI, _but_ will be great to see them fixed at some point. :)

**Comment by SubEdict** [comment]
Yeah, I know, but they are good back up when other (especially TGx) return "Time out", I'm guessing too many request after a couple of episodes.  Usually only eztv, TGx and sometime TPB uses different hosts or sources.

**Comment by elgatito** [comment]
Should be solved by version 0.0.76.

**Comment by SubEdict** [comment]
Wonderful result. **All** but idope (not really needed) **works great**.
New ExtraNet also crazy good.

Thanks to both of you guys. 🥇

**Comment by elgatito** [comment]
@SubEdict all the credits should go to @antonsoroko . I'm just clicking buttons.

**Comment by SubEdict** [comment]
Billions thanks to @antonsoroko of course.
That was crazy fast fixes, like a real py cowboy. 💯
