### ISSUE TITLE
How to enabed torrentz2 provider?

### ISSUE THREAD

**Issue by naveen1hot** [elgatito/script.elementum.burst#352]
i have changed enabled status as true. but still its not showing in burst?
kindly help!!! all the false also i put as true but no help.. pls suggest on how to enable the provider.
`"torrentz": {
        "anime_keywords": "{title} s{season:2}e{episode:2}",
        "anime_keywords2": "{title} {season:2}x01|S{season:2}",
        "anime_keywords_fallback": "{title} s{season:2}",
        "anime_query": "",
        "base_url": "https://torrentz2.nz/search?f=QUERYEXTRA",
        "color": "FFFFB090",
        "enabled": true,
        "filter_title": true,
        "general_extra": "",
        "general_keywords": "{title}",
        "general_query": "",
        "language": null,
        "languages": "en",
        "login_failed": "",
        "login_object": "",
        "login_path": null,
        "movie_extra": "",
        "movie_keywords": "{title} {year}",
        "movie_query": "",
        "name": "TorrentZ",
        "parser": {
            "infohash": "item(tag='a', attribute='href', divider=('/', 1))",
            "name": "item('a')",
            "peers": "item(tag='span', order=5)",
            "row": "find_once('div', ('class', 'results')).find_all('dl')",
            "seeds": "item(tag='span', order=4)",
            "size": "item(tag='span', order=3)",
            "torrent": "'magnet:?xt=urn:btih:%s' % item(tag='a', attribute='href', divider=('/', 1))"
        },
        "predefined": false,
        "private": false,
        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title} season {season:2}",
        "season_keywords2": "{title} s{season:2}",
        "season_query": "",
        "separator": "%20",
        "show_query": "",
        "subpage": false,
        "tv_extra": "",
        "tv_extra2": "",
        "tv_keywords": "{title} s{season:2}e{episode:2}",
        "tv_keywords2": "{title} {season:2}x01|S{season:2}",
        "tv_keywords_fallback": "{title} s{season:2}"
    },`

**Comment by antonsoroko** [comment]
@naveen1hot 
If you do development (you cloned git repo), then easy - run https://github.com/elgatito/script.elementum.burst/blob/master/scripts/generate_settings.py inside your repo (`python 3 scripts/generate_settings.py`).

If you do local changes - then manually copy/paste/edit settings lines for provider in your local https://github.com/elgatito/script.elementum.burst/blob/master/resources/settings.xml file (`resources/settings.xml`).

Although, it was disabled for a reason. You would need to fix it to use it.

**Comment by naveen1hot** [comment]
I hello @antonsoroko .. thanks for your quick response.. I tried same. But it's not appearing in elementum burst..

**Comment by antonsoroko** [comment]
You tried what exactly? You need to change providers.json and settings.xml and you need to check that you did changes in xml file correctly.

**Comment by naveen1hot** [comment]
Thanks a lot @antonsoroko. With your guidance i am able to enabled torrentz and its appear in burst also..
as you said it has some problem.
but while checked with new domain (https://torrentz2.nz/) its working fine. but not showing the results. could you pls check it if  possible.
![image](https://github.com/elgatito/script.elementum.burst/assets/67212860/99b7c431-dbee-45d2-91c5-9c1f6baea0be)

**Comment by antonsoroko** [comment]
@naveen1hot i added it, but i am disapointed. open any link, scroll down to bottom and you will see that this torrentz2 is just a different UI for bitserach #351.
Also it uses "bad" numbers for seeds/peers, like `1.2K` so very popular torrents will be skipped b/c of this wrong format.

**Comment by naveen1hot** [comment]
Thanks greatful for you efforts and response.  It's working now.. yeah seems it's replication of bitsearch. But torrentz working very well for me. Thanks so much @antonsoroko ...
