### ISSUE TITLE
Add torrenting.com provider

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/script.elementum.burst#359]
Hey,
Is that possible?

Thanks.

**Comment by antonsoroko** [comment]
It has Captcha on login. Thus - no.
On the side note: i have the account there - imho this tracker is kind of useless. From my experience: very rarely it has releases that torrentgalaxy does not have, but almost always it does not have releases that are available on torrentgalaxy.

**Comment by ShlomiD83** [comment]
OK, thanks @antonsoroko
