### ISSUE TITLE
Adding MVGroup.org

### ISSUE THREAD

**Issue by Sandbird** [elgatito/script.elementum.burst#36]
I am trying to create a custom provider for the private forum/tracker forums.mvgroup.org which has tons of documentaries, and although i managed to load the tracker in the settings...Its always returning 0 results, not to mention that the logs say **Login successful** even though i am purposely putting a wrong password to beta test it.
I dont know why its failing, i am pretty sure everything within the parser is correct.
Here is my parser:

```
{
	"mvgroup": {
	    "anime_extra": "",
	    "anime_keywords": "",
	    "anime_query": "",
	    "base_url": "http://forums.mvgroup.org/forumtracker.php?filter=QUERY",
	    "color": "FF4976B0",
	    "general_extra": "",
	    "general_keywords": "{title}",
	    "general_query": "",
	    "language": null,
	    "login_failed": "Login Failed!",
	    "login_object": "{'UserName': USERNAME, 'PassWord': PASSWORD}",
	    "login_path": "/index.php?act=Login&CODE=00",
	    "movie_extra": "",
	    "movie_keywords": "",
	    "movie_query": "",
	    "name": "MVGroup",
	    "parser": {
	        "infohash": "",
	        "row": "find_once('table', ('id', 'torrentlist')).find_all('tr')",
	        "name": "item(tag='a', order=4)",
	        "peers": "item(tag='td', order=5)",
	        "seeds": "item(tag='td', order=4)",
	        "size": "",
	        "torrent": "item(tag='a', attribute='href', order=1)"
	    },
	    "private": true,
	    "season_extra": "",
	    "season_extra2": "",
	    "season_keywords": "",
	    "season_keywords2": "",
	    "season_query": "",
	    "separator": "+",
	    "show_query": "",
	    "subpage": false,
	    "tv_extra": "",
	    "tv_extra2": "",
	    "tv_keywords": "",
	    "tv_keywords2": ""
	}
}
```
In order for the tracker to show up I had to add this line inside the Private section of the settings.xml file located at: \Kodi\addons\script.quasar.burst\resources\settings.xml

```
    <setting label="MVGroup" id="use_mvgroup" type="bool" default="false" />
      <setting id="mvgroup_username" label="32015" type="text" default="" subsetting="true" visible="eq(-1,true)" />
      <setting id="mvgroup_password" label="32016" type="text" default="" option="hidden" subsetting="true" visible="eq(-2,true)" />
```
Anyone knows what am i doing wrong here?
Thanks

**Comment by elgatito** [comment]
> In order for the tracker to show up I had to add this line inside the Private section of the settings.xml file located at: \Kodi\addons\script.quasar.burst\resources\settings.xml

It will be removed from `settings.xml` after Burst update. Custom providers don't show up in Kodi settings, because Kodi settings is not a dynamic thing, it's static (sadly).

It's easier to add your providers to Burst globally.
If you want to - you can send me login/pass (can be done with mail or gitter or whatever) so I can login and compose provider settings.

**Comment by elgatito** [comment]
MVGroup will be available in the next version.
There is a check for too-big torrent files. And on mvgroup many torrents are more than 100gb, so they can be filtered.
