### ISSUE TITLE
search not initiated after updating to 0.0.80

### ISSUE THREAD

**Issue by ShlomiD83** [elgatito/script.elementum.burst#367]
Hi @elgatito 
After updating to 0.0.80 search isn't initiated at all, it just hangs until a timeout.
Checked on Windows x64, Kodi 20.2.
https://gist.github.com/ShlomiD83/9f6fa719cc5df7752a77643ee117faef

**Comment by antonsoroko** [comment]
looks like this line
https://github.com/elgatito/script.elementum.burst/commit/b61e2a87ff8884af96e26a84ca30d6e0dce0a858#diff-11beb51e5598d394e3dfcdd282f505fb089203176e38f3ca50b08e2ff5f4e81fR13

causes inability to launch burst from elementum.

**Comment by elgatito** [comment]
@ShlomiD83 Should have been testing it better. 

Try with 0.0.81.

**Comment by ShlomiD83** [comment]
thank you @elgatito & @antonsoroko, it seems to work as expected now.
