### ISSUE TITLE
Filelist.io not working

### ISSUE THREAD

**Issue by tibikepc** [elgatito/script.elementum.burst#378]
Hello filelist.io provider not working in elementum,but the website work perfect.

**Comment by antonsoroko** [comment]
@tibikepc this is private tracker and registration is closed, so i do not have access to it.

so you either need to share your credentials or do debugging by yourself:

enable "Log debug messages for parsing" in burst settings and see kodi.log
also see search URLs and parsing rules here https://github.com/elgatito/script.elementum.burst/blob/ecd7b3c1e33a40960cf20a80c9eb798b511ea253/burst/providers/providers.json#L680

**Comment by antonsoroko** [comment]
@tibikepc looks like they opened registration but an "invitation code" is needed:
```
Eroare
Accesul la acest site se poate face numai pe baza unei invitatii.
```

so again: either fix it by yourself or provide an "invitation code".

**Comment by antonsoroko** [comment]
@tibikepc if you do not plan to fix the json code by yourself and do not plan to provide credentials - then just close the issue.

**Comment by tibikepc** [comment]
I can't send you an invitation,
Where can i send in privat message,provide credentials?

**Comment by antonsoroko** [comment]
@tibikepc there is email in my github profile page. sent it there.
**also**, as you can see here https://github.com/elgatito/script.elementum.burst/blob/ecd7b3c1e33a40960cf20a80c9eb798b511ea253/burst/providers/providers.json#L699
i do **not** need your password, i need only username and `passkey` for API.

**Comment by antonsoroko** [comment]
@tibikepc bro, i am confused :-D

![image](https://github.com/elgatito/script.elementum.burst/assets/17964763/c21689ea-330c-4974-adce-d55708a9c812)

it works for me, i tested on "flash 2023" movie.

same for tv show
![image](https://github.com/elgatito/script.elementum.burst/assets/17964763/185d3c60-264a-4aca-ba35-a11a6a043b9b)

**Comment by tibikepc** [comment]
A friend of mine said,the filelist working on kodi Leila version,but in New kodi no buffering.

**Comment by antonsoroko** [comment]
@tibikepc 

1. tried same torrent as on your screenshot - it does not work for me in both **qbittorrent** and elementum.
it does not look as elementum issue.

then i tried to connect to romanian VPN - only qbittorrent worked.

**looks like Filelist is blocking some clients.**
i see this in their tracker response :
`d14:failure reason36:Your client is not on the whitelist!12:min intervali5400e8:intervali5400ee`

**you need to read their Help/FAQ/etc and tell use which torrent clients are allowed so then we pretend as those clients.** there is a setting in elementum to do so (see end of bittorrent tab), but you need to know which client is allowed.

**if you will not find any info about allowed clients - try all of then, start with "libtorrent (Rasterbar) 1.1.0".**

2. 
>I have disable the "use kodi language" season 1 not searching..

are you talking about Filelist? b/c Filelist finds torrents for title "game of thrones" s01e01 for me.
if you are talking about different tracker - please write to different issue. maybe https://github.com/elgatito/plugin.video.elementum/issues/1026 ?

**Comment by tibikepc** [comment]
Thank you verry much! The filelist.io is working,I set the libtorrent Rasterbar 1.1.0 in elementum bittorent settings.

**Comment by antonsoroko** [comment]
@tibikepc can you please 
>you need to read their Help/FAQ/etc and tell us which torrent clients are allowed

Just curious what they allow, so we can update list.
