### ISSUE TITLE
YGGtorrent updates

### ISSUE THREAD

**Issue by Gregsr** [elgatito/script.elementum.burst#38]
YggTorrent adress has changed: https://yggtorrent.is
It seems that the site structure has changed too because, when I fill domain alias option in, no result is displayed. I have not error too.

Thanks

**Comment by lanzorg** [comment]
I hope rik91 won't be too long to provide us a new working release. ;)
The jackett project already updated YGG support:
https://github.com/Jackett/Jackett/commits/master

**Comment by Gregsr** [comment]
I hope too 😉
@rik91 ? 🙂

**Comment by rik91** [comment]
Yes, I'm going to watch this today ! ;-)

**Comment by rik91** [comment]
J'ai codé la mise a jour mais je l'ai pas encore pushé pour merge.
Mais vu qu'elgatito n'est pas très actif en ce moment, je sais pas combien ça peut prendre de temps pour avoir une nouvelle version.
Pour les plus pressé, il faut remplacer ce fichier : https://github.com/rik91/script.elementum.burst/blob/master/burst/providers/providers.json

**Comment by lanzorg** [comment]
Merci beaucoup, rik91. ;)
Il y a juste un problème lors de la sélection d'une saison pour une série, il n'y a pas de résultat.
Je ne sais pas si cela est un bug ou une régression suite à la mise à jour du site.

**Comment by rik91** [comment]
Ah yes j'ai pas testé cette partie. 
Je vais regarder !

**Comment by Gregsr** [comment]
- Lorsque je fais une recherche générale par ex sur "shameless saison 5", je n'ai pas de résultat or il en existe un. De plus, dans le .log le lien de recherche est le bon https://yggtorrent.is/engine/search?do=search&name=shameless+saison+5&category=2145

- Pour la recherche d'un flux d'une saison complète dans le menu série, il y a une erreur de elementum
voici ce que j'ai dans mon .log
19:10:15.758 T:18446744072353868488  NOTICE: [plugin.video.elementum] Python version: ['2.7.12 (default, Nov 14 2017, 17:15:35) ', '[GCC 4.9.x 20150123 (prerelease)]']
                                                dist: ('', '', '')
                                                linux_distribution: ('', '', '')
                                                system: Linux
                                                machine: aarch64
                                                platform: Could not detect
                                                uname: ('Linux', 'localhost', '3.14.29', '#1 SMP PREEMPT Thu Jun 29 15:20:54 CST 2017', 'aarch64', '')
                                                version: #1 SMP PREEMPT Thu Jun 29 15:20:54 CST 2017
                                                mac_ver: ('', ('', '', ''), '')
19:10:15.868 T:18446744072314037512  NOTICE: [plugin.video.elementum] [GIN] 2018/04/07 - 17:10:15 | 404 |           2µs |       127.0.0.1 | GET      /show/34307/season/5/play
19:10:15.873 T:18446744072353868488   ERROR: [plugin.video.elementum] Traceback (most recent call last):
19:10:15.873 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 185, in run
19:10:15.874 T:18446744072353868488   ERROR: [plugin.video.elementum]     data = _json(url)
19:10:15.874 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 128, in _json
19:10:15.874 T:18446744072353868488   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
19:10:15.875 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
19:10:15.875 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
19:10:15.875 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
19:10:15.876 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
19:10:15.876 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
19:10:15.876 T:18446744072353868488   ERROR: [plugin.video.elementum]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
19:10:15.876 T:18446744072353868488   ERROR: [plugin.video.elementum] HTTPError: HTTP Error 404: Not Found
19:10:15.877 T:18446744072353868488   ERROR: [plugin.video.elementum]
19:10:16.045 T:18446744072288890848   ERROR: PlayMedia could not play media: plugin://plugin.video.elementum/show/34307/season/5/play

Merci pour ton aide

**Comment by elgatito** [comment]
Please, in english, if you want some help here.

**Comment by Gregsr** [comment]
With the file modified by rik91, I have 2 problems:
- when I do a general search for example with "shameless saison 5", I have no result but there is one on the tracker. Moreover, in the .log the search link is correct https://yggtorrent.is/engine/search?do=search&name=shameless+saison+5&category=2145
- For stream search of a complete season in the tv shows menu there is an error of elementum. Here is what I have in my .log

19:10:15.758 T:18446744072353868488 NOTICE: [plugin.video.elementum] Python version: ['2.7.12 (default, Nov 14 2017, 17:15:35) ', '[GCC 4.9.x 20150123 (prerelease)]']
dist: ('', '', '')
linux_distribution: ('', '', '')
system: Linux
machine: aarch64
platform: Could not detect
uname: ('Linux', 'localhost', '3.14.29', '#1 SMP PREEMPT Thu Jun 29 15:20:54 CST 2017', 'aarch64', '')
version: #1 SMP PREEMPT Thu Jun 29 15:20:54 CST 2017
mac_ver: ('', ('', '', ''), '')
19:10:15.868 T:18446744072314037512 NOTICE: [plugin.video.elementum] [GIN] 2018/04/07 - 17:10:15 | 404 | 2µs | 127.0.0.1 | GET /show/34307/season/5/play
19:10:15.873 T:18446744072353868488 ERROR: [plugin.video.elementum] Traceback (most recent call last):
19:10:15.873 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 185, in run
19:10:15.874 T:18446744072353868488 ERROR: [plugin.video.elementum] data = _json(url)
19:10:15.874 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 128, in _json
19:10:15.874 T:18446744072353868488 ERROR: [plugin.video.elementum] with closing(urllib2.urlopen(url)) as response:
19:10:15.875 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 154, in urlopen
19:10:15.875 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 435, in open
19:10:15.875 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 548, in http_response
19:10:15.876 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 473, in error
19:10:15.876 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 407, in _call_chain
19:10:15.876 T:18446744072353868488 ERROR: [plugin.video.elementum] File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/urllib2.py", line 556, in http_error_default
19:10:15.876 T:18446744072353868488 ERROR: [plugin.video.elementum] HTTPError: HTTP Error 404: Not Found
19:10:15.877 T:18446744072353868488 ERROR: [plugin.video.elementum]
19:10:16.045 T:18446744072288890848 ERROR: PlayMedia could not play media: plugin://plugin.video.elementum/show/34307/season/5/play

Thanks for your help

**Comment by rik91** [comment]
Hi !

@Gregsr for your first point, it's because the only result have 0 seeder, elementum doesn't show results with 0 seeder.

For the second point (@lanzorg too), I have the same error, and I think it's a bug of Elementum.
It seem that it try to call an URL, and have a 404 error as we can see on the Gregsr's log.

@elgatito, can you confirm and see if you can do anything ?

**Comment by Gregsr** [comment]
@rik91 Ok, I understand because I hadn't checked option for displaying results without seeders. But when I tried with "shameless" or "derniers jedi", it didn't work too (no result). Unfortunately, I didn't save the .log. 
Now, I have an error "login failed" for yggtorrent and another about cloudhole.
I attach the .log.
[kodi.log](https://github.com/elgatito/script.elementum.burst/files/1891375/kodi.log)


Thanks for your help

**Comment by rik91** [comment]
It's strange, you have yggtorrent.com in your log and not yggtorrent.is

I think it's the problem because on the home page of the site, the team of ygg say they can't keep the redirect on the domain .com

**Comment by Gregsr** [comment]
@rik91 Indeed yesterday I used your link for your new json file and now I note it refers to "old" json file (with yggtorrent.com). That's my fault, I didn't check.

All is ok with your json file now.
Research problems come from ygg search engine e.g. no result with "shameless s05" and 2 results with"Shameless.US.S05". I suppose it will be a future optimization.

In json file, is it possible to use "&category=xxxx" and/or "&subcategory=xxxx" of ygg with movie_extra, anime_extra... ? Is it useful to perform research ?

Thanks

**Comment by rik91** [comment]
Ah yes I made some changes in my fork and I forgot to change the link in my previous post. 
Sorry... 
It's done

Yes, it's possible to do what you say.
It seems to me that in the old version of the site there was no subcategory.
If you think it's better, I can integrate that.

**Comment by Gregsr** [comment]
If it doesn't take too much time to integrate that, we can try to see if it's better :-)

**Comment by elgatito** [comment]
@rik91 , @Gregsr There is no error in the log. You should enable debug mode in Kodi, so we can see the full log file. Now there is nothing at all.

**Comment by rik91** [comment]
I open en new issue #41 because it's confused here ! :-)

**Comment by rossi29** [comment]
Bonjour a tous,
Quand je fait une recherche sur Elementum, il ne trouve rien sur le tracker yggtorrent. Y a t'il une mise a jour en attente ?
Merci a vous

**Comment by rik91** [comment]
Yes, une mise a jour va etre pusher prochainement pour corriger le problème.

Yes, an update will be pushed soon to correct the problem.

**Comment by rossi29** [comment]
Bonjour rik91,
Merci a toi pour l'info, elle sera a faire directement sur kodi ? ou faudra re-telecharger Elementum ?

**Comment by rossi29** [comment]
J'ai effectuer la mise a jour directement sur kodi et sa fonctionne bien, Yggtorrent apparais maintenant.
Merci encore.

**Comment by elgatito** [comment]
Is there something we can merge into burst regarding yggtorrent?

**Comment by rik91** [comment]
No I think you can close the issue !

**Comment by elgatito** [comment]
Okay, I'm closing the issue. 
If there's a need in changing providers - please, raise a PR.

**Comment by chicungunya** [comment]
Hi guys,
No results with YGG today. I put my login/password on elementum burst
I tried Venom
No result with Ygg

That's normal ? 

Thanks a lot
