### ISSUE TITLE
Search for anime titles

### ISSUE THREAD

**Issue by icarok99** [elgatito/script.elementum.burst#382]
title search of the anime should be made by Myanimelist why many people use the anime title from Myanimelist.

![Screenshot_2024-02-17-16-32-03-776_org xbmc kodi](https://github.com/elgatito/script.elementum.burst/assets/46580318/e0a15546-7c8b-4ab7-84da-67736d932014)

![IMG_20240217_163531](https://github.com/elgatito/script.elementum.burst/assets/46580318/01d3dbbd-3f87-4b19-b165-9f1eeac8b6b7)

![IMG_20240217_163401](https://github.com/elgatito/script.elementum.burst/assets/46580318/f6902e37-52a2-4922-bbc2-fcb20eba2511)

**Comment by antonsoroko** [comment]
but i think we can add an option that will set "original" to "jp". we already have an option to set "original" to "en".
https://github.com/elgatito/plugin.video.elementum/blob/214aab5f32bf2f8c553a37419e9f22a2760d11c0/resources/settings.xml#L288
https://github.com/elgatito/plugin.video.elementum/blob/214aab5f32bf2f8c553a37419e9f22a2760d11c0/resources/language/messages.pot#L1573

**Comment by antonsoroko** [comment]
@icarok99 and to answer your other question:

> Does it only recognize magnet link? I'm having a problem with a provider the link is to download the .torrent file

it is a bit hard to understand what you wrote, but i guess you meant if burst can find a link to `.torrent` file if you use provider with `"subpage": true`. it can, see:
https://github.com/elgatito/script.elementum.burst/blob/61c513a026262cc273dd97e894db65c93fe8677b/burst/burst.py#L546
https://github.com/elgatito/script.elementum.burst/blob/61c513a026262cc273dd97e894db65c93fe8677b/burst/burst.py#L566

burst finds magnet links, `.torrent` file links and many other links. see code for more details.

**Comment by icarok99** [comment]
@antonsoroko I was able to find the anime, I just had to add it to favorites and then change the name and use the title from Myanimelist. I used the context menu.

**Comment by antonsoroko** [comment]
@icarok99 i mean: i provided you the correct way to fix such issue - by editing providers.json and making a PR. up to you what way to use. 
i used nyaa - so i made changes for nyaa. you can make changes for other providers.

OR just wait, i think we will implement https://github.com/elgatito/plugin.video.elementum/issues/987 so no need to edit providers.json.
