### ISSUE TITLE
Version 0.0.84 is not working with older Elementum?

### ISSUE THREAD

**Issue by elgatito** [elgatito/script.elementum.burst#391]
There is a report that after updating Burst to 0.0.84 it is giving error and does not search anything.

**Comment by iz8mbw** [comment]
Yes, same issue. The behaviour is like 0 Provider are enabled.

**Comment by iz8mbw** [comment]
No errors in my case, simply like  0 Provider are enabled so not results are found.

**Comment by srdjantomic** [comment]
Also same issue, just got the message no providers enabled.

**Comment by Francesco980** [comment]
How long should we wait for them to solve this problem?

**Comment by jesterod** [comment]
same issue for me so i dropped back to 0.0.83 that one still works

**Comment by patkino** [comment]
+1
Doesn't work with elementum 0.1.99
Version 0.9.83 - ok

**Comment by elgatito** [comment]
Should be fixed with 0.0.85. 
Version 0.0.84 is now removed from releases.

**Comment by antonsoroko** [comment]
@elgatito 

>Have you checked Burst with older Elementum code? 

no. i checked with new version.
my mistake.
