### ISSUE TITLE
Yggtorrent stopped working since few days

### ISSUE THREAD

**Issue by hwk94** [elgatito/script.elementum.burst#400]
Hi,
Since few days I cannot fetch any result from this tracker.
I thought it was domain issue I add the right one on the domain alias option but still nothing.
I tried also to test the providers.json file to check what the line is doing 
https://www3.yggtorrent.wtf/engine/search?do=search&name=QUERYEXTRA&order=desc&sort=seed

There is redirection on my webrowser on the right url but empty result page.
So maybe the site has changed behaviour.
How to make this work?

Thank you in advance.

**Comment by antonsoroko** [comment]
@hwk94 yggtorrent uses CloudFlare anti-bot protection and burst is a bot. yggtorrent used to work last time i fixed it - https://github.com/elgatito/script.elementum.burst/pull/346 , but looks like nowadays burst always hits anti-bot protection page.
there is no solution at the moment.
see https://github.com/elgatito/script.elementum.burst/issues/240 for more details.

**Comment by FrelVick** [comment]
@hwk94 Had the same issue, after some debugging helped to update the provider alias to the newest one on .cool subdomain. Worked again

**Comment by hwk94** [comment]
Hello @FrelVick,
thank you for the info.

I tried on my side, even with updating alias on the burst parameter, it doesn't work.
Did you do someting else to make it work ?

**Comment by antonsoroko** [comment]
@FrelVick btw, you can make a permanent change instead of local change, by editing https://github.com/elgatito/script.elementum.burst/blob/master/burst/providers/providers.json#L2848 file in github, just click edit (pencil icon). or use standard git if you are familiar with git. see example in PR above.
