### ISSUE TITLE
Issue with full season search

### ISSUE THREAD

**Issue by rik91** [elgatito/script.elementum.burst#41]
When looking a torrent for a full season( Right Click on a Season -> Choose stream), there is an error in the log Kodi.

Burst calls an url and receives a 404 error:
It seems the url called is 
http://localhost:65220/show/60735/season/1/**play**

It should be
http://localhost:65220/show/60735/season/1/**links**
no ?

I join a log in Debug mode :
[kodi.log](https://github.com/elgatito/script.elementum.burst/files/1897601/kodi.log)

**Comment by elgatito** [comment]
It's not related to Burst. 
Will be fixed in elementum in the next version.

**Comment by rik91** [comment]
Thanks @elgatito and glad that you resume the project ! :+1
