### ISSUE TITLE
nyaa not working

### ISSUE THREAD

**Issue by goonbag** [elgatito/script.elementum.burst#42]
The nyaa domain was updated back in January but unfortunately this provider still doesn't work. From what I can see the search URL strings have changed but I am not knowledgeable enough to fix this myself.

**Comment by 112madgamer** [comment]
Same issue here I can't seem to see any URL change on the site.

**Comment by mancuniancol** [comment]
Ok, but I was following the conversation with elgatito

https://github.com/elgatito/script.elementum.burst/pull/40

I didn't know that it was more people involved

**Comment by goonbag** [comment]
Thanks mancuniancol! Just one note - the base url specifies the anime category, which to be fair is probably what most people use nyaa for, but those of us wanting to open search up to all categories can change that line to
`"base_url": "https://nyaa.si/?f=0&c=0_0&q=QUERYEXTRA&s=seeders&o=desc",`
I don't expect this change to be changed by default though, just noting this for anyone who has the issue in future.

**Comment by goonbag** [comment]
Thanks for helping fix the nyaa provider, mancuniancol. I'm still having a few issues with nyaa, maybe you can help me work out what's wrong. I'm trying to search for a live action show and I already know the categories need to be changed in the base url (c=1_0 is anime, c=0_0 is all categories). However even if I make that change I can't get the results to match what I get on the website, so there must be an issue with the pattern matching. For example, with c=0_0 searching for "game center" in elementum returns only 1 result, but on the nyaa website it returns many many more. I can't work out what needs to be changed though.

(by the way, I don't expect the categories to be changed in the base url for nyaa necessarily, as most people will probably want to use it just for anime, but I figure the pattern matching must be an issue either way)

**Comment by mancuniancol** [comment]
If you enable Kodi's debug logging.  You will see that the problem is not the URL. Instead, it is "Missing release type keyword". Not sure how to disable yet.  Sorry.

**Comment by mancuniancol** [comment]
About your second question, I just arrived here.  Some part of this addon uses my original code to search.   I want to share my new code here.  But, it is not my proyect.  Then, I am not the right person to answer you.

**Comment by goonbag** [comment]
Thanks again mancuniancol. I will play with the release types and see if it solves my problem. I appreciate your help!

**Comment by goonbag** [comment]
Ah, that's great. Thank you!

**Comment by elgatito** [comment]
Please, try with Burst v0.0.18. 
Added @mancuniancol fixed for provider definition and added Filtering settings, where you can disable filtering for release type.
