### ISSUE TITLE
FileList and TorrentLeech not working

### ISSUE THREAD

**Issue by a-nunes** [elgatito/script.elementum.burst#45]
I've been trying to use this two private providers in elementum burst without any success.

Both of them complete the Login with success, so there're two situations:

1) FileList returns some torrents correctly, but when any torrent of this provider is selected, it doesn't start to download.
2) TorrentLeech not even returns anything.

Here's the log

22:16:47.457 T:5972  NOTICE: [script.elementum.burst] [filelist] Login successful
22:16:47.457 T:5972  NOTICE: [script.elementum.burst] >          FileList search URL: https://filelist.ro/browse.php?search=arrival+2016&&cat=19&searchin=0&sort=0
22:16:47.767 T:10220  NOTICE: [script.elementum.burst] >>            RARBG returned 14 results in 1.4 seconds
22:16:47.846 T:8004  NOTICE: [script.elementum.burst] >>              YTS returned  6 results in 1.5 seconds
22:16:47.950 T:10360  NOTICE: [script.elementum.burst] [torrentleech] Login successful
22:16:47.950 T:10360  NOTICE: [script.elementum.burst] >      TorrentLeech search URL: https://www.torrentleech.org/torrents/browse/index/query/arrival%202016
22:16:48.142 T:7332  NOTICE: [script.elementum.burst] >>            1337x returned 18 results in 1.8 seconds, sending 15 best ones
22:16:48.919 T:10360  NOTICE: [script.elementum.burst] >>     TorrentLeech returned  0 results in 2.6 seconds
22:16:49.675 T:5972  NOTICE: [script.elementum.burst] >>         FileList returned 20 results in 3.3 seconds, sending 15 best ones

This is the end of log

22:17:11.095 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewTorrent       Waiting for information fetched for torrent: "6ba63a3bca8aee750a00c6fa0f37553be797ca9a"
22:17:11.095 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewTorrent       Information fetched for torrent: "6ba63a3bca8aee750a00c6fa0f37553be797ca9a"
22:17:11.096 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ onMetadataReceived  Metadata received.
22:17:11.097 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ onMetadataReceived  Downloading Arrival.2016.1080p.BluRay.DD5.1.x264-playHD
22:17:11.097 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ onMetadataReceived  Chosen file: Arrival.2016.1080p.BluRay.DD5.1.x264-playHD.mkv
22:17:11.098 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ onMetadataReceived  Saving torrent to database
22:17:11.098 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ onMetadataReceived  Setting file priorities
22:17:11.098 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ DownloadFile     Choosing file for download: Arrival.2016.1080p.BluRay.DD5.1.x264-playHD.mkv
22:17:11.194 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ SaveMetainfo     Saving torrent to D:\Quasar\Torrents\6ba63a3bca8aee750a00c6fa0f37553be797ca9a.torrent
22:17:11.291 T:2032  NOTICE: [plugin.video.elementum] go-libutp: 2018/04/16 22:17:11 socket.go:136: ignoring socket read error: read udp [::]:65034: wsarecvfrom: A conexão foi interrompida porque a atividade de manutenção de funcionamento detectou uma falha enquanto a operação estava em andamento.
22:17:11.366 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ onMetadataReceived  Setting piece priorities
22:17:11.441 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ playerLoop       Buffer loop
22:17:11.978 T:12568  NOTICE: [plugin.video.quasar] ERRO  libtorrent   ▶ logAlerts        udp_error_alert: UDP error: Foi forçado o cancelamento de uma conexão existente pelo host remoto from: 65.25.113.225
22:17:12.125 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    6ba63a: 0 B/0 B | Queued (0.00%)
22:17:12.131 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ Buffer           Setting buffer for file: Arrival.2016.1080p.BluRay.DD5.1.x264-playHD.mkv (9609038310 / 9609046437). Desired: 20971520. Pieces: 0-2 + 1144-1145, Length: 8388608 / 25165824 / 12478885, Offset: 0 / 9596559425 (8127)
22:17:12.132 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewFileReader    NewReader: 1171748392
22:17:12.132 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ NewFileReader    NewReader: 188870233
22:17:13.097 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    6ba63a: 0 B/0 B | Buffering (0.00%)
22:17:16.209 T:2032  NOTICE: Previous line repeats 3 times.
22:17:16.209 T:2032  NOTICE: [plugin.video.elementum] go-libutp: 2018/04/16 22:17:16 socket.go:136: ignoring socket read error: read udp [::]:65034: wsarecvfrom: A conexão foi interrompida porque a atividade de manutenção de funcionamento detectou uma falha enquanto a operação estava em andamento.
22:17:17.096 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    6ba63a: 0 B/0 B | Buffering (0.00%)
22:17:21.089 T:2032  NOTICE: Previous line repeats 3 times.
22:17:21.089 T:2032  NOTICE: [plugin.video.elementum] go-libutp: 2018/04/16 22:17:21 socket.go:136: ignoring socket read error: read udp [::]:65034: wsarecvfrom: A conexão foi interrompida porque a atividade de manutenção de funcionamento detectou uma falha enquanto a operação estava em andamento.
22:17:21.097 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    6ba63a: 0 B/0 B | Buffering (0.00%)
22:18:10.445 T:2032  NOTICE: Previous line repeats 49 times.
22:18:10.445 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ bufferDialog     User cancelled the buffering
22:18:10.465 T:2032  NOTICE: [plugin.video.elementum] [GIN] 2018/04/16 - 22:18:10 | 200 |   59.6348595s |             ::1 | GET      /play?library=&tmdb=329865&type=movie&uri=C%3A%5CUsers%5CArtur%5CAppData%5CRoaming%5CKodi%5Ccache%5Celementum%5C6ba63a3bca8aee750a00c6fa0f37553be797ca9a.torrent
22:18:11.097 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    6ba63a: 0 B/0 B | Buffering (0.00%)
22:18:12.692 T:11268  NOTICE: Previous line repeats 1 times.
22:18:12.692 T:11268   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.elementum/movie/329865/links]
22:18:13.096 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    6ba63a: 0 B/0 B | Buffering (0.00%)
22:18:14.205 T:2032  NOTICE: Previous line repeats 1 times.
22:18:14.205 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ Close            Deleting torrent file at D:\Quasar\Torrents\6ba63a3bca8aee750a00c6fa0f37553be797ca9a.torrent
22:18:14.206 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ Close            Deleting saved torrent file at D:\Quasar\Torrents\6ba63a3bca8aee750a00c6fa0f37553be797ca9a.torrent
22:18:14.206 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ Close            Removed Arrival.2016.1080p.BluRay.DD5.1.x264-playHD from database
22:18:14.206 T:2032  NOTICE: [plugin.video.elementum] INFO  btplayer     ▶ Close            Removing the torrent and deleting files...
22:18:14.206 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ RemoveTorrent    Removing torrent: Arrival.2016.1080p.BluRay.DD5.1.x264-playHD
22:18:14.206 T:2032  NOTICE: [plugin.video.elementum] INFO  bittorrent   ▶ Drop             Dropping torrent: Arrival.2016.1080p.BluRay.DD5.1.x264-playHD
22:18:14.206 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ Watch            Stopping watch events
22:18:14.209 T:2032  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ PlayerStop       PlayerStop

When I use a public providers, there's no problem.

**Comment by elgatito** [comment]
Issue for Torrenteech already created at #50
