### ISSUE TITLE
Can't extract episodes from season pack on TPB

### ISSUE THREAD

**Issue by ivashin** [elgatito/script.elementum.burst#46]
When trying to search for an episode on thepiratebay which is only present in a season pack, no results are found.
Example: Friends S08E20
Search results for 'Friends': https://thepiratebay.org/search/friends/0/99/0
Logs: https://pastebin.com/7qvQZ6N2

**Comment by elgatito** [comment]
Thepiratebay uses query to find exact episode, not season.

From your log:
The Pirate Bay search URL: https://thepiratebay.org/search/friends%20s08e20/0/99/200

I have made changes to allow both season+episode search.

**Comment by elgatito** [comment]
Please, try v0.0.19
