### ISSUE TITLE
new parser definition - zelka.org

### ISSUE THREAD

**Issue by dbarev** [elgatito/script.elementum.burst#48]
Hello,

I am trying to create a new parser definition for a private tracker in Bulgaria - zelka.org. Here is my definition:

    "zelka": {
        "anime_extra": "",
        "anime_keywords": "{title} {episode}",
        "anime_query": "QUERY&cat=25&incldead=0",
        "base_url": "http://zelka.org/browse.php?search=",
        "root_url": "http://zelka.org",
        "color": "FF076700",
        "general_extra": "",
        "general_keywords": "{title}",
        "general_query": "QUERY&cat=0&incldead=0",
        "language": null,
        "login_failed": "Login failed!",
        "login_object": "{'username': USERNAME, 'password': PASSWORD}",
        "login_path": "/takelogin.php",
        "movie_extra": "",
        "movie_keywords": "{title} {year}",
        "movie_query": "QUERY&cat=19&incldead=0",
        "name": "Zelka",
        "parser": {
            "infohash": "",
            "name": "item(tag='a', order=2)",
            "peers": "item(tag='td', order=-1)",
            "row": "find_once('table', ('class', 'test')).find_all('tr', start=2)",
            "seeds": "item(tag='td', order=-2)",
            "size": "item(tag='td', order=-4)",
            "torrent": "'http://zelka.org/%s' % item.take_with_root('src', 'http://img.zamunda.se/pic/download.gif')"
        },
        "private": true,
        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title} Season_{season}",
        "season_keywords2": "{title} Season{season}",
        "season_query": "QUERY&cat=7&incldead=0",
        "separator": "+",
        "show_query": "QUERY&cat=7&incldead=0",
        "subpage": false,
        "tv_extra": "",
        "tv_extra2": "",
        "tv_keywords": "{title} s{season:2}e{episode:2}",
        "tv_keywords2": ""
    },

and here is an html snapshot of a sample search on the tracker for the term 'batman' 

https://pastebin.com/66dqfUEU

and a kodi log

https://openload.co/f/8vPCuQu2uJI/kodi.log

The parser login works fine however as can be seen my challenge is that the torrent link is harder to parse as it is often in different table rows. I have however noticed that one can track it based on the download icon, so I tried to use the take_with_root function from ehp.py. I am not a python programmer so I am not sure of the correct syntax.

**Comment by dbarev** [comment]
Hello,

as no one helped me here I had to spend a lot of time trying to understand the available code but finally managed to get it right.

I have added a pull request to the maser branch to add two Bulgarian trackers.

Please accept it if you find it OK code-wise, if there are any issues with the code let me know to correct it.

**Comment by elgatito** [comment]
PR merged.

**Comment by elgatito** [comment]
Please, try v0.0.19

**Comment by dbarev** [comment]
Hi @elgatito  , thanks for accepting my commit. However I think you accidentally ruined it by reverting back the  burst/burst.py from before. Now the new Bulgarian trackers are not working.

**Comment by elgatito** [comment]
Validation was failing (flake8) because of missing unquote usage. It will be fixed in the next version.
