### ISSUE TITLE
torrentleech

### ISSUE THREAD

**Issue by Ducco** [elgatito/script.elementum.burst#50]
Torrentleech has not been working for a long time, can it have something to do whit there new site? new layout and so

**Comment by elgatito** [comment]
I have no account there.

**Comment by Ducco** [comment]
ok, anything i can do to help you check what can be at fault?

**Comment by elgatito** [comment]
An invite or share any login/password so I can enter and fix the search.

**Comment by Ducco** [comment]
email?

**Comment by elgatito** [comment]
denis.kuzmenok@gmail.com

**Comment by dbarev** [comment]
I have an account for torrentleech and will check it out. However you should have in mind this is a private tracker that rigorously enforces a quota limit and also most releases are actually scene releases i.e. multiple rar split files not suitable for direct playback. So indeed not a really good option for kodi&elementum ...

**Comment by leshets** [comment]
Same problem here, a solution will be much appreciated. Huge thanks!!!

**Comment by elgatito** [comment]
I will pick it up in the next days. Wait for the next version of Burst.

**Comment by elgatito** [comment]
It looks like something is wrong with the CloudHole app and we can't get a valid cloudflare key to bypass cloudflare defense.

**Comment by elgatito** [comment]
Now it's fine with CloudFlare, but then there is a captcha on login form. And that is a problem really. 
@mancuniancol do you have any thoughts about passing the captcha?

**Comment by dbarev** [comment]
Strange indeed, I do not get a captcha when trying to login, maybe you need to login at least once successfully from an ip range or something?

**Comment by elgatito** [comment]
First few times I had no captcha, now I do have. We do not use persistent login sessions, so we need to do login every time we try to search something.

**Comment by mancuniancol** [comment]
@elgatito, the captcha depends from IP address. If it is a VPN connection. It is normal to get that. Too many connections from the same IP

**Comment by elgatito** [comment]
@mancuniancol I know that, but:
```
We do not use persistent login sessions, so we need to do login every time we try to search something.
```

Means it will work from time to time, when there is no captcha.

**Comment by hoshsadiq** [comment]
@elgatito other apps have an optional non-intrusive notification like option to specify captcha. They are next to impossible to bypass especially services like recaptcha.

**Comment by ilanerukh** [comment]
For me I can log in, but no results:

13:37:25.474 T:67656  NOTICE: [script.elementum.burst] [torrentleech] Login successful
13:37:25.475 T:67656  NOTICE: [script.elementum.burst] >      TorrentLeech search URL: https://www.torrentleech.org/torrents/browse/index/query/thor%20ragnarok%202017/newfilter/2/facets/category%253AMovies
13:37:25.505 T:67544  NOTICE: script.module.metadatautils --> Rate limiter active for themoviedb.org - delaying request with 5 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
13:37:25.588 T:67640  NOTICE: [script.elementum.burst] >>            1337x returned 18 results in 4.3 seconds
13:37:25.656 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    a66dbb: 0 B/0 B | Queued (0.00%)
13:37:25.799 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    285aea: 0 B/0 B | Queued (0.00%)
13:37:25.959 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    360204: 0 B/0 B | Queued (0.00%)
13:37:26.282 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    693013: 0 B/0 B | Queued (0.00%)
13:37:26.371 T:67656  NOTICE: [script.elementum.burst] >>     TorrentLeech returned  0 results in 5.0 seconds

**Comment by mancuniancol** [comment]
@ilanerukh, both links show in the browser nothing.  Then, it is normal that burst gets no results.

**Comment by ilanerukh** [comment]
But there are plenty results when you search in TorrenLleech itself for the same movie: https://www.torrentleech.org/torrents/browse/index/query/Thor%20ragnarok

The query searched in burst doesn't exist, and I think this is the problem. Not logging in to the tracker.

**Comment by mancuniancol** [comment]
@ilanerukh, the page changed.  Then, the values in the json are not valid.

**Comment by ilanerukh** [comment]
I see. Is it possible to use the old site which is this:
http://classic.torrentleech.org/

And the results are in the same way:
http://classic.torrentleech.org/torrents/browse/index/query/thor+ragnarok/facets/category%253AMovies

Instead of 
https://www.torrentleech.org/torrents/browse/index/categories/8,37,43,14,12,13,41,47,15/query/thor%2Bragnarok

**Comment by mancuniancol** [comment]
@ilanerukh, the classic seems not to use javascript for the content.  Then, just changing the url in json will work.  I don't have time to do the test.  But, you can try.

**Comment by ilanerukh** [comment]
I tried, And even though it finds results in the log file, the results are not shown in kodi.

15:14:31.079 T:38292  NOTICE: [script.elementum.burst] >      TorrentLeech search URL: http://classic.torrentleech.org/torrents/browse/index/query/thor%20ragnarok%202017/newfilter/2/facets/category%253AMovies
15:14:31.336 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    693013: 0 B/0 B | Queued (0.00%)
15:14:31.401 T:44452  NOTICE: script.module.metadatautils --> Rate limiter active for themoviedb.org - delaying request with 5 seconds - Configure a personal API key in the settings to get rid of this message and the delay.
15:14:31.534 T:40152  NOTICE: [script.elementum.burst] >>              YTS returned  4 results in 3.2 seconds
15:14:31.639 T:46536  NOTICE: [script.elementum.burst] >>         MagnetDL returned 39 results in 3.3 seconds, sending 25 best ones
15:14:31.702 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    a66dbb: 0 B/0 B | Queued (0.00%)
15:14:31.749 T:39312  NOTICE: [script.elementum.burst] >>            RARBG returned 25 results in 3.4 seconds
15:14:31.756 T:77600  NOTICE: [script.elementum.burst] >>            Rutor returned 44 results in 3.4 seconds, sending 25 best ones
15:14:31.844 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    285aea: 0 B/0 B | Queued (0.00%)
15:14:31.855 T:52596  NOTICE: [script.elementum.burst] >>          TorLock returned  0 results in 3.5 seconds
15:14:32.005 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    360204: 0 B/0 B | Queued (0.00%)
15:14:32.327 T:62000  NOTICE: [plugin.video.elementum] DEBU  bittorrent   ▶ progressEvent    693013: 0 B/0 B | Queued (0.00%)
15:14:32.595 T:46408  NOTICE: [script.elementum.burst] >>            1337x returned 18 results in 4.2 seconds
15:14:32.635 T:38292  NOTICE: [script.elementum.burst] >>     TorrentLeech returned 58 results in 4.3 seconds, sending 25 best ones

**Comment by ilanerukh** [comment]
Maybe this is the problem?

`15:19:44.029 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for |Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get : unsupported protocol scheme ""
15:19:44.029 T:62000  NOTICE: [plugin.video.elementum] DEBU  ratelimit    ▶ func1            Resolved yts.am to 104.27.215.28 in 0s
15:19:44.030 T:62000  NOTICE: Previous line repeats 1 times.
15:19:44.030 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/budyzer|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/budyzer: unsupported protocol scheme ""
15:19:44.031 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/alarquitas|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/alarquitas: unsupported protocol scheme ""
15:19:44.032 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/alexfiha7797|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/alexfiha7797: unsupported protocol scheme ""
15:19:44.032 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/kam009|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/kam009: unsupported protocol scheme ""
15:19:44.033 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/aisha|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/aisha: unsupported protocol scheme ""
15:19:44.033 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/Flowzn|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/Flowzn: unsupported protocol scheme ""
15:19:44.033 T:62000  NOTICE: [plugin.video.elementum] WARN  linkssearch  ▶ 1                Resolve failed for /profile/hopoje|Cookie=PHPSESSID=4e49nat9rbgu9uhja7dn8e8fm6|User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 : Get /profile/hopoje: unsupported protocol scheme ""`

**Comment by ilanerukh** [comment]
@elgatito @mancuniancol Any possible solution for it?

**Comment by elgatito** [comment]
Will be fixed in the next version.

**Comment by elgatito** [comment]
Please, try v0.0.19

**Comment by elgatito** [comment]
Please, check Burst 0.0.31 with Elementum >= 0.0.67.
