### ISSUE TITLE
Not getting results on RARBG

### ISSUE THREAD

**Issue by ilanerukh** [elgatito/script.elementum.burst#53]
I noticed I'm not getting results at all  from RARBG recently. I search for something that I know RARBG has, and still no results. Enabled in Burst, running kodi 17.6 windows 10.

Thank you

**Comment by elgatito** [comment]
You should, at least, provide what to search and what you expect to see. At most - provide a kodi.log with debug mode "on", so I can see what pages it requests and what expects.

**Comment by ilanerukh** [comment]
I was searching for 4k content. Increased the maximum file size in burst and now I cant see the torrent.

**Comment by elgatito** [comment]
I believe you. 
Still you are not helping.

```
You should, at least, provide what to search and what you expect to see.
```

**Comment by ilanerukh** [comment]
I was trying to say that by increasing the file size in burst, everything works properly in RARBG,

**Comment by trinaldi** [comment]
Can confirm, increasing the size works

**Comment by elgatito** [comment]
They have limitation of 1 search request per 2 seconds. 
I have checked and rarbg successfully returns movies and episodes.
