### ISSUE TITLE
Проблема с rutracker

### ISSUE THREAD

**Issue by Agdiru** [elgatito/script.elementum.burst#62]
Добрый день! При поиске на торрентах rutracker и kinozal в плагине пишет что они работают медленно. Лог во вложении.
[spmc.zip](https://github.com/elgatito/script.elementum.burst/files/2232425/spmc.zip)

**Comment by Agdiru** [comment]
Да

**Comment by elgatito** [comment]
[script.elementum.burst-0.0.20.zip](https://github.com/elgatito/script.elementum.burst/files/2235598/script.elementum.burst-0.0.20.zip)
Попробуйте вручную установить из архива и что-то поищите.

**Comment by Agdiru** [comment]
Теперь не пишет что rutracker работает медленно, но и нет результата поиска на нем. Так же из списка провайдеров пропал kinozal.
[spmc.zip](https://github.com/elgatito/script.elementum.burst/files/2235782/spmc.zip)

**Comment by elgatito** [comment]
Буду еще смотреть кирилицу в логине пароле.

Кинозала не будет, они закрыли возможность брать ссылки на торренты.

**Comment by Agdiru** [comment]
Спасибо. Жду решения.

**Comment by Agdiru** [comment]
Всё так же нет результатов поиска на rutracker. Теперь чаще стал писать что rutor работает медленно, rutracker реже.
[spmc.zip](https://github.com/elgatito/script.elementum.burst/files/2245807/spmc.zip)

**Comment by Nemiroff** [comment]
@elgatito У кинозала осталась возможность брать ссылки на торрент. Но идеалогия трекера такова, что скачать можно около 3х в сутки для новичка. На зеркале раньше брался магнет, но и зеркало убрало такую возможность.

**Comment by elgatito** [comment]
@Agdiru пробуйте версию 0.0.22.

**Comment by Agdiru** [comment]
Постоянно пишет что rutor работает медленно, нет результатов поиска на rutor, rutracker и megapeer.

**Comment by Agdiru** [comment]
Поиск на rutor и megapeer победил добавив альтернативные адреса. Поиск по rutracker результатов не выдает.

**Comment by elgatito** [comment]
С блокировками поможет нормально только VPN. 
Это уже не в области дополнения.

**Comment by Agdiru** [comment]
Конкретно по rutracker через браузер на него захожу без проблем, авторизацию так же прохожу без проблем, поиск на rutracker через браузер работает. В дополнение нет результатов поиска по rutracker/
