### ISSUE TITLE
elementum burst gives error when run

### ISSUE THREAD

**Issue by skemayam** [elgatito/script.elementum.burst#63]
burst cannot star and gives and error asking to check the log. 
burst ver: 0.0.20
elementum ver : 0.0.58

log file: http://paste.kodi.tv/eyoguyemig

**Comment by Sandbird** [comment]
+1, Exactly the same error.
Tried reinstalling, selecting only 1 tracker, deleting caches, nothing worked.

**Comment by elgatito** [comment]
Please, try v0.0.21 of Burst.
