### ISSUE TITLE
Some trackers cannot find anything

### ISSUE THREAD

**Issue by martinstz** [elgatito/script.elementum.burst#65]
Hi!
After update to v.0.0.20 some trackers like Zamunda and Zelka cannot find anything. With version 0.0.19 everything working fine.
Thank you in advance!

**Comment by elgatito** [comment]
Please, try v0.0.21.

**Comment by martinstz** [comment]
Thank you!
Everything working fine with v.0.0.21! And working on Windows ;)
With respect from Bulgaria!
