### ISSUE TITLE
Burst 0.0.20 No providers error

### ISSUE THREAD

**Issue by borisantelo** [elgatito/script.elementum.burst#68]
Hello, elementum was working well, only that when it was starting besides with kodi it prompted some error message, never the less you can open the addon, but all over sudden, at the time you do a search, it began to prompt the elementum burst error. and then  the message "0 providers". The log is in https://paste.kodi.tv/oxesetafuj 
I changed to burst version 0.0.18 and it worked again.
Thanks

**Comment by elgatito** [comment]
Please, try v0.0.21
