### ISSUE TITLE
No links returned

### ISSUE THREAD

**Issue by graham23s** [elgatito/script.elementum.burst#74]
Hi Guys,

I am not sure if this is an error to do with Burst or the main Elementum addon, in the errors log i can see links are being returned for some providers:

Link log: https://paste.kodi.tv/raw/yikevapewe

But Elementum is not showing the links, it's always "No links were found" this only started a few days ago, before that everything was working fine, i haven't touched or updated any settings,
is this just my issue? i cannot see anyone talking about it when i do searches on the web.

Best reagrds

Graham

**Comment by elgatito** [comment]
Please, try to upgrade Elementum to the latest version and Burst and retry the search.

Also try to decrease number of providers. 
Then re-post the log file. 

You can use Elementum settings -> Advanced -> Logging -> Paste ... for easy pastebin it.

**Comment by elgatito** [comment]
You have a lot of network errors in the log. 
There was a bug with magnetdl, but I still can't get results because of CloudFlare. It's more often used.

**Comment by graham23s** [comment]
Hi elgatito,

Ah i see, CloudFlare is a pain, i have come accross that in my development travels too.

I did notice, on a FireStick everything works much better, i believe it's this Android box which is the issue and not Elementum, i'll fix up those network issues and debug this box a bit more :)

regards

Graham
