### ISSUE TITLE
CorsaroNero doesnt provide any result

### ISSUE THREAD

**Issue by LinearLambda** [elgatito/script.elementum.burst#79]
Hello everybody,

TNT is working great but CorsaroNero is not providing any result..

**Comment by EffeF** [comment]
For me, any Italian provider does not provide any results with the latest version of the script. Before updating I had the 0.0.19, and they worked properly.

**Comment by elgatito** [comment]
Log file is needed - http://elementum.surge.sh/contribute/log/

**Comment by LinearLambda** [comment]
guys sorry for the delay in my reply

i was not using the lastest version of elementum and burst, now i have updated and it works all fine.

thanks you very much for your support

**Comment by elgatito** [comment]
Ilcorsaronero, ilcorsaroblu would be fixed in the next version.
