### ISSUE TITLE
ZipManager: not a zip file!

### ISSUE THREAD

**Issue by Nemiroff** [elgatito/script.elementum.burst#8]
Ошибка возникает если брать zip собранный через make (make zip).
На OrangePi PC+, OpenELEC, Kodi 16.1 помогло отключить сжатие файла в строке №15. Конечная версия выглядит так:
`	$(GIT) archive -0 --format zip --prefix $(NAME)/ --output $(ZIP_FILE) HEAD`
Возможно будет работать при -1 -2

**Comment by elgatito** [comment]
Log file for error?

**Comment by Nemiroff** [comment]
Свой не сохранял, есть с похожего одноплатника на форуме http://xbmc.ru/forum/showpost.php?p=118200&postcount=482.

**Comment by elgatito** [comment]
Конкретно эта ошибка была из-за того что версия 0.0.5 была в релизе, но архива не было на github, и плагин возвращал не zip, а обычный html (404) под его видом.

**Comment by Nemiroff** [comment]
Собирал в своем репозитории, даже при установке из Коди выдоет эту ошибку. Сегодня попробую в разных вариантах. Возможно ошибка появляется на одноплатниках.

**Comment by Nemiroff** [comment]
Проверил всё по новой, ошибка не появилась.
