### ISSUE TITLE
3й переход для получения торент-файла

### ISSUE THREAD

**Issue by vapustovoyt** [elgatito/script.elementum.burst#83]
Добрый день!
Пишу парсер под свои любимые сайты с сериалами и столкнулся с проблемой:
один сайт нуждается в дополнительном переходе для получения торент-файла.
например- сылка поиска http://site/search/?q=Сериал (получаем результат, берем ид сериала)
после нужно перейти на http://site/series/id001/seasons (получаем список сезонов, серий, ид)
и уже на 3м переходе типа http://site/v_search.php?a=111222333 перекидает на левый сайт http://site2/index.php?ID&SEASONS&EPISOD&USER&HASH где получаем список торент-файлов (111-ид сериала, 222-сезон, 333 серия)
и увы нельзя собрать ссылку за 2 перехода
можно ли как-то решить такую проблему?

**Comment by elgatito** [comment]
Точно не буду добавлять еще один вызов. Даже 2 это много.
