### ISSUE TITLE
TNTVillage doesnt provide any result

### ISSUE THREAD

**Issue by EffeF** [elgatito/script.elementum.burst#84]
I do not know if my problem is the same as [the other user has](https://github.com/elgatito/script.elementum.burst/issues/79), since he says he has solved, so I think it is better to open a new issue.

With script.elementum.burst v0.0.19 installed:
```logos
DEBUG: [script.elementum.burst] [tntvillage] After keywords  - Query: u'fringe s01e01' - Extra: ''
DEBUG: [script.elementum.burst] -   tntvillage query: u'fringe s01e01'
DEBUG: [script.elementum.burst] >>>>>> tntvillage would send 2 torrents to Elementum <<<<<<<
NOTICE: [script.elementum.burst] >>       TNTVillage returned  2 results in 2.0 seconds
```

With script.elementum.burst v0.0.29 installed:
```logos
DEBUG: [script.elementum.burst] [tntvillage] After keywords  - Query: 'fringe%20s01e01' - Extra: ''
DEBUG: [script.elementum.burst] -   tntvillage query: 'fringe%20s01e01'
DEBUG: [script.elementum.burst] >>>>>> tntvillage would send 0 torrents to Elementum <<<<<<<
NOTICE: [script.elementum.burst] >>          TNTVillage returned  0 results in 4.4 seconds
```

Apparently the search query has changed with the latest versions of script.elementum.burst, and therefore TNTVillage no longer provides results.

Full logs:
[v0.0.19](https://pastebin.com/raw/vZSNFVvG)
[v0.0.29](https://pastebin.com/raw/Gt1QGYsd)

**Comment by elgatito** [comment]
Should be fixed in the next release.
