### ISSUE TITLE
No links were found

### ISSUE THREAD

**Issue by edureis95** [elgatito/script.elementum.burst#85]
I have a newly installed Elementum and Elementum Burst can't find any links.

However the log files shows correct urls that have torrents in them and yet, no results.

`02:38:51.382 T:8308  NOTICE: [script.elementum.burst] [rarbg] Using translated 'original' title u'avengers infinity war'
02:38:51.382 T:2508  NOTICE: [script.elementum.burst] [1337x] Using translated 'original' title u'avengers infinity war'
02:38:51.383 T:12632  NOTICE: [script.elementum.burst] [magnetdl] Using translated 'original' title u'avengers infinity war'
02:38:51.383 T:3908  NOTICE: [script.elementum.burst] [yts] Using translated 'original' title u'avengers infinity war'
02:38:51.386 T:2508  NOTICE: [script.elementum.burst] >                1337x search URL: https://www.1337x.to/search/avengers+infinity+war+2018/1/
02:38:51.386 T:12632  NOTICE: [script.elementum.burst] >             MagnetDL search URL: http://www.magnetdl.com/a/avengers-infinity-war-2018/
02:38:51.386 T:3908  NOTICE: [script.elementum.burst] >                  YTS search URL: https://yts.ag/api/v2/list_movies.json?query_term=avengers%20infinity%20war&sort_by=seeds&order_by=desc
02:38:51.660 T:12632  NOTICE: [script.elementum.burst] >>            MagnetDL returned  0 results in 0.3 seconds
02:38:52.623 T:3908  NOTICE: [script.elementum.burst] >>                 YTS returned  0 results in 1.3 seconds
02:38:52.636 T:2508  NOTICE: [script.elementum.burst] >>               1337x returned  0 results in 1.3 seconds
02:38:52.660 T:8308  NOTICE: [script.elementum.burst] >                RARBG search URL: https://torrentapi.org/pubapi_v2.php?mode=search&search_string=avengers+infinity+war+2018&category=14;48;17;44;45;47;50;51;52;42;46&format=json_extended&app_id=script.elementum.burst&token=w8qk7456it
02:38:52.982 T:8308  NOTICE: [script.elementum.burst] >>               RARBG returned  0 results in 1.6 seconds
02:38:53.129 T:13340  NOTICE: [script.elementum.burst] Providers returned 0 results in 1.76 seconds`

Edit: The weird thing is that if I keep trying to open the movie, elementum will eventually find a link after around 10-20 tries.

**Comment by joaoflf** [comment]
Same here

**Comment by elgatito** [comment]
No log = no help.
http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment]
Trackers more and more enable cloudflare, which we can't bypass.
