### ISSUE TITLE
RPi3 - LE 8.2.5 - on boot up keeps saying Burst is not installed

### ISSUE THREAD

**Issue by john3voltas** [elgatito/script.elementum.burst#86]
I have LibreELEC 8.2.5 on a Raspberry Pi 3 and I installed Elementum/Burst on it.
Every time I reboot/boot up the Pi I get an OSD message stating the there is an addon companion for Elementum called Burst that I might be interested.
I've installed Burst, uninstalled and reinstalled it more than a dozen times but I keep getting that nag message.
In case no one else is experiencing the same issue, could this be due to the fact that I am using profiles in Kodi? My Kodi box doesn't boot directly into Kodi. Instead it boots into a menu where I can choose a Kodi profile, mine, my wife's, my daughter's, etc. Could this be related to my Burst issue.
Mind you that despite the nag message, Elementum and Burst still work just fine on my Pi.
Cheers

**Comment by elgatito** [comment]
It can be caused by profile usage. I cannot test this.

**Comment by elgatito** [comment]
I have tried creating new profile and installing Elementum+Burst there and it worked. That was on Kodi 18. Not sure if your issue happens on pre-18?

**Comment by john3voltas** [comment]
Really nice of you for keep trying to help me. Impolite of me not checking my own topic once in a while. So sorry for that but life kept me a bit busy this last month...
Cool to see that you're already testing Elementum on Leia. I'm still on plain "old" Krypton (LibreElec 8.2.5 - Kodi 17.6) but I am already thinking of installing LE 8.9beta with Kodi 18 under the hood on a new sd card just for checking.
This might also be related to LibreElec and not to Kodi itself or it might be related to other addons that I usually install.
I will check with a Leia build this next weekend and will post my findings afterwards.
Thanks a bunch for your support.
Cheers

**Comment by john3voltas** [comment]
Have tested with a "Leia" Beta build and I couldn't replicate the issue.
Wen't back to my 17.6 backup and I still can replicate the issue with user choice at Kodi boot having Burst saying it's not installed, when in fact it is and it even works.
I will now consider to either reinstalling 17.6 from scratch and see if it still occurs or taking the red pill and move on to "Leia" which is still a bit buggy, at least on LibreELEC.
Thanks mate.
Cheers

**Comment by john3voltas** [comment]
Today I've retested it, this time both on a Pi3 and also on a LibreELEC VM.
Fresh new installs. Results are the same both on the Pi and on the VM. LibreELEC 8.2.5 (v17.6) has the issue whereas LibreELEC 9 (v18) doesn't have the issue.
I don't know how much more time it's going to take v18 to go stable/release. I think we're still 6 months away from release.
If it's something easy, it would be cool if you could fix it in v17.6 but if it's something that will completely break your development pace and taking into account that I might be the only soul using Elementum and Kodi profiles, then just forget about it.
Thanks anyways.
Cheers

**Comment by john3voltas** [comment]
Kodi v18.x has been stable for a very long time and the problem was gone as soon as I upgraded.
Case closed.
