### ISSUE TITLE
No links found when apostrophe in title

### ISSUE THREAD

**Issue by henryjfry** [elgatito/script.elementum.burst#89]
Hello

I would post logs but I just get the link "paste.ubuntu.com" when I try. But this problem has been reported before and never resolved.

When a show name has an apostrophe in it elementum will not find any results.  As per the unresolved report:

https://github.com/elgatito/script.elementum.burst/issues/31

"This is still a problem with elementum not returning results for shows with apostrophes in their titles.

So marvels daredevil returns no results from tpb, rarbg, kickass, torrentz, megapeer, rutor, 1337x, magnetdl, newstudio, basically any provider which works fine when TVDB doesn't include an apostrophe in the show or movie name."

**Comment by herrwusel** [comment]
Maybe add an option on how the apostrophe is handled is a solution.

**Comment by elgatito** [comment]
> I would post logs but I just get the link "paste.ubuntu.com" when I try
You get a link to a log file.

**Comment by elgatito** [comment]
There is no perfect solution for handling apostrophe in the query. Some trackers don't search with it, some do.

**Comment by jellespijker** [comment]
Are there workarounds that could be implemented, maybe a setting per provider or something like that. Because searching with EZTV gives a lot of false positives that pollute the actual list.

**Comment by jellespijker** [comment]
Discard comment above, I just noticed issue #122 and it seems there is related PR
