### ISSUE TITLE
Results not listed (kodi 17.3, win7)

### ISSUE THREAD

**Issue by Gregsr** [elgatito/script.elementum.burst#93]
I have this message "no link found" but, in the log, there are links found. Issue is that these links are not listed. Same issue than #10 
[kodi.log](https://github.com/elgatito/script.elementum.burst/files/2640958/kodi.log)

**Comment by elgatito** [comment]
Next version of Elementum will have increased time of resolve. Burst returns results, Elementum cannot download torrent files in time.

**Comment by elgatito** [comment]
Please, check Burst 0.0.31 with Elementum >= 0.0.67.

**Comment by Gregsr** [comment]
It does not work
[kodi.log](https://github.com/elgatito/script.elementum.burst/files/2683503/kodi.log)

**Comment by elgatito** [comment]
You have overrides for providers?

**Comment by Gregsr** [comment]
No I have not.
I only use Yggtorrent, Torrent9 and Cpasbien

**Comment by elgatito** [comment]
Please, try 0.0.32.

**Comment by chicungunya** [comment]
Same for me. No link found and same providers...
Why ?

**Comment by Gregsr** [comment]
Downloading does not start
[kodi.log](https://github.com/elgatito/script.elementum.burst/files/2696066/kodi.log)

**Comment by Gregsr** [comment]
It works fine with elementum 0.0.69 and burst 0.0.33

Thanks!
