### ISSUE TITLE
Elementum doesn't found Grey's Anatomy serie

### ISSUE THREAD

**Issue by a-nunes** [elgatito/script.elementum.burst#97]
I've tried to search for grey's anatomy show, but it doesn't return any results. After looking closely to log and try to repeat the searches manually in trackers sites, I've found the error:

Most trackers use greys anatomy torrent name (without the '). Could you correct this parser to not use the " ' " char, please?

**Comment by elgatito** [comment]
There is no perfect solution. 
Some providers understand quotes and does not find result without it, some don't.

**Comment by a-nunes** [comment]
I've tried to add this to list of 'exceptions' in filtering.py:

title = title.replace("grey's anatomy", 'greys anatomy')

 but didn't work. Could you help me to use it?

**Comment by a-nunes** [comment]
I've changed this in normalize.py, then it worked better for me:

control_chars = ''.join(map(unichr, range(0, 32) + range(33,47) + range(127, 160)))

**Comment by elgatito** [comment]
I have added option to Burst 0.0.34 to remove quote from queries.
