### ISSUE TITLE
Wrong or No results from some providers

### ISSUE THREAD

**Issue by dancaer69** [elgatito/script.elementum.burst#98]
I don't get results from some providers or results for different series/episodes. I tested with "Smallville" series because I tried some different episodes and always get results for "Titans" or "Marvel's Runaways" and only from EZTV. Testing for smalvile S01E10, here is the relative log messages:

`10:18:01.225 T:140010774759168  NOTICE: [script.elementum.burst] Burstin' with RARBG, EZTV, 1337x, TorrentFunk, ETTV, HD Torrents, YTS, YourBitTorrent, MegaPeer, Torrent9, TorrentLeech, MagnetDL, TorLock
10:18:01.252 T:140010758067968  NOTICE: [script.elementum.burst] >                 EZTV search URL: https://eztv.ag/search/Smallville-s01e10
10:18:01.267 T:140010641610496  NOTICE: [script.elementum.burst] >                  YTS search URL: https://yts.ag/api/v2/list_movies.json?query_term=Smallville%20s01e10&sort_by=seeds&order_by=desc
10:18:01.276 T:140010749675264  NOTICE: [script.elementum.burst] >                1337x search URL: https://www.1337x.to/search/Smallville+s01e10/1/
10:18:01.278 T:140010741282560  NOTICE: [script.elementum.burst] >          TorrentFunk search URL: https://www.torrentfunk.com/all/torrents/Smallville-s01e10.html
10:18:01.312 T:140010650003200   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.hd-torrents'.
10:18:01.313 T:140010650003200   ERROR: Previous line repeats 1 times.
10:18:01.313 T:140010650003200   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.hd-torrents-mc'.
10:18:01.318 T:140010658395904   ERROR: Previous line repeats 1 times.
10:18:01.318 T:140010658395904  NOTICE: [script.elementum.burst] >                 ETTV search URL: https://www.ettv.tv/torrents-search.php?search=Smallville%20s01e10&cat=0&incldead=0&lang=00
10:18:01.322 T:140008669304576  NOTICE: [script.elementum.burst] >             MegaPeer search URL: http://megapeer.org/browse.php?search=Smallville+s01e10&age=&cat=0&stype=0&sort=0&ascdesc=0
10:18:01.329 T:140008084301568  NOTICE: [script.elementum.burst] >             Torrent9 search URL: http://www.torrent9.blue/search_torrent/Smallville-s01e10.html
10:18:01.340 T:140008067516160  NOTICE: [script.elementum.burst] >             MagnetDL search URL: https://www.magnetdl.com/S/Smallville-s01e10/
10:18:01.340 T:140010610296576  NOTICE: [script.elementum.burst] >       YourBitTorrent search URL: https://yourbittorrent.com/?q=Smallville+s01e10
10:18:01.344 T:140008046364416  NOTICE: [script.elementum.burst] >              TorLock search URL: https://www.torlock2.com/all/torrents/Smallville-s01e10.html
10:18:01.347 T:140008075908864   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.torrentleech'.
10:18:01.347 T:140008075908864   ERROR: Previous line repeats 1 times.
10:18:01.347 T:140008075908864   ERROR: EXCEPTION: Unknown addon id 'script.magnetic.torrentleech-mc'.
10:18:01.526 T:140008075908864   ERROR: Previous line repeats 1 times.
10:18:01.526 T:140008075908864   ERROR: [script.elementum.burst] [torrentleech] Login failed: 503
10:18:01.529 T:140008075908864  NOTICE: [script.elementum.burst] >>        TorrentLeech returned  0 results in 0.3 seconds
10:18:01.571 T:140010741282560  NOTICE: [script.elementum.burst] >>         TorrentFunk returned  0 results in 0.3 seconds
10:18:01.668 T:140010610296576  NOTICE: [script.elementum.burst] >>      YourBitTorrent returned  1 results in 0.4 seconds
10:18:01.673 T:140010783151872  NOTICE: [script.elementum.burst] >                RARBG search URL: https://torrentapi.org/pubapi_v2.php?mode=search&search_string=Smallville+s01e10&format=json_extended&app_id=script.elementum.burst&token=wosz9np4qm
10:18:01.701 T:140008067516160  NOTICE: [script.elementum.burst] >>            MagnetDL returned  0 results in 0.5 seconds
10:18:01.820 T:140010749675264  NOTICE: [script.elementum.burst] >>               1337x returned  0 results in 0.6 seconds
10:18:01.857 T:140008046364416  NOTICE: [script.elementum.burst] >>             TorLock returned  0 results in 0.6 seconds
10:18:01.896 T:140008084301568  NOTICE: [script.elementum.burst] >>            Torrent9 returned  0 results in 0.7 seconds
10:18:01.902 T:140008669304576  NOTICE: [script.elementum.burst] >>            MegaPeer returned  0 results in 0.7 seconds
10:18:01.937 T:140010650003200   ERROR: [script.elementum.burst] [hd-torrents] Login failed: Wrong username or password
10:18:01.938 T:140010650003200  NOTICE: [script.elementum.burst] >>         HD Torrents returned  0 results in 0.7 seconds
10:18:02.057 T:140010641610496  NOTICE: [script.elementum.burst] >>                 YTS returned  0 results in 0.8 seconds
10:18:02.114 T:140010783151872  NOTICE: [script.elementum.burst] >>               RARBG returned  0 results in 0.9 seconds
10:18:02.703 T:140010758067968  NOTICE: [script.elementum.burst] >>                EZTV returned 41 results in 1.5 seconds, sending 15 best ones
10:18:03.644 T:140010658395904  NOTICE: [script.elementum.burst] >>                ETTV returned  0 results in 2.4 seconds
10:18:03.836 T:140010774759168  NOTICE: [script.elementum.burst] Providers returned 15 results in 2.61 seconds
10:18:03.840 T:140008206001920  NOTICE: [plugin.video.elementum] [GIN] 2018/12/22 - 08:18:03 | 200 |      81.574µs |      `

I only see 15 results from EZTV. I tried to manually go to some of the providers using the links from log file, or manually search on these sites and I had some more results.
Using the link from log file for "youbittorrent" provider I get 1 result for this episode, which doesn't show in burst.
For "magnetDL" using the link from log file it gets me to a 404 error, but If I manually search I get 1 result again.
I don't know for other series/episodes because I get some relative links, but I always have results for different series/episodes and I think that I get only from EZTV.
Can you please take a look?
Thanks.

**Comment by elgatito** [comment]
Your log does not help. Make correct one - http://elementum.surge.sh/contribute/log/

**Comment by dancaer69** [comment]
Here it is:
https://www.dropbox.com/s/fj64p3rgve7wpif/kodi.log?dl=0

**Comment by kaiketsuT** [comment]
Also having this issue, I am attempting to use nyaa.si to get most of my torrents but nothing shows up when searching known working searches in web browsers.

Eztv also shows no results for popular shows 

I can use these sites fine in a web browser and can run the torrent if I type the link directly

I have the internal proxy enabled but doesn't effect it either way

Running Kodi 18.1 on firetvstick

**Comment by elgatito** [comment]
I have made some changes to EZTV provider. 
Please, check v0.0.36.

**Comment by alexandrupopescutm** [comment]
Hi,

I have exactly the same issue. I cannot get going ETTV for example.

**Comment by elgatito** [comment]
Closing this issue as being old. Please, re-open if it is still relevant.
