### ISSUE TITLE
How to debug custom provider

### ISSUE THREAD

**Issue by a-nunes** [elgatito/script.elementum.burst#99]
I'm trying to add a new custom provider, but it isn't working properly. Could you help me to debug it? I want to know, with the logs, where I'm going wrong.

"manicomio-share": {
        "enabled": true,
        "predefined": false,
        "private": true,
        "name": "Manicomio-Share",
        "languages": "pt",
        "anime_extra": "",
        "anime_keywords": "{title:original} {episode}",
        "anime_query": "&parent_cat=Anime",
        "base_url": "https://www.manicomio-share.com/torrents.php?busca=QUERY&EXTRA",
        "color": "558D19",
        "general_extra": "",
        "general_keywords": "{title:original}",
        "general_query": "",
        "language": null,
        "login_failed": "Atenção! Nome de usuário ou senha inválidos",
        "login_object": "{'username': USERNAME, 'password': PASSWORD, 'unlock': '1'}",
        "login_path": "/index.php",
        "movie_extra": "",
        "movie_keywords": "{title:original}",
        "movie_query": "&parent_cat=Filmes",
        "parser": {
            "infohash": "",
            "name": "item(tag='a', order=2, attribute='title')",
            "peers": "item(tag='span', order=3)",
            "row": "find_once('table', ('id', 'tbltorrent')).find_all('tr', start=2)",
            "seeds": "item(tag='span', order=2)",
            "size": "item(tag='td', order=4)",
            "torrent": "item(tag='a', attribute='href', order=6)"
        },
        "season_extra": "",
        "season_extra2": "",
        "season_keywords": "{title:original} season {season:2}",
        "season_keywords2": "{title:original} s{season:2}",
        "season_query": "&parent_cat=Series",
        "separator": "+",
        "show_query": "&parent_cat=Series",
        "subpage": false,
        "tv_extra": "",
        "tv_extra2": "",
        "tv_keywords": "{title:original} s{season:2}e{episode:2}",
        "tv_keywords2": "{title:original} s{season:2}"
    }

Here's is the html of a search that I did.

https://pastebin.com/vpn6mrcy

It's login properly, but it isn't getting any results, here's the log file:

https://pastebin.com/zSQ4Y8tR

I already tried to use this too:

"row": "find_all('tr', ('id', 'closest'))"

Is there a way to look for the debug file to find out why it isn't working good?

**Comment by elgatito** [comment]
Enable debug in Kodi, Enable parser debug in Burst settings (last tab).
And suggest to disable all other providers, to see the log more easily.

**Comment by elgatito** [comment]
Description is pretty straight... It does not get any page content. 
You can open the url to see what outputs there, maybe url is wrong or you can be filtered by some anti-robot defense.

**Comment by a-nunes** [comment]
I've tried a lot of other things, but the results still the same. The problem seems to be on my tracker. Closing here, thank you.
